import frontend.training.BasicTrainingPatient
import frontend.training.BasicTrainingPatient
import frontend.training.FunctionTrianingPatient
import frontend.training.MirrorPatient
import frontend.training.SensorimotorPatient
import frontend.training.SpaceTrainingPatient
import frontend.training.Training
import frontend.training.HistoricalHistory
