# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):  # 感觉运动观察训练-病人界面
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.leftPictureLabel = QtWidgets.QLabel(Form)
        self.leftPictureLabel.setGeometry(QtCore.QRect(0, 0, 960, 1080))
        self.leftPictureLabel.setObjectName("leftPictureLabel")
        self.rightPictureLabel = QtWidgets.QLabel(Form)
        self.rightPictureLabel.setGeometry(QtCore.QRect(960, 0, 960, 1080))
        self.rightPictureLabel.setObjectName("rightPictureLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class sensorimotor_Patient(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super(sensorimotor_Patient, self).__init__()
        self.setupUi(self)

    def showLeftPictureByPicture(self, pic):
        self.leftPictureLabel.setPixmap(pic)
        ...

    def showRightPictureByPicture(self, pic):
        self.rightPictureLabel.setPixmap(pic)
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = sensorimotor_Patient()
    gui.show()
    sys.exit(app.exec_())
