# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# 空间想象界面-患者端
import sys
import time

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1900, 1250)
        self.pictureLabel = QtWidgets.QLabel(Form)
        self.pictureLabel.setGeometry(QtCore.QRect(300, 40, 1300, 1100))
        self.pictureLabel.setObjectName("picturelistView")
        self.leftButton = QtWidgets.QPushButton(Form)
        self.leftButton.setGeometry(QtCore.QRect(10, 540, 260, 150))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(Form)
        self.rightButton.setGeometry(QtCore.QRect(1630, 540, 260, 150))
        self.rightButton.setObjectName("rightButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leftButton.setText(_translate("Form", "左手"))
        self.rightButton.setText(_translate("Form", "右手"))


class SpaceTrainingPatient(QtWidgets.QMainWindow, Ui_Form):
    # singal = pyqtSignal(list)
    def __init__(self):
        super(SpaceTrainingPatient, self).__init__()
        self.setupUi(self)

        self.nowSelection = None
        self.timeSelected = time.time()

        self.leftButton.mousePressEvent = self.leftHandButtonLeftClick
        self.rightButton.mousePressEvent = self.rightHandButtonLeftClick

        self.desktop = QApplication.desktop()
        self.setGeometry(self.desktop.screenGeometry(1))

    def replacePicture(self, pic):
        self.pictureLabel.setPixmap(pic)
        ...

    def rightHandButtonLeftClick(self, *args):
        self.nowSelection = "右"
        self.timeSelected = time.time()
        pass

    def leftHandButtonLeftClick(self, *args):
        self.nowSelection = "左"
        self.timeSelected = time.time()
        pass


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = SpaceTrainingPatient()
    gui.show()
    sys.exit(app.exec_())
