# -*- coding: utf-8 -*-
import json
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, Qt
from PyQt5.QtWidgets import QTreeWidgetItem

import config


class Ui_Form(object):
    def setupUi(self, Form):
        Form.resize(1920, 1080)
        Form.setStyleSheet("background:rgb(242,249,255)")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 160, 40))
        self.label.setStyleSheet("font:14pt")

        self.trianTimeDateEdit = QtWidgets.QDateEdit(QDate.currentDate(), Form)
        self.trianTimeDateEdit.setGeometry(QtCore.QRect(180, 10, 220, 40))
        self.trianTimeDateEdit.setStyleSheet("font:14pt;background:white")
        self.trianTimeDateEdit.setCalendarPopup(True)

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 240, 40))  # 空间训练参数设置
        self.label_2.setStyleSheet("font:14pt;color:rgb(0,138,200)")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 135, 180, 40))
        self.label_3.setStyleSheet("font:14pt")

        self.pictureNum = QtWidgets.QComboBox(Form)
        self.pictureNum.setGeometry(QtCore.QRect(220, 135, 150, 40))
        self.pictureNum.addItems(['', '10', '20', '30', '40', '50', '60'])
        self.pictureNum.setStyleSheet("font:14pt;background:white")

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(380, 135, 240, 40))
        self.label_4.setStyleSheet("font:14pt")

        self.playSpeed = QtWidgets.QComboBox(Form)
        self.playSpeed.setGeometry(QtCore.QRect(570, 135, 150, 40))
        self.playSpeed.addItems(['', '3', '5', '7', '8', '9', '10'])
        self.playSpeed.setStyleSheet("font:14pt;background:white")

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(750, 135, 240, 40))
        self.label_5.setStyleSheet("font:14pt")

        self.selecthard = QtWidgets.QComboBox(Form)
        self.selecthard.setGeometry(QtCore.QRect(870, 135, 150, 40))
        self.selecthard.addItems(['', '低难度', '中难度', '高难度'])
        self.selecthard.setStyleSheet("font:14pt;background:white")

        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 300, 40))
        self.label_6.setStyleSheet("font:14pt")

        self.handComboBox = QtWidgets.QComboBox(Form)
        self.handComboBox.setGeometry(QtCore.QRect(300, 200, 150, 40))
        self.handComboBox.addItems(['左', '右'])
        self.handComboBox.setStyleSheet("font:14pt;background:white")

        self.basic_selectTrainingFrame = QtWidgets.QFrame(Form)  # 基本动作训练容器
        self.basic_selectTrainingFrame.setGeometry(QtCore.QRect(10, 260, 600, 600))
        self.basic_selectTrainingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.basic_selectTrainingFrame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.basic_scrollArea = QtWidgets.QScrollArea(self.basic_selectTrainingFrame)  # 基本动作训练滑动窗口
        self.basic_scrollArea.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.basic_scrollArea.setWidgetResizable(True)

        self.basic_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.basic_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.basic_scrollAreaWidgetContents.setMinimumHeight(3000)
        self.basic_scrollArea.setWidget(self.basic_scrollAreaWidgetContents)

        self.basic_leftTree = QtWidgets.QTreeWidget(self.basic_scrollAreaWidgetContents)
        self.basic_leftTree.setGeometry(QtCore.QRect(0, 0, 700, 10000))
        self.basic_leftTree.setStyleSheet('font:14pt')
        # 为树控件指定列数
        self.basic_leftTree.setColumnCount(1)
        # 指定列标签
        self.basic_leftTree.setHeaderLabels(['基本训练动作_左'])
        # 根节点
        self.basic_trainingLeftActionRoot_1 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作1根节点
        self.basic_trainingLeftActionRoot_1.setText(0, '拇指运动')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_1.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.basic_trainingLeftAction1Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_1)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction1Child_1.setText(0, '拇指对食指')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction1Child_1.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_2.setText(0, '拇指对小指指根')
        self.basic_trainingLeftAction1Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_3.setText(0, '拇指环转')
        self.basic_trainingLeftAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_4 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_4.setText(0, '拇指屈伸')
        self.basic_trainingLeftAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_5 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_5.setText(0, '拇指外展')
        self.basic_trainingLeftAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_6 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_6.setText(0, '拇指对四指')
        self.basic_trainingLeftAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_7 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_7.setText(0, '拇指对掌')
        self.basic_trainingLeftAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction1Child_8 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_1)
        self.basic_trainingLeftAction1Child_8.setText(0, '拇指伸展')
        self.basic_trainingLeftAction1Child_8.setCheckState(0, Qt.Unchecked)

        self.basic_trainingLeftActionRoot_2 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingLeftActionRoot_2.setText(0, '精细灵活性运动')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_2.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingLeftAction2Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction2Child_1.setText(0, '比OK')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction2Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingLeftAction2Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_2)
        self.basic_trainingLeftAction2Child_2.setText(0, '比数字')
        self.basic_trainingLeftAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction2Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_2)
        self.basic_trainingLeftAction2Child_3.setText(0, '侧捏')
        self.basic_trainingLeftAction2Child_3.setCheckState(0, Qt.Unchecked)

        # 根节点
        self.basic_trainingLeftActionRoot_3 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingLeftActionRoot_3.setText(0, '抓握运动')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_3.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingLeftAction3Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction3Child_1.setText(0, '钩状抓握')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction3Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingLeftAction3Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_3)
        self.basic_trainingLeftAction3Child_2.setText(0, '球状抓握')
        self.basic_trainingLeftAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction3Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_3)
        self.basic_trainingLeftAction3Child_3.setText(0, '握拳')
        self.basic_trainingLeftAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction3Child_4 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_3)
        self.basic_trainingLeftAction3Child_4.setText(0, '直拳')
        self.basic_trainingLeftAction3Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction3Child_5 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_3)
        self.basic_trainingLeftAction3Child_5.setText(0, '柱状抓握')
        self.basic_trainingLeftAction3Child_5.setCheckState(0, Qt.Unchecked)

        self.basic_trainingLeftActionRoot_4 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingLeftActionRoot_4.setText(0, '手指动作')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_4.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingLeftAction4Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_4)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction4Child_1.setText(0, '手指内收外展')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction4Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingLeftAction4Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_4)
        self.basic_trainingLeftAction4Child_2.setText(0, '四指单独屈伸')
        self.basic_trainingLeftAction4Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction4Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_4)
        self.basic_trainingLeftAction4Child_3.setText(0, '四指屈曲')
        self.basic_trainingLeftAction4Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction4Child_4 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_4)
        self.basic_trainingLeftAction4Child_4.setText(0, '四指伸展')
        self.basic_trainingLeftAction4Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction4Child_5 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_4)
        self.basic_trainingLeftAction4Child_5.setText(0, '掌指关节屈曲')
        self.basic_trainingLeftAction4Child_5.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction4Child_6 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_4)
        self.basic_trainingLeftAction4Child_6.setText(0, '指尖关节伸展')
        self.basic_trainingLeftAction4Child_6.setCheckState(0, Qt.Unchecked)

        self.basic_trainingLeftActionRoot_5 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingLeftActionRoot_5.setText(0, '腕部运动')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_5.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingLeftAction5Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_5)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction5Child_1.setText(0, '尺偏')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction5Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingLeftAction5Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_5)
        self.basic_trainingLeftAction5Child_2.setText(0, '桡偏')
        self.basic_trainingLeftAction5Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction5Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_5)
        self.basic_trainingLeftAction5Child_3.setText(0, '前臂中立位腕背伸')
        self.basic_trainingLeftAction5Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction5Child_4 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_5)
        self.basic_trainingLeftAction5Child_4.setText(0, '前臂旋前位腕背伸')
        self.basic_trainingLeftAction5Child_4.setCheckState(0, Qt.Unchecked)

        self.basic_trainingLeftActionRoot_6 = QTreeWidgetItem(self.basic_leftTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingLeftActionRoot_6.setText(0, '前臂旋转')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingLeftActionRoot_6.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingLeftAction6Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_6)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingLeftAction6Child_1.setText(0, '前臂旋前')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingLeftAction6Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingLeftAction6Child_2 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_6)
        self.basic_trainingLeftAction6Child_2.setText(0, '前臂旋后')
        self.basic_trainingLeftAction6Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingLeftAction6Child_3 = QTreeWidgetItem(self.basic_trainingLeftActionRoot_6)
        self.basic_trainingLeftAction6Child_3.setText(0, '前臂旋前旋后')
        self.basic_trainingLeftAction6Child_3.setCheckState(0, Qt.Unchecked)

        self.basic_rightTree = QtWidgets.QTreeWidget(self.basic_scrollAreaWidgetContents)
        self.basic_rightTree.setGeometry(QtCore.QRect(0, 0, 700, 10000))
        self.basic_rightTree.setStyleSheet('font:14pt')
        self.basic_rightTree.setVisible(False)
        # 为树控件指定列数
        self.basic_rightTree.setColumnCount(1)
        # 指定列标签
        self.basic_rightTree.setHeaderLabels(['基本训练动作_右'])
        # 根节点
        self.basic_trainingrightActionRoot_1 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作1根节点
        self.basic_trainingrightActionRoot_1.setText(0, '拇指运动')  # 0代表第一列，即Key列
        self.basic_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_1.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.basic_trainingrightAction1Child_1 = QTreeWidgetItem(
            self.basic_trainingrightActionRoot_1)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction1Child_1.setText(0, '拇指对食指')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction1Child_1.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_2.setText(0, '拇指对小指指根')
        self.basic_trainingrightAction1Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_3.setText(0, '拇指环转')
        self.basic_trainingrightAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_4 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_4.setText(0, '拇指屈伸')
        self.basic_trainingrightAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_5 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_5.setText(0, '拇指外展')
        self.basic_trainingrightAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_6 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_6.setText(0, '拇指对四指')
        self.basic_trainingrightAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_7 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_7.setText(0, '拇指对掌')
        self.basic_trainingrightAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction1Child_8 = QTreeWidgetItem(self.basic_trainingrightActionRoot_1)
        self.basic_trainingrightAction1Child_8.setText(0, '拇指伸展')
        self.basic_trainingrightAction1Child_8.setCheckState(0, Qt.Unchecked)

        self.basic_trainingrightActionRoot_2 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingrightActionRoot_2.setText(0, '精细灵活性运动')  # 0代表第一列，即Key列
        self.basic_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_2.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingrightAction2Child_1 = QTreeWidgetItem(
            self.basic_trainingrightActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction2Child_1.setText(0, '比OK')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction2Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingrightAction2Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_2)
        self.basic_trainingrightAction2Child_2.setText(0, '比数字')
        self.basic_trainingrightAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction2Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_2)
        self.basic_trainingrightAction2Child_3.setText(0, '侧捏')
        self.basic_trainingrightAction2Child_3.setCheckState(0, Qt.Unchecked)

        # 根节点
        self.basic_trainingrightActionRoot_3 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingrightActionRoot_3.setText(0, '抓握运动')  # 0代表第一列，即Key列
        self.basic_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_3.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingrightAction3Child_1 = QTreeWidgetItem(
            self.basic_trainingrightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction3Child_1.setText(0, '钩状抓握')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction3Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingrightAction3Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_3)
        self.basic_trainingrightAction3Child_2.setText(0, '球状抓握')
        self.basic_trainingrightAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction3Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_3)
        self.basic_trainingrightAction3Child_3.setText(0, '握拳')
        self.basic_trainingrightAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction3Child_4 = QTreeWidgetItem(self.basic_trainingrightActionRoot_3)
        self.basic_trainingrightAction3Child_4.setText(0, '直拳')
        self.basic_trainingrightAction3Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction3Child_5 = QTreeWidgetItem(self.basic_trainingrightActionRoot_3)
        self.basic_trainingrightAction3Child_5.setText(0, '柱状抓握')
        self.basic_trainingrightAction3Child_5.setCheckState(0, Qt.Unchecked)

        self.basic_trainingrightActionRoot_4 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingrightActionRoot_4.setText(0, '手指动作')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_4.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingrightAction4Child_1 = QTreeWidgetItem(
            self.basic_trainingrightActionRoot_4)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction4Child_1.setText(0, '手指内收外展')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction4Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingrightAction4Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_4)
        self.basic_trainingrightAction4Child_2.setText(0, '四指单独屈伸')
        self.basic_trainingrightAction4Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction4Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_4)
        self.basic_trainingrightAction4Child_3.setText(0, '四指屈曲')
        self.basic_trainingrightAction4Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction4Child_4 = QTreeWidgetItem(self.basic_trainingrightActionRoot_4)
        self.basic_trainingrightAction4Child_4.setText(0, '四指伸展')
        self.basic_trainingrightAction4Child_4.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction4Child_5 = QTreeWidgetItem(self.basic_trainingrightActionRoot_4)
        self.basic_trainingrightAction4Child_5.setText(0, '掌指关节屈曲')
        self.basic_trainingrightAction4Child_5.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction4Child_6 = QTreeWidgetItem(self.basic_trainingrightActionRoot_4)
        self.basic_trainingrightAction4Child_6.setText(0, '指尖关节伸展')
        self.basic_trainingrightAction4Child_6.setCheckState(0, Qt.Unchecked)

        self.basic_trainingrightActionRoot_5 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingrightActionRoot_5.setText(0, '腕部运动')  # 0代表第一列，即Key列
        self.basic_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_5.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingrightAction5Child_1 = QTreeWidgetItem(
            self.basic_trainingLeftActionRoot_5)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction5Child_1.setText(0, '尺偏')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction5Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingrightAction5Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_5)
        self.basic_trainingrightAction5Child_2.setText(0, '桡偏')
        self.basic_trainingrightAction5Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction5Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_5)
        self.basic_trainingrightAction5Child_3.setText(0, '前臂中立位腕背伸')
        self.basic_trainingrightAction5Child_3.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction5Child_4 = QTreeWidgetItem(self.basic_trainingrightActionRoot_5)
        self.basic_trainingrightAction5Child_4.setText(0, '前臂旋前位腕背伸')
        self.basic_trainingrightAction5Child_4.setCheckState(0, Qt.Unchecked)

        self.basic_trainingrightActionRoot_6 = QTreeWidgetItem(self.basic_rightTree)  # 基本动作训练-训练动作2根节点
        self.basic_trainingrightActionRoot_6.setText(0, '前臂旋转')  # 0代表第一列，即Key列
        self.basic_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.basic_trainingrightActionRoot_6.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.basic_trainingrightAction6Child_1 = QTreeWidgetItem(
            self.basic_trainingrightActionRoot_6)  # 基本动作训练-训练动作1的孩子节点1
        self.basic_trainingrightAction6Child_1.setText(0, '前臂旋前')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.basic_trainingrightAction6Child_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点2
        self.basic_trainingrightAction6Child_2 = QTreeWidgetItem(self.basic_trainingrightActionRoot_6)
        self.basic_trainingrightAction6Child_2.setText(0, '前臂旋后')
        self.basic_trainingrightAction6Child_2.setCheckState(0, Qt.Unchecked)
        self.basic_trainingrightAction6Child_3 = QTreeWidgetItem(self.basic_trainingrightActionRoot_6)
        self.basic_trainingrightAction6Child_3.setText(0, '前臂旋前旋后')
        self.basic_trainingrightAction6Child_3.setCheckState(0, Qt.Unchecked)

        self.function_selectTrainingFrame = QtWidgets.QFrame(Form)  # 功能动作训练容器
        self.function_selectTrainingFrame.setGeometry(QtCore.QRect(650, 260, 600, 600))
        self.function_selectTrainingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.function_selectTrainingFrame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.function_scrollArea = QtWidgets.QScrollArea(self.function_selectTrainingFrame)  # 功能动作训练滑动窗口
        self.function_scrollArea.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.function_scrollArea.setWidgetResizable(True)

        self.function_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.function_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.function_scrollAreaWidgetContents.setMinimumHeight(3000)
        self.function_scrollArea.setWidget(self.function_scrollAreaWidgetContents)

        self.function_leftTree = QtWidgets.QTreeWidget(self.function_scrollAreaWidgetContents)
        self.function_leftTree.setGeometry(QtCore.QRect(0, 0, 700, 10000))
        self.function_leftTree.setStyleSheet('font:14pt')
        # 为树控件指定列数
        self.function_leftTree.setColumnCount(1)
        # 指定列标签
        self.function_leftTree.setHeaderLabels(['功能训练动作_左'])
        # 根节点
        self.function_trainingLeftActionRoot_1 = QTreeWidgetItem(self.function_leftTree)  # 功能动作训练-训练动作1根节点
        self.function_trainingLeftActionRoot_1.setText(0, '精细动作')  # 0代表第一列，即Key列
        self.function_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingLeftActionRoot_1.setCheckState(0, Qt.Unchecked)
        # 添加子节点1
        self.function_trainingLeftAction1Child_1 = QTreeWidgetItem(
            self.function_trainingLeftActionRoot_1)  # 功能动作训练-训练动作1的孩子节点1
        self.function_trainingLeftAction1Child_1.setText(0, '侧捏夹子')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingLeftAction1Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作1的孩子节点2
        self.function_trainingLeftAction1Child_2 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_2.setText(0, '对指翻书页')
        self.function_trainingLeftAction1Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_3 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_3.setText(0, '对指捏夹子')
        self.function_trainingLeftAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_4 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_4.setText(0, '拿玻璃球')
        self.function_trainingLeftAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_5 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_5.setText(0, '拿回形针')
        self.function_trainingLeftAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_6 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_6.setText(0, '拿木块两指捏')
        self.function_trainingLeftAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_7 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_7.setText(0, '拿木块三指捏')
        self.function_trainingLeftAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_8 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_8.setText(0, '拿小木块两指捏')
        self.function_trainingLeftAction1Child_8.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_9 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_9.setText(0, '拿小木块三指捏')
        self.function_trainingLeftAction1Child_9.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction1Child_10 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingLeftAction1Child_10.setText(0, '拿钥匙')
        self.function_trainingLeftAction1Child_10.setCheckState(0, Qt.Unchecked)

        # 根节点
        self.function_trainingLeftActionRoot_2 = QTreeWidgetItem(self.function_leftTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingLeftActionRoot_2.setText(0, '复合旋转运动')  # 0代表第一列，即Key列
        self.function_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingLeftActionRoot_2.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingLeftAction2Child_1 = QTreeWidgetItem(
            self.function_trainingLeftActionRoot_2)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingLeftAction2Child_1.setText(0, '翻卡片')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingLeftAction2Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingLeftAction2Child_2 = QTreeWidgetItem(self.function_trainingLeftActionRoot_2)
        self.function_trainingLeftAction2Child_2.setText(0, '翻木板')
        self.function_trainingLeftAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction2Child_3 = QTreeWidgetItem(self.function_trainingLeftActionRoot_2)
        self.function_trainingLeftAction2Child_3.setText(0, '翻日历')
        self.function_trainingLeftAction2Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction2Child_4 = QTreeWidgetItem(self.function_trainingLeftActionRoot_2)
        self.function_trainingLeftAction2Child_4.setText(0, '翻书页')
        self.function_trainingLeftAction2Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction2Child_5 = QTreeWidgetItem(self.function_trainingLeftActionRoot_2)
        self.function_trainingLeftAction2Child_5.setText(0, '前臂旋前套杯子')
        self.function_trainingLeftAction2Child_5.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction2Child_6 = QTreeWidgetItem(self.function_trainingLeftActionRoot_2)
        self.function_trainingLeftAction2Child_6.setText(0, '套杯子')
        self.function_trainingLeftAction2Child_6.setCheckState(0, Qt.Unchecked)

        self.function_trainingLeftActionRoot_3 = QTreeWidgetItem(self.function_leftTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingLeftActionRoot_3.setText(0, '抓握运动')  # 0代表第一列，即Key列
        self.function_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingLeftActionRoot_3.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingLeftAction3Child_1 = QTreeWidgetItem(
            self.function_trainingLeftActionRoot_3)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingLeftAction3Child_1.setText(0, '木棒抓握')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingLeftAction3Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingLeftAction3Child_2 = QTreeWidgetItem(self.function_trainingLeftActionRoot_3)
        self.function_trainingLeftAction3Child_2.setText(0, '拿玻璃杯')
        self.function_trainingLeftAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction3Child_3 = QTreeWidgetItem(self.function_trainingLeftActionRoot_3)
        self.function_trainingLeftAction3Child_3.setText(0, '拿矿泉水瓶')
        self.function_trainingLeftAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction3Child_4 = QTreeWidgetItem(self.function_trainingLeftActionRoot_3)
        self.function_trainingLeftAction3Child_4.setText(0, '捏弹力球')
        self.function_trainingLeftAction3Child_4.setCheckState(0, Qt.Unchecked)

        self.function_trainingLeftActionRoot_4 = QTreeWidgetItem(self.function_leftTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingLeftActionRoot_4.setText(0, 'ADL活动')  # 0代表第一列，即Key列
        self.function_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingLeftActionRoot_4.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingLeftAction4Child_1 = QTreeWidgetItem(
            self.function_trainingLeftActionRoot_4)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingLeftAction4Child_1.setText(0, '写字')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingLeftAction4Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingLeftAction4Child_2 = QTreeWidgetItem(self.function_trainingLeftActionRoot_4)
        self.function_trainingLeftAction4Child_2.setText(0, '旋转铅笔')
        self.function_trainingLeftAction4Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction4Child_3 = QTreeWidgetItem(self.function_trainingLeftActionRoot_4)
        self.function_trainingLeftAction4Child_3.setText(0, '旋转钥匙')
        self.function_trainingLeftAction4Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction4Child_4 = QTreeWidgetItem(self.function_trainingLeftActionRoot_4)
        self.function_trainingLeftAction4Child_4.setText(0, '用勺子舀珠子')
        self.function_trainingLeftAction4Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingLeftAction4Child_5 = QTreeWidgetItem(self.function_trainingLeftActionRoot_4)
        self.function_trainingLeftAction4Child_5.setText(0, '抓放网球')
        self.function_trainingLeftAction4Child_5.setCheckState(0, Qt.Unchecked)

        self.function_trainingLeftActionRoot_5 = QTreeWidgetItem(self.function_leftTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingLeftActionRoot_5.setText(0, '双手联合运动')  # 0代表第一列，即Key列
        self.function_leftTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingLeftActionRoot_5.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingLeftAction5Child_1 = QTreeWidgetItem(
            self.function_trainingLeftActionRoot_5)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingLeftAction5Child_1.setText(0, '双手滚训练棒')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingLeftAction5Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingLeftAction5Child_2 = QTreeWidgetItem(self.function_trainingLeftActionRoot_5)
        self.function_trainingLeftAction5Child_2.setText(0, '双手用力弯曲训练棒')
        self.function_trainingLeftAction5Child_2.setCheckState(0, Qt.Unchecked)

        self.function_rightTree = QtWidgets.QTreeWidget(self.function_scrollAreaWidgetContents)
        self.function_rightTree.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.function_rightTree.setStyleSheet('font:14pt')
        # 为树控件指定列数
        self.function_rightTree.setColumnCount(1)
        # 指定列标签
        self.function_rightTree.setHeaderLabels(['功能训练动作_右'])
        self.function_rightTree.setVisible(False)
        # 根节点
        self.function_trainingRightActionRoot_1 = QTreeWidgetItem(self.function_rightTree)  # 功能动作训练-训练动作1根节点
        self.function_trainingRightActionRoot_1.setText(0, '精细动作')  # 0代表第一列，即Key列
        self.function_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingRightActionRoot_1.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingRightAction1Child_1 = QTreeWidgetItem(
            self.function_trainingRightActionRoot_1)  # 功能动作训练-训练动作1的孩子节点1
        self.function_trainingRightAction1Child_1.setText(0, '侧捏夹子')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingRightAction1Child_1.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_2 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_2.setText(0, '对指翻书页')
        self.function_trainingRightAction1Child_2.setCheckState(0, Qt.Unchecked)

        self.function_trainingRightAction1Child_3 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_3.setText(0, '对指捏夹子')
        self.function_trainingRightAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_4 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_4.setText(0, '拿玻璃球')
        self.function_trainingRightAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_5 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingRightAction1Child_5.setText(0, '拿回形针')
        self.function_trainingRightAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_6 = QTreeWidgetItem(self.function_trainingLeftActionRoot_1)
        self.function_trainingRightAction1Child_6.setText(0, '拿木块两指捏')
        self.function_trainingRightAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_7 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_7.setText(0, '拿木块三指捏')
        self.function_trainingRightAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_8 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_8.setText(0, '拿小木块两指捏')
        self.function_trainingRightAction1Child_8.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_9 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_9.setText(0, '拿小木块三指捏')
        self.function_trainingRightAction1Child_9.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction1Child_10 = QTreeWidgetItem(self.function_trainingRightActionRoot_1)
        self.function_trainingRightAction1Child_10.setText(0, '拿钥匙')
        self.function_trainingRightAction1Child_10.setCheckState(0, Qt.Unchecked)

        # 根节点
        self.function_trainingRightActionRoot_2 = QTreeWidgetItem(self.function_rightTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingRightActionRoot_2.setText(0, '复合旋转运动')  # 0代表第一列，即Key列
        self.function_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingRightActionRoot_2.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingRightAction2Child_1 = QTreeWidgetItem(
            self.function_trainingRightActionRoot_2)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingRightAction2Child_1.setText(0, '翻卡片')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingRightAction2Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingRightAction2Child_2 = QTreeWidgetItem(self.function_trainingRightActionRoot_2)
        self.function_trainingRightAction2Child_2.setText(0, '翻木板')
        self.function_trainingRightAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction2Child_3 = QTreeWidgetItem(self.function_trainingRightActionRoot_2)
        self.function_trainingRightAction2Child_3.setText(0, '翻日历')
        self.function_trainingRightAction2Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction2Child_4 = QTreeWidgetItem(self.function_trainingRightActionRoot_2)
        self.function_trainingRightAction2Child_4.setText(0, '翻书页')
        self.function_trainingRightAction2Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction2Child_5 = QTreeWidgetItem(self.function_trainingRightActionRoot_2)
        self.function_trainingRightAction2Child_5.setText(0, '前臂旋前套杯子')
        self.function_trainingRightAction2Child_5.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction2Child_6 = QTreeWidgetItem(self.function_trainingRightActionRoot_2)
        self.function_trainingRightAction2Child_6.setText(0, '套杯子')
        self.function_trainingRightAction2Child_6.setCheckState(0, Qt.Unchecked)

        self.function_trainingRightActionRoot_3 = QTreeWidgetItem(self.function_rightTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingRightActionRoot_3.setText(0, '抓握运动')  # 0代表第一列，即Key列
        self.function_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingRightActionRoot_3.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingRightAction3Child_1 = QTreeWidgetItem(
            self.function_trainingRightActionRoot_3)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingRightAction3Child_1.setText(0, '木棒抓握')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingRightAction3Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingRightAction3Child_2 = QTreeWidgetItem(self.function_trainingRightActionRoot_3)
        self.function_trainingRightAction3Child_2.setText(0, '拿玻璃杯')
        self.function_trainingRightAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction3Child_3 = QTreeWidgetItem(self.function_trainingRightActionRoot_3)
        self.function_trainingRightAction3Child_3.setText(0, '拿矿泉水瓶')
        self.function_trainingRightAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction3Child_4 = QTreeWidgetItem(self.function_trainingRightActionRoot_3)
        self.function_trainingRightAction3Child_4.setText(0, '捏弹力球')
        self.function_trainingRightAction3Child_4.setCheckState(0, Qt.Unchecked)

        self.function_trainingRightActionRoot_4 = QTreeWidgetItem(self.function_rightTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingRightActionRoot_4.setText(0, 'ADL活动')  # 0代表第一列，即Key列
        self.function_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingRightActionRoot_4.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingRightAction4Child_1 = QTreeWidgetItem(
            self.function_trainingRightActionRoot_4)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingRightAction4Child_1.setText(0, '写字')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingRightAction4Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingRightAction4Child_2 = QTreeWidgetItem(self.function_trainingRightActionRoot_4)
        self.function_trainingRightAction4Child_2.setText(0, '旋转铅笔')
        self.function_trainingRightAction4Child_2.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction4Child_3 = QTreeWidgetItem(self.function_trainingRightActionRoot_4)
        self.function_trainingRightAction4Child_3.setText(0, '旋转钥匙')
        self.function_trainingRightAction4Child_3.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction4Child_4 = QTreeWidgetItem(self.function_trainingRightActionRoot_4)
        self.function_trainingRightAction4Child_4.setText(0, '用勺子舀珠子')
        self.function_trainingRightAction4Child_4.setCheckState(0, Qt.Unchecked)
        self.function_trainingRightAction4Child_5 = QTreeWidgetItem(self.function_trainingRightActionRoot_4)
        self.function_trainingRightAction4Child_5.setText(0, '抓放网球')
        self.function_trainingRightAction4Child_5.setCheckState(0, Qt.Unchecked)

        self.function_trainingRightActionRoot_5 = QTreeWidgetItem(self.function_rightTree)  # 功能动作训练-训练动作2根节点
        self.function_trainingRightActionRoot_5.setText(0, '双手联合运动')  # 0代表第一列，即Key列
        self.function_rightTree.setColumnWidth(0, 200)  # 第一列列宽设为200
        # 开启复选框状态
        self.function_trainingRightActionRoot_5.setCheckState(0, Qt.Unchecked)

        # 添加子节点1
        self.function_trainingRightAction5Child_1 = QTreeWidgetItem(
            self.function_trainingRightActionRoot_5)  # 功能动作训练-训练动作2的孩子节点1
        self.function_trainingRightAction5Child_1.setText(0, '双手滚训练棒')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.function_trainingRightAction5Child_1.setCheckState(0, Qt.Unchecked)
        # 功能动作训练-训练动作2的孩子节点2
        self.function_trainingRightAction5Child_2 = QTreeWidgetItem(self.function_trainingRightActionRoot_5)
        self.function_trainingRightAction5Child_2.setText(0, '双手用力弯曲训练棒')
        self.function_trainingRightAction5Child_2.setCheckState(0, Qt.Unchecked)

        self.sensorimotor_selectTrainingFrame = QtWidgets.QFrame(Form)  # 感觉运动训练容器
        self.sensorimotor_selectTrainingFrame.setGeometry(QtCore.QRect(1300, 260, 600, 600))
        self.sensorimotor_selectTrainingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorimotor_selectTrainingFrame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.sensorimotor_scrollArea = QtWidgets.QScrollArea(self.sensorimotor_selectTrainingFrame)  # 感觉运动训练滑动窗口
        self.sensorimotor_scrollArea.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.sensorimotor_scrollArea.setWidgetResizable(True)

        self.sensorimotor_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.sensorimotor_scrollAreaWidgetContents.setMinimumHeight(3000)
        self.sensorimotor_scrollArea.setWidget(self.sensorimotor_scrollAreaWidgetContents)

        # 感觉运动训练-训练动作左根节点
        self.sensorimotor_leftTree = QtWidgets.QTreeWidget(self.sensorimotor_scrollAreaWidgetContents)
        self.sensorimotor_leftTree.setGeometry(QtCore.QRect(0, 0, 700, 10000))
        self.sensorimotor_leftTree.setStyleSheet('font:14pt')
        # 为树控件指定列数
        self.sensorimotor_leftTree.setColumnCount(1)

        # 指定列标签
        self.sensorimotor_leftTree.setHeaderLabels(['感觉运动观察训练_左'])

        # 感觉运动训练-训练动作左1根节点
        self.sensorimotor_trainingLeftActionRoot_1 = QTreeWidgetItem(self.sensorimotor_leftTree)
        self.sensorimotor_trainingLeftActionRoot_1.setText(0, '浅感觉')  # 0代表第一列，即Key列
        self.sensorimotor_leftTree.setColumnWidth(0, 350)

        # 开启复选框状态
        self.sensorimotor_trainingLeftActionRoot_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作1的孩子节点1
        self.sensorimotor_trainingLeftAction1Child_1 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_1.setText(0, '触摸布')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingLeftAction1Child_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作1的孩子节点2
        self.sensorimotor_trainingLeftAction1Child_2 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_2.setText(0, '触摸指压板')
        self.sensorimotor_trainingLeftAction1Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_3 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_3.setText(0, '触摸竹简')
        self.sensorimotor_trainingLeftAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_4 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_4.setText(0, '触摸桌垫')
        self.sensorimotor_trainingLeftAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_5 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_5.setText(0, '单丝触觉—食指远端指腹')
        self.sensorimotor_trainingLeftAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_6 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_6.setText(0, '单丝触觉—手背虎口')
        self.sensorimotor_trainingLeftAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_7 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_7.setText(0, '单丝触觉—远端指背')
        self.sensorimotor_trainingLeftAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_8 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_8.setText(0, '棉签轻触觉—食指背侧')
        self.sensorimotor_trainingLeftAction1Child_8.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_9 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_9.setText(0, '棉签轻触觉—食指指腹')
        self.sensorimotor_trainingLeftAction1Child_9.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_10 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_10.setText(0, '刷擦1—手背')
        self.sensorimotor_trainingLeftAction1Child_10.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_11 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_11.setText(0, '刷擦1—手掌')
        self.sensorimotor_trainingLeftAction1Child_11.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_12 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_12.setText(0, '纸板触觉—手背')
        self.sensorimotor_trainingLeftAction1Child_12.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction1Child_13 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_1)
        self.sensorimotor_trainingLeftAction1Child_13.setText(0, '纸板触觉—手掌')
        self.sensorimotor_trainingLeftAction1Child_13.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2根节点
        self.sensorimotor_trainingLeftActionRoot_2 = QTreeWidgetItem(self.sensorimotor_leftTree)
        self.sensorimotor_trainingLeftActionRoot_2.setText(0, '深感觉')  # 0代表第一列，即Key列
        self.sensorimotor_leftTree.setColumnWidth(0, 350)  # 第一列列宽设为200
        # 开启复选框状态
        self.sensorimotor_trainingLeftActionRoot_2.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2的孩子节点1
        self.sensorimotor_trainingLeftAction2Child_1 = QTreeWidgetItem(
            self.sensorimotor_trainingLeftActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingLeftAction2Child_1.setText(0, '运动觉')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingLeftAction2Child_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2的孩子节点2
        self.sensorimotor_trainingLeftAction2Child_2 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_2)
        self.sensorimotor_trainingLeftAction2Child_2.setText(0, '震动觉1')
        self.sensorimotor_trainingLeftAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction2Child_3 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_2)
        self.sensorimotor_trainingLeftAction2Child_3.setText(0, '震动觉2')
        self.sensorimotor_trainingLeftAction2Child_3.setCheckState(0, Qt.Unchecked)

        self.sensorimotor_trainingLeftActionRoot_3 = QTreeWidgetItem(self.sensorimotor_leftTree)
        self.sensorimotor_trainingLeftActionRoot_3.setText(0, '复合感觉')  # 0代表第一列，即Key列
        self.sensorimotor_leftTree.setColumnWidth(0, 350)  # 第一列列宽设为200
        # 开启复选框状态
        self.sensorimotor_trainingLeftActionRoot_3.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作3的孩子节点1
        self.sensorimotor_trainingLeftAction3Child_1 = QTreeWidgetItem(
            self.sensorimotor_trainingLeftActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingLeftAction3Child_1.setText(0, '皮肤定位觉')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingLeftAction3Child_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2的孩子节点2
        self.sensorimotor_trainingLeftAction3Child_2 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_2.setText(0, '抓木块1')
        self.sensorimotor_trainingLeftAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_3 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_3.setText(0, '抓木块2')
        self.sensorimotor_trainingLeftAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_4 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_4.setText(0, '抓木块3')
        self.sensorimotor_trainingLeftAction3Child_4.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_5 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_5.setText(0, '抓木块4')
        self.sensorimotor_trainingLeftAction3Child_5.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_6 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_6.setText(0, '抓球1')
        self.sensorimotor_trainingLeftAction3Child_6.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_7 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_7.setText(0, '抓球2')
        self.sensorimotor_trainingLeftAction3Child_7.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_8 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_8.setText(0, '抓球3')
        self.sensorimotor_trainingLeftAction3Child_8.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_9 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_9.setText(0, '抓球4')
        self.sensorimotor_trainingLeftAction3Child_9.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_10 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_10.setText(0, '抓圆柱1')
        self.sensorimotor_trainingLeftAction3Child_10.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_11 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_11.setText(0, '抓圆柱2')
        self.sensorimotor_trainingLeftAction3Child_11.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_12 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_12.setText(0, '抓圆柱3')
        self.sensorimotor_trainingLeftAction3Child_12.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_13 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_13.setText(0, '抓圆柱4')
        self.sensorimotor_trainingLeftAction3Child_13.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingLeftAction3Child_15 = QTreeWidgetItem(self.sensorimotor_trainingLeftActionRoot_3)
        self.sensorimotor_trainingLeftAction3Child_15.setText(0, '抓圆柱5')
        self.sensorimotor_trainingLeftAction3Child_15.setCheckState(0, Qt.Unchecked)

        self.sensorimotor_rightTree = QtWidgets.QTreeWidget(self.sensorimotor_scrollAreaWidgetContents)
        self.sensorimotor_rightTree.setGeometry(QtCore.QRect(0, 0, 700, 10000))
        self.sensorimotor_rightTree.setStyleSheet('font:14pt')
        # 为树控件指定列数
        self.sensorimotor_rightTree.setColumnCount(1)
        # 指定列标签
        self.sensorimotor_rightTree.setHeaderLabels(['感觉运动观察训练_右'])
        self.sensorimotor_rightTree.setVisible(False)

        # 感觉运动训练-训练动作1根节点
        self.sensorimotor_trainingRightActionRoot_1 = QTreeWidgetItem(self.sensorimotor_rightTree)
        self.sensorimotor_trainingRightActionRoot_1.setText(0, '浅感觉')  # 0代表第一列，即Key列
        self.sensorimotor_rightTree.setColumnWidth(0, 350)  # 第一列列宽设为200
        # 开启复选框状态
        self.sensorimotor_trainingRightActionRoot_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRighAction1Child_1 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRighAction1Child_1.setText(0, '触摸布')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingRighAction1Child_1.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作1的孩子节点2
        self.sensorimotor_trainingRightAction1Child_2 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_2.setText(0, '触摸指压板')
        self.sensorimotor_trainingRightAction1Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_3 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_3.setText(0, '触摸竹简')
        self.sensorimotor_trainingRightAction1Child_3.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_4 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_4.setText(0, '触摸桌垫')
        self.sensorimotor_trainingRightAction1Child_4.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_5 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_5.setText(0, '单丝触觉—食指远端指腹')
        self.sensorimotor_trainingRightAction1Child_5.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_6 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_6.setText(0, '单丝触觉—手背虎口')
        self.sensorimotor_trainingRightAction1Child_6.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_7 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_7.setText(0, '单丝触觉—远端指背')
        self.sensorimotor_trainingRightAction1Child_7.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_8 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_8.setText(0, '棉签轻触觉—食指背侧')
        self.sensorimotor_trainingRightAction1Child_8.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_9 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_9.setText(0, '棉签轻触觉—食指指腹')
        self.sensorimotor_trainingRightAction1Child_9.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_10 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_10.setText(0, '刷擦1—手背')
        self.sensorimotor_trainingRightAction1Child_10.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_11 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_11.setText(0, '刷擦1—手掌')
        self.sensorimotor_trainingRightAction1Child_11.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_12 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_12.setText(0, '纸板触觉—手背')
        self.sensorimotor_trainingRightAction1Child_12.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction1Child_13 = QTreeWidgetItem(self.sensorimotor_trainingRightActionRoot_1)
        self.sensorimotor_trainingRightAction1Child_13.setText(0, '纸板触觉—手掌')
        self.sensorimotor_trainingRightAction1Child_13.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2根节点
        self.sensorimotor_trainingRightActionRoot_2 = QTreeWidgetItem(self.sensorimotor_rightTree)
        self.sensorimotor_trainingRightActionRoot_2.setText(0, '深感觉')  # 0代表第一列，即Key列
        self.sensorimotor_rightTree.setColumnWidth(0, 350)  # 第一列列宽设为200
        # 开启复选框状态
        self.sensorimotor_trainingRightActionRoot_2.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作2的孩子节点1
        self.sensorimotor_trainingRightAction2Child_1 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction2Child_1.setText(0, '运动觉')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingRightAction2Child_1.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction2Child_2 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction2Child_2.setText(0, '震动觉1')  # 第一列Key为 子节点1
        self.sensorimotor_trainingRightAction2Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction2Child_3 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_2)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction2Child_3.setText(0, '震动觉2')  # 第一列Key为 子节点1
        self.sensorimotor_trainingRightAction2Child_3.setCheckState(0, Qt.Unchecked)

        self.sensorimotor_trainingRightActionRoot_3 = QTreeWidgetItem(self.sensorimotor_rightTree)
        self.sensorimotor_trainingRightActionRoot_3.setText(0, '复合感觉')  # 0代表第一列，即Key列
        self.sensorimotor_rightTree.setColumnWidth(0, 350)  # 第一列列宽设为200
        # 开启复选框状态
        self.sensorimotor_trainingRightActionRoot_3.setCheckState(0, Qt.Unchecked)

        # 感觉运动训练-训练动作3的孩子节点1
        self.sensorimotor_trainingRightAction3Child_1 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_1.setText(0, '皮肤定位觉')  # 第一列Key为 子节点1
        # 设置子节点1开启复选框状态
        self.sensorimotor_trainingRightAction3Child_1.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_2 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_2.setText(0, '抓木块1')
        self.sensorimotor_trainingRightAction3Child_2.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_3 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_3.setText(0, '抓木块2')
        self.sensorimotor_trainingRightAction3Child_3.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_4 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_4.setText(0, '抓木块3')
        self.sensorimotor_trainingRightAction3Child_4.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_5 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_5.setText(0, '抓木块4')
        self.sensorimotor_trainingRightAction3Child_5.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_6 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_6.setText(0, '抓球1')
        self.sensorimotor_trainingRightAction3Child_6.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_7 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_7.setText(0, '抓球2')
        self.sensorimotor_trainingRightAction3Child_7.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_8 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_8.setText(0, '抓球3')
        self.sensorimotor_trainingRightAction3Child_8.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_9 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_9.setText(0, '抓球4')
        self.sensorimotor_trainingRightAction3Child_9.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_10 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_10.setText(0, '抓圆柱1')
        self.sensorimotor_trainingRightAction3Child_10.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_11 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_11.setText(0, '抓圆柱2')
        self.sensorimotor_trainingRightAction3Child_11.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_12 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_12.setText(0, '抓圆柱3')
        self.sensorimotor_trainingRightAction3Child_12.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_13 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_13.setText(0, '抓圆柱4')
        self.sensorimotor_trainingRightAction3Child_13.setCheckState(0, Qt.Unchecked)
        self.sensorimotor_trainingRightAction3Child_14 = QTreeWidgetItem(
            self.sensorimotor_trainingRightActionRoot_3)  # 基本动作训练-训练动作1的孩子节点1
        self.sensorimotor_trainingRightAction3Child_14.setText(0, '抓圆柱5')
        self.sensorimotor_trainingRightAction3Child_14.setCheckState(0, Qt.Unchecked)

        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(1180, 50, 150, 50))
        self.saveButton.setStyleSheet("font:14pt;color:white;background: rgb(0,138,200)")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加训练方案"))
        self.label.setText(_translate("Form", "训练时间"))
        self.label_2.setText(_translate("Form", "空间训练参数设置"))
        self.label_3.setText(_translate("Form", "图片总数（张）"))
        self.label_4.setText(_translate("Form", "播放速率（秒）"))
        self.label_5.setText(_translate("Form", "辨别难度"))
        self.label_6.setText(_translate("Form", "训练手部:"))

        self.saveButton.setText(_translate("Form", "保存"))


class addPlan(QtWidgets.QMainWindow, Ui_Form):  # 基本功能动作训练
    def __init__(self,patient_id):
        super(addPlan, self).__init__()

        self.patient_id = patient_id

        self.patientInfo = json.loads(requests.post(config.patientGetById,data={"id":self.patient_id}).content.decode("utf-8"))["data"]

        self.setupUi(self)
        self.saveButton.mousePressEvent = self.saveButtonClick
        self.handComboBox.currentIndexChanged.connect(self.handComboBoxClick)

    def saveButtonClick(self, *args):  # 保存训练方案
        ...

    def handComboBoxClick(self, *args):  # 保存训练方案
        if (self.handComboBox.currentIndex() == 1):
            self.basic_rightTree.setVisible(True)
            self.function_rightTree.setVisible(True)
            self.sensorimotor_rightTree.setVisible(True)
            self.basic_leftTree.setVisible(False)
            self.function_leftTree.setVisible(False)
            self.sensorimotor_leftTree.setVisible(False)

        else:
            self.basic_leftTree.setVisible(True)
            self.function_leftTree.setVisible(True)
            self.sensorimotor_leftTree.setVisible(True)
            self.basic_rightTree.setVisible(False)
            self.function_rightTree.setVisible(False)
            self.sensorimotor_rightTree.setVisible(False)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = addPlan("1")
    gui.show()
    sys.exit(app.exec_())
