# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from PyQt5.QtWidgets import QAbstractItemView, QHeaderView, QTableWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.resize(1920, 1080)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0,1920, 1080))
        self.frame.setStyleSheet("background:rgb(242,249,255)")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20,120, 40))
        self.label.setStyleSheet("font:14pt")


        self.schemeNamelineEdit = QtWidgets.QLineEdit(self.frame)
        self.schemeNamelineEdit.setGeometry(QtCore.QRect(150, 20, 1500, 40))
        self.schemeNamelineEdit.setStyleSheet("font:14pt;background:white")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 12))
        self.label_2.setStyleSheet("color:red;font:12pt;")

        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 150, 40))
        self.label_3.setStyleSheet("font:14pt")

        self.startDateEdit = QtWidgets.QDateEdit(QDate.currentDate(),self.frame)
        self.startDateEdit.setGeometry(QtCore.QRect(160, 90, 250, 40))
        self.startDateEdit.setStyleSheet("font:14pt;background:white")
        self.startDateEdit.setCalendarPopup(True)

        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(420, 90, 154, 40))
        self.label_4.setStyleSheet("font:14pt")

        self.endDateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.frame)
        self.endDateEdit.setGeometry(QtCore.QRect(460, 90, 250, 40))
        self.endDateEdit.setStyleSheet("font:14pt;background:white")
        self.endDateEdit.setCalendarPopup(True)

        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 150, 40))
        self.label_5.setStyleSheet("font:14pt")

        self.remarklineEdit = QtWidgets.QLineEdit(self.frame)
        self.remarklineEdit.setGeometry(QtCore.QRect(100, 140,  1500, 40))
        self.remarklineEdit.setStyleSheet("font:14pt;background:white")

        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(110, 200,200,45))
        self.addButton.setStyleSheet("font:14pt;color:white;background: rgb(0,138,200)")

        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setGeometry(QtCore.QRect(330,200,200,45))
        self.deleteButton.setStyleSheet("font:14pt;color:white;background: rgb(0,138,200)")

        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setGeometry(QtCore.QRect(550, 200,200,45))
        self.startButton.setStyleSheet("font:14pt;color:white;background: rgb(0,138,200)")

        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260,1900, 800))
        self.tableWidget.setStyleSheet("font:14pt;background:white")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(16)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QHeaderView.SelectRows)
        self.tableWidget.setSelectionMode(QTableWidget.SingleSelection)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        self.tableWidget.setColumnWidth(0, 400)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.tableWidget.setColumnWidth(1, 400)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        self.tableWidget.setColumnWidth(2, 790)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        self.tableWidget.setColumnWidth(3, 300)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "方案名称"))
        self.label_2.setText(_translate("Form", "*"))
        self.label_3.setText(_translate("Form", "计划日期"))
        self.label_4.setText(_translate("Form", "—"))
        self.label_5.setText(_translate("Form", "备注"))
        self.addButton.setText(_translate("Form", "添加训练计划"))
        self.deleteButton.setText(_translate("Form", "删除训练计划"))
        self.startButton.setText(_translate("Form", "开始训练"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "计划时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "训练模式"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "训练内容"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "训练状态"))

class addTriangingplan(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super(addTriangingplan, self).__init__()
        self.setupUi(self)
        self.addButton.mousePressEvent=self.addButtonClick
        self.deleteButton.mousePressEvent = self.deleteButtonClick
        self.startButton.mousePressEvent = self.startButtonClick

    def addButtonClick(self, *args):  # 添加训练计划

        ...
    def deleteButtonClick(self, *args):  # 删除训练计划

        ...
    def startButtonClick(self, *args):  # 开始训练，跳到相应界面
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = addTriangingplan()
    gui.show()
    sys.exit(app.exec_())
