# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5uipy.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import requests
import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt, QDate
from PyQt5.QtWidgets import QFileDialog, QMessageBox

import config
import tool

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(500, 10, 400, 41))
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setStyleSheet('font:16pt')

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label.setStyleSheet('font:14pt')

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.name.setStyleSheet('font:14pt')

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_2.setStyleSheet('font:14pt')

        self.gender = QtWidgets.QLabel(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.gender.setStyleSheet('font:14pt')

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.age.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.hand = QtWidgets.QLabel(self.centralwidget)
        self.hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.hand.setStyleSheet('font:14pt')

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 120, 1460, 700))
        self.table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table.setStyleSheet('background:white;font:12pt')
        self.table.setColumnCount(5)
        self.table.setRowCount(20)
        self.table.verticalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)  # 列
        self.table.setColumnWidth(0, 120)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.setColumnWidth(1, 680)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.setColumnWidth(2, 208)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.setColumnWidth(3, 208)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.setColumnWidth(4, 208)

        item = QtWidgets.QTableWidgetItem('抓')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 0, item)
        self.table.setRowHeight(0, 80)
        self.table.setSpan(0, 0, 6, 1)
        item = QtWidgets.QTableWidgetItem('1．抓一边长10 cm的正方体木块（如果得分=3，则该部分总分=18，并直接做“握”部分）')
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem('2．抓一边长2.5 cm的正方体木块 （如果得分=0，则该部分总分=0，并直接做“握”部分）')
        self.table.setRowHeight(1, 80)
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem('3．抓一边长5 cm的正方体木块')
        self.table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem('4．抓一边长7.5 cm的正方体木块')
        self.table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem('5．抓一直径7.5 cm的球')
        self.table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem('6．抓一直径10 × 2.5 × 1 cm的石头 ')
        self.table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem('握')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 0, item)
        self.table.setSpan(6, 0, 4, 1)
        item = QtWidgets.QTableWidgetItem('1．把一玻璃杯的水倒入另一玻璃杯里（如果得分=3，则该部分总分=12，并直接做“捏”部分） ')
        self.table.setItem(6, 1, item)
        self.table.setRowHeight(6, 80)
        item = QtWidgets.QTableWidgetItem('2．2.25 cm的管子（如果得分=0，则该部分总分=0，并直接做“捏”部分） ')
        self.table.setItem(7, 1, item)
        self.table.setRowHeight(7, 80)
        item = QtWidgets.QTableWidgetItem('3．1 x 16 cm的管子 ')
        self.table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem('4．把直径3.5cm的螺帽放在螺钉上 ')
        self.table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem('捏')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(10, 0, item)
        self.table.setSpan(10, 0, 6, 1)
        item = QtWidgets.QTableWidgetItem('1．用无名指和拇指相对捏起直径6 mm的小球（如果得分=3，则该部分总分=18，并直接做“粗大运动”部分）')
        self.table.setItem(10, 1, item)
        self.table.setRowHeight(10, 80)
        item = QtWidgets.QTableWidgetItem('2．用食指和拇指捏起直径1.5 cm的弹子（如果得分=0，则该部分总分=0，并直接做“粗大运动”部分）')
        self.table.setRowHeight(11, 80)
        self.table.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem('3．用中指和拇指相对捏起直径6 mm的小球')
        self.table.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem('4．用食指和拇指相对捏起直径6 mm的小球')
        self.table.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem('5．用中指和拇指捏起直径1.5 cm的弹子')
        self.table.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem('6．用无名指和拇指捏起直径1.5 cm的弹子')
        self.table.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem('粗大运动')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(16, 0, item)
        self.table.setRowHeight(0, 80)
        self.table.setSpan(16, 0, 3, 1)
        item = QtWidgets.QTableWidgetItem('1．把手置于脑后（如果得分=3，则该部分总分=9; 如果得分=0，则该部分总分=0，并结束')
        self.table.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem('2．把手放在头')
        self.table.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem('3．手碰嘴')
        self.table.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem('总分:')
        self.table.setItem(19, 0, item)
        self.table.setSpan(19, 0, 1, 2)
        self.table.setColumnWidth(0, 80)
        self.table.setWordWrap(True)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 830, 1460, 100))
        self.label_5.setStyleSheet("font:12pt")
        self.label_5.setWordWrap(True)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 940, 260, 40))
        self.label_6.setStyleSheet("font:16pt")

        self.dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 940, 260, 40))
        self.dateEdit.setStyleSheet("font:16pt;background:white")
        self.dateEdit.setCalendarPopup(True)

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(450, 940, 120, 40))
        self.saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.downLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downLoadButton.setGeometry(QtCore.QRect(590, 940, 120, 40))
        self.downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ARAT上肢动作研究量表"))
        self.title.setText(_translate("MainWindow", "手臂动作调查测试表（ARAT）"))
        self.label.setText(_translate("MainWindow", "姓名:"))
        self.name.setText(_translate("MainWindow", "--"))
        self.label_2.setText(_translate("MainWindow", "性别:"))
        self.gender.setText(_translate("MainWindow", "--"))
        self.label_3.setText(_translate("MainWindow", "年龄:"))
        self.age.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "患手:"))
        self.hand.setText(_translate("MainWindow", "--"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ARAT"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", ""))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "评分1"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "评分2"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "评分3"))
        self.label_5.setText(_translate("MainWindow",
                                        "手臂动作调查测试（Action Research Arm "
                                        "Test，ARAT）分四部分（抓、握、捏和粗大运动），共19项。每项为4级评分（0=不能完成；1=只能完成一部分；2=能完成，但动作慢或笨拙；3"
                                        "=能正确地完成），总分为57分。简便、快速，可*性高（ICC=0.99）。缺点为：需较多工具和设备"))
        self.label_6.setText(_translate("MainWindow", "评定日期:"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.downLoadButton.setText(_translate("MainWindow", "导出"))


class ARAT(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, patient_id):
        super(ARAT, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']
        self.name= self.name.setText(self.patientInfo['name'])
        self.gender = self.gender.setText(self.patientInfo['gender'])
        self.age = self.age.setText(self.patientInfo['age'])
        self.hand=self.hand.setText(self.patientInfo['illness'])

        self.saveButton.clicked.connect(self.saveButtonClick)
        self.downLoadButton.clicked.connect(self.downLoadButtonClick)

    #
    def saveButtonClick(self, *args):
        test_date = self.dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def downLoadButtonClick(self, *args):
        self.saveButton.hide()
        self.downLoadButton.hide()
        img = self.grab()
        self.saveButton.show()
        self.downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.name.text()}_{self.dateEdit.text().replace('/', '-')}.png")
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = ARAT()
    gui.show()
    sys.exit(app.exec_())
