# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '23uipy.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, Qt
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from future.moves import sys

import config
import tool


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(500, 10, 400, 41))
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setStyleSheet('font:16pt')

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label.setStyleSheet('font:14pt')

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.name.setStyleSheet('font:14pt')

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_2.setStyleSheet('font:14pt')

        self.gender = QtWidgets.QLabel(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.gender.setStyleSheet('font:14pt')

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.age.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.hand = QtWidgets.QLabel(self.centralwidget)
        self.hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.hand.setStyleSheet('font:14pt')

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 120, 1460, 510))
        self.table.setStyleSheet('background:white;font:14pt')
        self.table.setColumnCount(6)
        self.table.setRowCount(10)
        self.table.verticalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        self.table.setColumnWidth(0,250)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.setColumnWidth(1, 232)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.setColumnWidth(2,250)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.setColumnWidth(3, 232)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.setColumnWidth(4, 250)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.table.setColumnWidth(5, 232)

        item = QtWidgets.QTableWidgetItem('1.树')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem('11.羽毛球拍')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem('21.听诊器')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('2.笔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem('12.蜗牛')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem('22.金字塔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 4, item)

        item = QtWidgets.QTableWidgetItem('3.剪刀')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem('13.海马')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem('23.漏斗')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2,4, item)

        item = QtWidgets.QTableWidgetItem('4.花')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem('14.飞镖')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem('24.手风琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 4, item)

        item = QtWidgets.QTableWidgetItem('5.锯子')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem('15.口琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem('25.圆规')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(4, 4, item)

        item = QtWidgets.QTableWidgetItem('6.扫把')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem('16.犀牛')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem('26.三脚架')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 4, item)

        item = QtWidgets.QTableWidgetItem('7.冬菇')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem('17.冰屋')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem('27.钳')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 4, item)

        item = QtWidgets.QTableWidgetItem('8.衣架')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem('18.仙人掌')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem('28.花棚')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 4, item)

        item = QtWidgets.QTableWidgetItem('9.轮椅')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem('19.扶手电梯')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem('29.量角器')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(8,4, item)

        item = QtWidgets.QTableWidgetItem('10.骆驼')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem('20.竖琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem('30.算盘')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(9, 4, item)

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 650, 260, 40))
        self.label_7.setStyleSheet("font:16pt")

        self.totalScore = QtWidgets.QLineEdit(self.centralwidget)
        self.totalScore.setGeometry(QtCore.QRect(120, 650, 260, 40))
        self.totalScore.setStyleSheet("font:16pt;background:white")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 650, 260, 40))
        self.label_8.setStyleSheet("font:16pt")

        self.conclusion = QtWidgets.QLineEdit(self.centralwidget)
        self.conclusion.setGeometry(QtCore.QRect(500, 650, 940, 40))
        self.conclusion.setStyleSheet("font:16pt;background:white")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 700, 1460, 140))
        self.label_5.setStyleSheet("font:14pt")
        self.label_5.setWordWrap(True)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 880, 260, 40))
        self.label_6.setStyleSheet("font:16pt")

        self.dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 880, 260, 40))
        self.dateEdit.setStyleSheet("font:16pt;background:white")
        self.dateEdit.setCalendarPopup(True)

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(450, 880, 120, 40))
        self.saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.downLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downLoadButton.setGeometry(QtCore.QRect(590, 880, 120, 40))
        self.downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "波士顿命名测试（BNT）"))
        self.title.setText(_translate("MainWindow", "波士顿命名测试（BNT）"))
        self.label.setText(_translate("MainWindow", "姓名:"))
        self.name.setText(_translate("MainWindow", "--"))
        self.label_2.setText(_translate("MainWindow", "性别:"))
        self.gender.setText(_translate("MainWindow", "--"))
        self.label_3.setText(_translate("MainWindow", "年龄:"))
        self.age.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "患手:"))
        self.hand.setText(_translate("MainWindow", "--"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "图片"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "回答"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "图片"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "回答"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "图片"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "回答"))
        self.label_5.setText(_translate("MainWindow", "备注：分析指标为：①自发命名正确数，满分30分；②提示命名正确百分比，即在不能自发命名的图形中，经过语义提示后正确命名所占比例；③选择命名正确百分比，即在提示命名错误的图形中，正确选择命名所占的百分比；④选择命名回答的错误类型。\
BNT自发命名≤22分作为划界分，识别轻度认知障碍的敏感性为61％，识别轻度阿尔茨海默病的敏感性为79％，识别中度阿尔茨海默病的敏感性为95％，特异性均为81％。"))
        self.label_6.setText(_translate("MainWindow", "评定日期:"))
        self.label_7.setText(_translate("MainWindow", "总分:"))
        self.label_8.setText(_translate("MainWindow", "结论:"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.downLoadButton.setText(_translate("MainWindow", "导出"))


class BNT(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, patient_id):
        super(BNT, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']

        self.name.setText(self.patientInfo['name'])
        self.age.setText(str(self.patientInfo['age']))
        self.gender.setText(self.patientInfo['sex'])
        self.hand.setText(self.patientInfo['illness'])
        self.saveButton.clicked.connect(self.saveButtonClick)
        self.downLoadButton.clicked.connect(self.downLoadButtonClick)

    def saveButtonClick(self, *args):
        code_1 = self.totalScore.text()
        code_2 = self.conclusion.text()
        test_date = self.dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'code_1': code_1, 'code_2': code_2,
                 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def downLoadButtonClick(self, *args):
        self.saveButton.hide()
        self.downLoadButton.hide()
        img = self.grab()
        self.saveButton.show()
        self.downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.name.text()}_{self.dateEdit.text().replace('/', '-')}.png")
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = BNT()
    gui.show()
    sys.exit(app.exec_())