import json
import sys

import requests
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt, QDate
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QSlider, QMessageBox, QFileDialog

import config
import tool


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1600, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 80, 1500, 1000))

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 10, 300, 40))
        self.label.setStyleSheet("font:16pt")

        self.totalComBox = QtWidgets.QComboBox(self.centralwidget)
        self.totalComBox.setGeometry(QtCore.QRect(800, 10, 560, 40))
        self.totalComBox.addItems(['', '蒙特利尔认知评估量表(MoCA)', '简易智力状态检查量表（MMSE）', '波士顿命名测试（BNT）'])
        self.totalComBox.setStyleSheet("font:16pt;background:white")

        self.page = QtWidgets.QWidget()
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 800, 41))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setStyleSheet('font:16pt')

        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.MoCA_name = QtWidgets.QLabel(self.page)
        self.MoCA_name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.MoCA_name.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.MoCA_gender = QtWidgets.QLabel(self.page)
        self.MoCA_gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.MoCA_gender.setStyleSheet('font:14pt')

        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_5.setStyleSheet('font:14pt')

        self.MoCA_bornDate = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)  # 获取出生日期
        self.MoCA_bornDate.setGeometry(QtCore.QRect(605, 60, 200, 40))
        self.MoCA_bornDate.setStyleSheet("font:14pt")
        self.MoCA_bornDate.setCalendarPopup(True)

        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(830, 60, 200, 40))
        self.label_6.setStyleSheet('font:14pt')

        self.MoCA_educationLevel = QtWidgets.QLabel(self.page)  # 获取教育水平
        self.MoCA_educationLevel.setGeometry(QtCore.QRect(970, 60, 200, 40))
        self.MoCA_educationLevel.setStyleSheet('font:14pt;')

        self.MoCA_table = QtWidgets.QTableWidget(self.page)
        self.MoCA_table.setGeometry(QtCore.QRect(20, 120, 1460, 800))
        self.MoCA_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MoCA_table.setStyleSheet('background:white;font:14pt')
        self.MoCA_table.setColumnCount(14)
        self.MoCA_table.setRowCount(33)
        self.MoCA_table.verticalHeader().setVisible(False)
        self.MoCA_table.horizontalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem('视空间与执行功能')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(0, 0, item)
        self.MoCA_table.setSpan(0, 0, 1, 13)
        item = QtWidgets.QTableWidgetItem('得分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(0, 13, item)

        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setPixmap(QPixmap('./././src/fig/MoCA_1.png'))
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(1, 0, item)
        self.MoCA_table.setSpan(1, 0, 8, 3)
        self.MoCA_table.setSpan(9, 0, 1, 3)
        self.MoCA_table.setCellWidget(1, 0, self.label_7)

        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.label_8.setPixmap(QPixmap('D:\Pycharm\留存\MoCA_2.png'))
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(1, 3, item)
        self.MoCA_table.setSpan(1, 3, 8, 3)
        self.MoCA_table.setSpan(9, 3, 1, 4)
        self.MoCA_table.setCellWidget(1, 3, self.label_8)
        item = QtWidgets.QTableWidgetItem('复\n制\n立\n方\n体')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(1, 6, item)
        self.MoCA_table.setColumnWidth(6, 40)
        self.MoCA_table.setSpan(1, 6, 8, 1)

        self.MoCA_oneScore = QtWidgets.QComboBox(self.page)
        self.MoCA_oneScore.addItems(['', '0', '1', '2', '3', '4', '5'])
        self.MoCA_oneScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(1, 13, item)
        self.MoCA_table.setSpan(1, 13, 9, 1)
        self.MoCA_table.setCellWidget(1, 13, self.MoCA_oneScore)

        item = QtWidgets.QTableWidgetItem('画钟表（ 11点过10分 ）（3分）')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(1, 7, item)
        self.MoCA_table.setSpan(1, 7, 1, 6)

        self.MoCA_uploadButton = QtWidgets.QPushButton(self.page)
        self.MoCA_uploadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(2, 7, item)
        self.MoCA_table.setCellWidget(2, 7, self.MoCA_uploadButton)
        self.MoCA_table.setSpan(2, 7, 1, 6)
        self.MoCA_table.setSpan(3, 7, 6, 6)
        item = QtWidgets.QTableWidgetItem('轮廓')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem('指针')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem('数字')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(9, 11, item)

        item = QtWidgets.QTableWidgetItem('命名')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(10, 0, item)
        self.MoCA_table.setSpan(10, 0, 1, 14)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.label_9.setPixmap(QPixmap('D:\Pycharm\留存\MoCA_3.png'))
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(11, 0, item)
        self.MoCA_table.setSpan(11, 0, 4, 3)
        self.MoCA_table.setSpan(15, 0, 1, 3)
        self.MoCA_table.setCellWidget(11, 0, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.label_10.setPixmap(QPixmap('D:\Pycharm\留存\MoCA_4.png'))
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(11, 3, item)
        self.MoCA_table.setSpan(11, 3, 4, 3)
        self.MoCA_table.setCellWidget(11, 3, self.label_10)
        self.MoCA_table.setSpan(15, 3, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.label_11.setPixmap(QPixmap('D:\Pycharm\留存\MoCA_5.png'))
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(11, 6, item)
        self.MoCA_table.setSpan(11, 6, 4, 7)
        self.MoCA_table.setCellWidget(11, 6, self.label_11)
        self.MoCA_table.setSpan(15, 6, 1, 7)
        self.MoCA_twoScore = QtWidgets.QComboBox(self.page)
        self.MoCA_twoScore.addItems(['', '0', '1', '2', '3'])
        self.MoCA_twoScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(11, 13, item)
        self.MoCA_table.setSpan(11, 13, 5, 1)
        self.MoCA_table.setCellWidget(11, 13, self.MoCA_twoScore)

        item = QtWidgets.QTableWidgetItem('记忆')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 0, item)
        self.MoCA_table.setSpan(16, 0, 3, 1)
        item = QtWidgets.QTableWidgetItem('读出下列词语，然后由患者重复上述过程重复2次，5分钟后回忆。')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 1, item)
        self.MoCA_table.setSpan(16, 1, 3, 3)
        item = QtWidgets.QTableWidgetItem('面孔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 5, item)
        self.MoCA_table.setSpan(16, 5, 1, 2)
        self.MoCA_table.setSpan(17, 5, 1, 2)
        self.MoCA_table.setSpan(18, 5, 1, 2)
        item = QtWidgets.QTableWidgetItem('天鹅绒')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 7, item)
        self.MoCA_table.setSpan(16, 7, 1, 2)
        self.MoCA_table.setSpan(17, 7, 1, 2)
        self.MoCA_table.setSpan(18, 7, 1, 2)
        item = QtWidgets.QTableWidgetItem('教堂')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 9, item)
        self.MoCA_table.setSpan(16, 9, 1, 2)
        self.MoCA_table.setSpan(17, 9, 1, 2)
        self.MoCA_table.setSpan(18, 9, 1, 2)
        item = QtWidgets.QTableWidgetItem('第一次')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem('第二次')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem('菊花')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 11, item)
        item = QtWidgets.QTableWidgetItem('红色')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 12, item)
        item = QtWidgets.QTableWidgetItem('不计分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(16, 13, item)
        self.MoCA_table.setSpan(16, 13, 3, 1)

        item = QtWidgets.QTableWidgetItem('注意')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(19, 0, item)
        self.MoCA_table.setSpan(19, 0, 2, 1)
        item = QtWidgets.QTableWidgetItem('读出下列数字，请患者重复（每秒1个）。')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(19, 1, item)
        self.MoCA_table.setSpan(19, 1, 2, 9)
        item = QtWidgets.QTableWidgetItem('顺背')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(19, 10, item)
        item = QtWidgets.QTableWidgetItem('21854')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(19, 12, item)
        item = QtWidgets.QTableWidgetItem('倒背')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(20, 10, item)
        item = QtWidgets.QTableWidgetItem('742')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(20, 12, item)
        self.MoCA_threeScore = QtWidgets.QComboBox(self.page)
        self.MoCA_threeScore.addItems(['', '0', '1', '2'])
        self.MoCA_threeScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(19, 13, item)
        self.MoCA_table.setSpan(19, 13, 2, 1)
        self.MoCA_table.setCellWidget(19, 13, self.MoCA_threeScore)

        item = QtWidgets.QTableWidgetItem('读出下列数字，每当数字出现1时，患者敲1下桌面，错误数大于或等于2不给分。')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(21, 0, item)
        self.MoCA_table.setRowHeight(21, 80)
        self.MoCA_table.setSpan(21, 0, 1, 5)
        self.MoCA_table.setSpan(21, 5, 1, 4)
        item = QtWidgets.QTableWidgetItem('52139411806215194511141905112')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(21, 9, item)
        self.MoCA_table.setSpan(21, 9, 1, 4)
        self.MoCA_fourScore = QtWidgets.QComboBox(self.page)
        self.MoCA_fourScore.addItems(['', '0', '1', '2'])
        self.MoCA_fourScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(21, 13, item)
        self.MoCA_table.setCellWidget(21, 13, self.MoCA_fourScore)

        item = QtWidgets.QTableWidgetItem('100连续减7')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 0, item)
        self.MoCA_table.setSpan(22, 0, 1, 3)
        item = QtWidgets.QTableWidgetItem('93')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 4, item)
        item = QtWidgets.QTableWidgetItem('86')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 6, item)
        item = QtWidgets.QTableWidgetItem('79')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 8, item)
        item = QtWidgets.QTableWidgetItem('72')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 10, item)
        item = QtWidgets.QTableWidgetItem('65')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 12, item)
        item = QtWidgets.QTableWidgetItem('4~5个正确给3分，2~3个正确给1分，全部错误为0分。')
        item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.MoCA_table.setItem(23, 0, item)
        self.MoCA_table.setSpan(23, 0, 1, 13)
        self.MoCA_fiveScore = QtWidgets.QComboBox(self.page)
        self.MoCA_fiveScore.addItems(['', '0', '1', '2', '3'])
        self.MoCA_fiveScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(22, 13, item)
        self.MoCA_table.setSpan(22, 13, 2, 1)
        self.MoCA_table.setCellWidget(22, 13, self.MoCA_fiveScore)

        item = QtWidgets.QTableWidgetItem('语言')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(24, 0, item)
        self.MoCA_table.setSpan(24, 0, 2, 1)
        item = QtWidgets.QTableWidgetItem('重复：我只知道今天张亮是来帮过忙的人。')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(24, 1, item)
        self.MoCA_table.setSpan(24, 1, 1, 4)
        self.MoCA_table.setSpan(24, 5, 1, 2)
        item = QtWidgets.QTableWidgetItem('狗在房间的时候，猫总是躲在沙发下面')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(24, 7, item)
        self.MoCA_table.setSpan(24, 7, 1, 4)
        self.MoCA_table.setSpan(24, 11, 1, 2)
        self.MoCA_sixScore = QtWidgets.QComboBox(self.page)
        self.MoCA_sixScore.addItems(['', '0', '1', '2'])
        self.MoCA_sixScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(24, 13, item)
        self.MoCA_table.setCellWidget(24, 13, self.MoCA_sixScore)
        item = QtWidgets.QTableWidgetItem('流畅性：在1分钟内尽可能多地说出动物的名字。')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(25, 1, item)
        self.MoCA_table.setSpan(25, 1, 1, 5)
        self.MoCA_table.setSpan(25, 6, 1, 2)
        self.MoCA_table.setSpan(25, 8, 1, 3)
        item = QtWidgets.QTableWidgetItem('(N≥11名称)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(25, 11, item)
        self.MoCA_table.setSpan(25, 11, 1, 2)
        self.MoCA_sevenScore = QtWidgets.QComboBox(self.page)
        self.MoCA_sevenScore.addItems(['', '0', '1'])
        self.MoCA_sevenScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(25, 13, item)
        self.MoCA_table.setCellWidget(25, 13, self.MoCA_sevenScore)

        item = QtWidgets.QTableWidgetItem('抽象')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem('词语相似性：香蕉—桔子=水果')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(26, 1, item)
        self.MoCA_table.setSpan(26, 1, 1, 5)
        self.MoCA_table.setSpan(26, 6, 1, 2)
        item = QtWidgets.QTableWidgetItem('火车—自行车 ')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(26, 8, item)
        self.MoCA_table.setSpan(26, 8, 1, 2)
        item = QtWidgets.QTableWidgetItem('手表—尺子 ')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(26, 11, item)
        self.MoCA_table.setSpan(26, 11, 1, 2)
        self.MoCA_eightScore = QtWidgets.QComboBox(self.page)
        self.MoCA_eightScore.addItems(['', '0', '1', '2'])
        self.MoCA_eightScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(26, 13, item)
        self.MoCA_table.setCellWidget(26, 13, self.MoCA_eightScore)

        item = QtWidgets.QTableWidgetItem('延迟回忆')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 0, item)
        self.MoCA_table.setSpan(27, 0, 4, 1)
        item = QtWidgets.QTableWidgetItem('回忆时不能提醒')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 1, item)
        self.MoCA_table.setSpan(27, 1, 2, 2)
        item = QtWidgets.QTableWidgetItem('面孔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 3, item)
        self.MoCA_table.setSpan(28, 3, 1, 3)
        self.MoCA_table.setSpan(27, 3, 1, 3)
        item = QtWidgets.QTableWidgetItem('天鹅绒')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 6, item)
        item = QtWidgets.QTableWidgetItem('教堂')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 7, item)
        self.MoCA_table.setSpan(28, 7, 1, 3)
        self.MoCA_table.setSpan(27, 7, 1, 3)
        item = QtWidgets.QTableWidgetItem('菊花')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 10, item)
        item = QtWidgets.QTableWidgetItem('红色')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 11, item)
        item = QtWidgets.QTableWidgetItem('仅根据非提示记忆得分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 12, item)
        self.MoCA_table.setSpan(27, 12, 4, 1)
        self.MoCA_nineScore = QtWidgets.QComboBox(self.centralwidget)
        self.MoCA_nineScore.addItems(['', '0', '1', '2'])
        self.MoCA_nineScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(27, 13, item)
        self.MoCA_table.setCellWidget(27, 13, self.MoCA_nineScore)
        self.MoCA_table.setSpan(27, 13, 2, 1)
        item = QtWidgets.QTableWidgetItem('分类提示：')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(29, 1, item)
        self.MoCA_table.setSpan(29, 1, 1, 2)
        self.MoCA_table.setSpan(29, 3, 1, 3)
        self.MoCA_table.setSpan(29, 7, 1, 3)
        self.MoCA_tenScore = QtWidgets.QComboBox(self.page)
        self.MoCA_tenScore.addItems(['', '0', '1', '2'])
        self.MoCA_tenScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(29, 13, item)
        self.MoCA_table.setCellWidget(29, 13, self.MoCA_tenScore)
        item = QtWidgets.QTableWidgetItem('多选提示：')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(30, 1, item)
        self.MoCA_table.setSpan(30, 1, 1, 2)
        self.MoCA_table.setSpan(30, 3, 1, 3)
        self.MoCA_table.setSpan(30, 7, 1, 3)
        self.MoCA_elevenScore = QtWidgets.QComboBox(self.page)
        self.MoCA_elevenScore.addItems(['', '0', '1', '2'])
        self.MoCA_elevenScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(30, 13, item)
        self.MoCA_table.setCellWidget(30, 13, self.MoCA_elevenScore)
        item = QtWidgets.QTableWidgetItem('定向')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem('日期')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 1, item)
        item = QtWidgets.QTableWidgetItem('月份')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 3, item)
        item = QtWidgets.QTableWidgetItem('年代')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 5, item)
        self.MoCA_table.setColumnWidth(6, 120)
        item = QtWidgets.QTableWidgetItem('星期几')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 7, item)
        item = QtWidgets.QTableWidgetItem('地点')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 9, item)
        item = QtWidgets.QTableWidgetItem('城市')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 11, item)
        self.MoCA_twelveScore = QtWidgets.QComboBox(self.page)
        self.MoCA_twelveScore.addItems(['', '0', '1', '2', '3', '4', '5', '6'])
        self.MoCA_twelveScore.setStyleSheet('font:16pt')
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(31, 13, item)
        self.MoCA_table.setCellWidget(31, 13, self.MoCA_twelveScore)

        item = QtWidgets.QTableWidgetItem('总分(30)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MoCA_table.setItem(32, 0, item)
        self.MoCA_table.setSpan(32, 1, 1, 12)

        self.MoCA_table.setWordWrap(True)

        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(20, 940, 200, 40))
        self.label_12.setStyleSheet('font:14pt')

        self.MoCA_evaluationDate = QtWidgets.QDateEdit(QDate.currentDate(), self.page)
        self.MoCA_evaluationDate.setGeometry(QtCore.QRect(160, 940, 200, 40))
        self.MoCA_evaluationDate.setStyleSheet("font:14pt;background:white")
        self.MoCA_evaluationDate.setCalendarPopup(True)

        self.MoCA_saveButton = QtWidgets.QPushButton(self.page)
        self.MoCA_saveButton.setGeometry(QtCore.QRect(450, 940, 120, 40))
        self.MoCA_saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.MoCA_downLoadButton = QtWidgets.QPushButton(self.page)
        self.MoCA_downLoadButton.setGeometry(QtCore.QRect(590, 940, 120, 40))
        self.MoCA_downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")
        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(300, 10, 900, 41))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setStyleSheet('font:16pt')

        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label_14.setStyleSheet('font:14pt')

        self.MMSE_name = QtWidgets.QLabel(self.page_2)
        self.MMSE_name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.MMSE_name.setStyleSheet('font:14pt')

        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_15.setStyleSheet('font:14pt')

        self.MMSE_gender = QtWidgets.QLabel(self.page_2)
        self.MMSE_gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.MMSE_gender.setStyleSheet('font:14pt')

        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_16.setStyleSheet('font:14pt')

        self.MMSE_age = QtWidgets.QLabel(self.page_2)
        self.MMSE_age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.MMSE_age.setStyleSheet('font:14pt')

        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_17.setStyleSheet('font:14pt')

        self.MMSE_hand = QtWidgets.QLabel(self.page_2)
        self.MMSE_hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.MMSE_hand.setStyleSheet('font:14pt')

        self.MMSE_table = QtWidgets.QTableWidget(self.page_2)
        self.MMSE_table.setGeometry(QtCore.QRect(20, 120, 1460, 700))
        self.MMSE_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MMSE_table.setStyleSheet('background:white;font:14pt')
        self.MMSE_table.setColumnCount(5)
        self.MMSE_table.setRowCount(23)
        self.MMSE_table.verticalHeader().setVisible(False)
        self.MMSE_table.horizontalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.MMSE_table.setHorizontalHeaderItem(0, item)  # 列
        self.MMSE_table.setColumnWidth(0, 120)
        item = QtWidgets.QTableWidgetItem()
        self.MMSE_table.setHorizontalHeaderItem(1, item)
        self.MMSE_table.setColumnWidth(1, 680)
        item = QtWidgets.QTableWidgetItem()
        self.MMSE_table.setHorizontalHeaderItem(2, item)
        self.MMSE_table.setColumnWidth(2, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MMSE_table.setHorizontalHeaderItem(3, item)
        self.MMSE_table.setColumnWidth(3, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MMSE_table.setHorizontalHeaderItem(4, item)
        self.MMSE_table.setColumnWidth(4, 208)

        item = QtWidgets.QTableWidgetItem('项目')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(0, 0, item)
        self.MMSE_table.setSpan(0, 0, 1, 2)
        item = QtWidgets.QTableWidgetItem('评分标准')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem('评分1')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem('评分2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('定向力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(1, 0, item)
        self.MMSE_table.setSpan(1, 0, 2, 1)
        item = QtWidgets.QTableWidgetItem('现在是(哪一年) (什么季节) (几月) (几号) (星期几)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem('我们现在在哪里(哪个国家)(哪个城市)(哪个城区) (哪个医院)(第几层楼)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(2, 2, item)

        item = QtWidgets.QTableWidgetItem('记忆力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(3, 0, item)
        self.MMSE_table.setSpan(3, 0, 2, 1)
        self.MMSE_table.setRowHeight(3, 100)
        item = QtWidgets.QTableWidgetItem('现在我要说出三样东西的名称，在我讲完之后，请您重复说一遍。请您记出这三样东西，因为几分钟后还要再问您。(请仔细说清楚，每一样东西一秒钟)。\
        “皮球”“国旗”“树木”')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem('请你把这三样东西说一遍(以第一次答案计分)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem('3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(3, 2, item)
        self.MMSE_table.setSpan(3, 2, 2, 1)
        self.MMSE_table.setSpan(3, 3, 2, 1)
        self.MMSE_table.setSpan(3, 4, 2, 1)

        item = QtWidgets.QTableWidgetItem('注意力和计算力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(5, 0, item)
        self.MMSE_table.setRowHeight(5, 160)
        item = QtWidgets.QTableWidgetItem('请你算一算100减去7，然后从所得的数目再减去7，如此一直计算下去，请你将每减一个7后的答案告诉我，直到我说“停”为止。(若错了，但下一个答案是对的，那么只记一次错误) \
        93…，86…，79…，72…，65…')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(5, 2, item)

        item = QtWidgets.QTableWidgetItem('回忆力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(6, 0, item)
        self.MMSE_table.setRowHeight(6, 80)
        item = QtWidgets.QTableWidgetItem('现在请您说出刚才我让您记住的那三样东西？“皮球”“国旗”“树木”（首次重复的答案）')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem('3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(6, 2, item)

        item = QtWidgets.QTableWidgetItem('语言能力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(7, 0, item)
        self.MMSE_table.setSpan(7, 0, 15, 1)
        self.MMSE_table.setSpan(7, 2, 3, 1)
        self.MMSE_table.setSpan(7, 3, 3, 1)
        self.MMSE_table.setSpan(7, 4, 3, 1)
        self.MMSE_table.setSpan(10, 2, 3, 1)
        self.MMSE_table.setSpan(10, 3, 3, 1)
        self.MMSE_table.setSpan(10, 4, 3, 1)
        self.MMSE_table.setSpan(13, 2, 3, 1)
        self.MMSE_table.setSpan(13, 3, 3, 1)
        self.MMSE_table.setSpan(13, 4, 3, 1)
        self.MMSE_table.setSpan(17, 2, 3, 1)
        self.MMSE_table.setSpan(17, 3, 3, 1)
        self.MMSE_table.setSpan(17, 4, 3, 1)
        item = QtWidgets.QTableWidgetItem('命名能力')
        self.MMSE_table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem('每项1分，共2分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem(' （出示手表）这个东西叫什么？')
        self.MMSE_table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem(' （出示铅笔）这个东西叫什么？')
        self.MMSE_table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem('复述能力')
        self.MMSE_table.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem('     现在我要说一句话，请您跟着我清楚地重复一遍。')
        self.MMSE_table.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem('     “四十四只石狮子”')
        self.MMSE_table.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem('阅读能力')
        self.MMSE_table.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem('     请您念一念这句话，并按照上面的意思去做。')
        self.MMSE_table.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem('     “闭上您的眼睛”')
        self.MMSE_table.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem('我给您一张纸，请您按我说的去做，现在开始：“用右手拿着这张纸，用两只手将它对折起来，放在您的大腿上”（不要重复说明，也不要示范）')
        self.MMSE_table.setItem(16, 1, item)
        self.MMSE_table.setRowHeight(16, 120)
        item = QtWidgets.QTableWidgetItem('每个动作1分，共3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem('书写能力')
        self.MMSE_table.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem('     请您给我写一个完整的句子（须有意义，有主语和动词），记下所叙述句子的全文')
        self.MMSE_table.setItem(18, 1, item)
        self.MMSE_table.setRowHeight(18, 100)
        self.MMSE_table.setRowHeight(19, 200)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem('结构能力')
        self.MMSE_table.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem('     这是一张图，请您在同一张纸上照样把它画下来。（对：两个五边形的图案，交叉处有个小四边形，得1分）')
        self.MMSE_table.setItem(21, 1, item)
        self.MMSE_table.setRowHeight(21, 80)
        item = QtWidgets.QTableWidgetItem('得分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MMSE_table.setItem(22, 0, item)
        self.MMSE_table.setWordWrap(True)

        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(20, 840, 260, 40))
        self.label_18.setStyleSheet("font:16pt")

        self.MMSE_dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.page_2)
        self.MMSE_dateEdit.setGeometry(QtCore.QRect(170, 840, 260, 40))
        self.MMSE_dateEdit.setStyleSheet("font:16pt;background:white")
        self.MMSE_dateEdit.setCalendarPopup(True)

        self.MMSE_saveButton = QtWidgets.QPushButton(self.page_2)
        self.MMSE_saveButton.setGeometry(QtCore.QRect(450, 840, 120, 40))
        self.MMSE_saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.MMSE_downLoadButton = QtWidgets.QPushButton(self.page_2)
        self.MMSE_downLoadButton.setGeometry(QtCore.QRect(590, 840, 120, 40))
        self.MMSE_downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.stackedWidget.addWidget(self.page_2)

        self.page_3 = QtWidgets.QWidget()
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(500, 10, 400, 41))
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_19.setStyleSheet('font:16pt')

        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label_20.setStyleSheet('font:14pt')

        self.BNT_name = QtWidgets.QLabel(self.page_3)
        self.BNT_name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.BNT_name.setStyleSheet('font:14pt')

        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_21.setStyleSheet('font:14pt')

        self.BNT_gender = QtWidgets.QLabel(self.page_3)
        self.BNT_gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.BNT_gender.setStyleSheet('font:14pt')

        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_22.setStyleSheet('font:14pt')

        self.BNT_age = QtWidgets.QLabel(self.page_3)
        self.BNT_age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.BNT_age.setStyleSheet('font:14pt')

        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_23.setStyleSheet('font:14pt')

        self.BNT_hand = QtWidgets.QLabel(self.page_3)
        self.BNT_hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.BNT_hand.setStyleSheet('font:14pt')

        self.BNT_table = QtWidgets.QTableWidget(self.page_3)
        self.BNT_table.setGeometry(QtCore.QRect(20, 120, 1460, 510))
        self.BNT_table.setStyleSheet('background:white;font:14pt')
        self.BNT_table.setColumnCount(6)
        self.BNT_table.setRowCount(10)
        self.BNT_table.verticalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(0, item)
        self.BNT_table.setColumnWidth(0, 250)
        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(1, item)
        self.BNT_table.setColumnWidth(1, 232)
        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(2, item)
        self.BNT_table.setColumnWidth(2, 250)
        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(3, item)
        self.BNT_table.setColumnWidth(3, 232)
        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(4, item)
        self.BNT_table.setColumnWidth(4, 250)
        item = QtWidgets.QTableWidgetItem()
        self.BNT_table.setHorizontalHeaderItem(5, item)
        self.BNT_table.setColumnWidth(5, 232)

        item = QtWidgets.QTableWidgetItem('1.树')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem('11.羽毛球拍')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem('21.听诊器')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('2.笔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem('12.蜗牛')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem('22.金字塔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(1, 4, item)

        item = QtWidgets.QTableWidgetItem('3.剪刀')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem('13.海马')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem('23.漏斗')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(2, 4, item)

        item = QtWidgets.QTableWidgetItem('4.花')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem('14.飞镖')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem('24.手风琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(3, 4, item)

        item = QtWidgets.QTableWidgetItem('5.锯子')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem('15.口琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem('25.圆规')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(4, 4, item)

        item = QtWidgets.QTableWidgetItem('6.扫把')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem('16.犀牛')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem('26.三脚架')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(5, 4, item)

        item = QtWidgets.QTableWidgetItem('7.冬菇')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem('17.冰屋')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem('27.钳')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(6, 4, item)

        item = QtWidgets.QTableWidgetItem('8.衣架')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem('18.仙人掌')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem('28.花棚')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(7, 4, item)

        item = QtWidgets.QTableWidgetItem('9.轮椅')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem('19.扶手电梯')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem('29.量角器')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(8, 4, item)

        item = QtWidgets.QTableWidgetItem('10.骆驼')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem('20.竖琴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem('30.算盘')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.BNT_table.setItem(9, 4, item)

        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setGeometry(QtCore.QRect(20, 650, 260, 40))
        self.label_24.setStyleSheet("font:16pt")

        self.BNT_totalScore = QtWidgets.QLineEdit(self.page_3)
        self.BNT_totalScore.setGeometry(QtCore.QRect(120, 650, 260, 40))
        self.BNT_totalScore.setStyleSheet("font:16pt;background:white")

        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(400, 650, 260, 40))
        self.label_25.setStyleSheet("font:16pt")

        self.BNT_conclusion = QtWidgets.QLineEdit(self.page_3)
        self.BNT_conclusion.setGeometry(QtCore.QRect(500, 650, 940, 40))
        self.BNT_conclusion.setStyleSheet("font:16pt;background:white")

        self.label_26 = QtWidgets.QLabel(self.page_3)
        self.label_26.setGeometry(QtCore.QRect(20, 700, 1460, 140))
        self.label_26.setStyleSheet("font:14pt")
        self.label_26.setWordWrap(True)

        self.label_27 = QtWidgets.QLabel(self.page_3)
        self.label_27.setGeometry(QtCore.QRect(20, 880, 260, 40))
        self.label_27.setStyleSheet("font:16pt")

        self.BNT_dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.page_3)
        self.BNT_dateEdit.setGeometry(QtCore.QRect(170, 880, 260, 40))
        self.BNT_dateEdit.setStyleSheet("font:16pt;background:white")
        self.BNT_dateEdit.setCalendarPopup(True)

        self.BNT_saveButton = QtWidgets.QPushButton(self.page_3)
        self.BNT_saveButton.setGeometry(QtCore.QRect(450, 880, 120, 40))
        self.BNT_saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.BNT_downLoadButton = QtWidgets.QPushButton(self.page_3)
        self.BNT_downLoadButton.setGeometry(QtCore.QRect(590, 880, 120, 40))
        self.BNT_downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.stackedWidget.setCurrentIndex(0)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "认知功能评定"))
        self.label.setText(_translate("MainWindow", "认知功能评定"))
        self.label_2.setText(_translate("MainWindow", "蒙特利尔认知评估量表(MoCA)"))
        self.label_3.setText(_translate("MainWindow", "姓名:"))
        self.MoCA_name.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "性别:"))
        self.MoCA_gender.setText(_translate("MainWindow", "--"))
        self.label_5.setText(_translate("MainWindow", "出生日期:"))
        self.label_6.setText(_translate("MainWindow", "教育水平:"))
        self.label_12.setText(_translate("MainWindow", "评定日期:"))
        self.MoCA_uploadButton.setText(_translate("MainWindow", "上传(点我)"))
        self.MoCA_saveButton.setText(_translate("MainWindow", "保存"))
        self.MoCA_downLoadButton.setText(_translate("MainWindow", "导出"))
        self.label_13.setText(_translate("MainWindow", "简易认知功能检查 (Mini-Mental State Examination, MMSE)"))
        self.label_14.setText(_translate("MainWindow", "姓名:"))
        self.MMSE_name.setText(_translate("MainWindow", "--"))
        self.label_15.setText(_translate("MainWindow", "性别:"))
        self.MMSE_gender.setText(_translate("MainWindow", "--"))
        self.label_16.setText(_translate("MainWindow", "年龄:"))
        self.MMSE_age.setText(_translate("MainWindow", "--"))
        self.label_17.setText(_translate("MainWindow", "患手:"))
        self.MMSE_hand.setText(_translate("MainWindow", "--"))
        self.label_18.setText(_translate("MainWindow", "评定日期:"))
        self.MMSE_saveButton.setText(_translate("MainWindow", "保存"))
        self.MMSE_downLoadButton.setText(_translate("MainWindow", "导出"))
        self.label_19.setText(_translate("MainWindow", "波士顿命名测试（BNT）"))
        self.label_20.setText(_translate("MainWindow", "姓名:"))
        self.BNT_name.setText(_translate("MainWindow", "--"))
        self.label_21.setText(_translate("MainWindow", "性别:"))
        self.BNT_gender.setText(_translate("MainWindow", "--"))
        self.label_22.setText(_translate("MainWindow", "年龄:"))
        self.BNT_age.setText(_translate("MainWindow", "--"))
        self.label_23.setText(_translate("MainWindow", "患手:"))
        self.BNT_hand.setText(_translate("MainWindow", "--"))
        item = self.BNT_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "图片"))
        item = self.BNT_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "回答"))
        item = self.BNT_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "图片"))
        item = self.BNT_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "回答"))
        item = self.BNT_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "图片"))
        item = self.BNT_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "回答"))
        self.label_26.setText(_translate("MainWindow", "备注：分析指标为：①自发命名正确数，满分30分；②提示命名正确百分比，即在不能自发命名的图形中，经过语义提示后正确命名所占比例；③选择命名正确百分比，即在提示命名错误的图形中，正确选择命名所占的百分比；④选择命名回答的错误类型。\
        BNT自发命名≤22分作为划界分，识别轻度认知障碍的敏感性为61％，识别轻度阿尔茨海默病的敏感性为79％，识别中度阿尔茨海默病的敏感性为95％，特异性均为81％。"))
        self.label_27.setText(_translate("MainWindow", "评定日期:"))
        self.label_24.setText(_translate("MainWindow", "总分:"))
        self.label_25.setText(_translate("MainWindow", "结论:"))
        self.BNT_saveButton.setText(_translate("MainWindow", "保存"))
        self.BNT_downLoadButton.setText(_translate("MainWindow", "导出"))






class cognitiveFunctionAssessment(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, patient_id):
        super(cognitiveFunctionAssessment, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']

        self.MoCA_name.setText(self.patientInfo['name'])
        self.MoCA_educationLevel.setText(str(self.patientInfo['education']))
        self.MoCA_gender.setText(self.patientInfo['sex'])

        self.MMSE_name.setText(self.patientInfo['name'])
        self.MMSE_age.setText(str(self.patientInfo['age']))
        self.MMSE_gender.setText(self.patientInfo['sex'])
        self.MMSE_hand.setText(self.patientInfo['illness'])

        self.BNT_name.setText(self.patientInfo['name'])
        self.BNT_age.setText(str(self.patientInfo['age']))
        self.BNT_gender.setText(self.patientInfo['sex'])
        self.BNT_hand.setText(self.patientInfo['illness'])

        self.totalComBox.currentIndexChanged.connect(self.totalComBoxClick)
        self.MoCA_uploadButton.clicked.connect(self.MoCA_uploadButtonClick)
        self.MoCA_saveButton.clicked.connect(self.MoCA_saveButtonClick)
        self.MoCA_downLoadButton.clicked.connect(self.MoCA_downLoadButtonClick)
        self.MMSE_saveButton.clicked.connect(self.MMSE_saveButtonClick)
        self.MMSE_downLoadButton.clicked.connect(self.MMSE_downLoadButtonClick)
        self.BNT_saveButton.clicked.connect(self.BNT_saveButtonClick)
        self.BNT_downLoadButton.clicked.connect(self.BNT_downLoadButtonClick)


    def totalComBoxClick(self, *args):
        if(self.totalComBox.currentIndex()==1):
            self.stackedWidget.setCurrentIndex(0)
        elif(self.totalComBox.currentIndex()==2):
            self.stackedWidget.setCurrentIndex(1)
        else:
            self.stackedWidget.setCurrentIndex(2)

    def MoCA_uploadButtonClick(self, *args):  # 上传
        ...

    def MoCA_saveButtonClick(self, *args):
        code_1 = self.MoCA_bornDate.text()
        code_2 = self.MoCA_oneScore.currentText()
        code_3 = self.MoCA_twoScore.currentText()
        code_4 = self.MoCA_threeScore.currentText()
        code_5 = self.MoCA_fourScore.currentText()
        code_6 = self.MoCA_fiveScore.currentText()
        code_7 = self.MoCA_sixScore.currentText()
        code_8 = self.MoCA_sevenScore.currentText()
        code_9 = self.MoCA_eightScore.currentText()
        code_10 = self.MoCA_nineScore.currentText()
        code_11 = self.MoCA_tenScore.currentText()
        code_12 = self.MoCA_elevenScore.currentText()
        code_13 = self.MoCA_twelveScore.currentText()

        test_date = self.MoCA_evaluationDate.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'code_1': code_1, 'code_2': code_2,
                 'code_3': code_3, 'code_4': code_4, 'code_5': code_5, 'code_6': code_6, 'code_7': code_7,
                 'code_8': code_8, 'code_9': code_9, \
                 'code_10': code_10, 'code_11': code_11, 'code_12': code_12, 'code_13': code_13, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def MoCA_downLoadButtonClick(self, *args):
        self.MoCA_saveButton.hide()
        self.MoCA_downLoadButton.hide()
        img = self.grab()
        self.MoCA_saveButton.show()
        self.MoCA_downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.MoCA_name.text()}_{self.MoCA_evaluationDate.text().replace('/', '-')}_{self.totalComBox.currentText()}.png")
        ...

    def MMSE_saveButtonClick(self, *args):
        test_date = self.MMSE_dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def MMSE_downLoadButtonClick(self, *args):
        self.MMSE_saveButton.hide()
        self.MMSE_downLoadButton.hide()
        img = self.grab()
        self.MMSE_saveButton.show()
        self.MMSE_downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.MMSE_name.text()}_{self.MMSE_dateEdit.text().replace('/', '-')}_{self.totalComBox.currentText()}.png")
        ...

    def BNT_saveButtonClick(self, *args):
        code_1 = self.BNT_totalScore.text()
        code_2 = self.BNT_conclusion.text()
        test_date = self.BNT_dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'code_1': code_1, 'code_2': code_2,
                 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def BNT_downLoadButtonClick(self, *args):
        self.BNT_saveButton.hide()
        self.BNT_downLoadButton.hide()
        img = self.grab()
        self.BNT_saveButton.show()
        self.BNT_downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.BNT_name.text()}_{self.BNT_dateEdit.text().replace('/', '-')}_{self.totalComBox.currentText()}.png")
        ...

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = cognitiveFunctionAssessment()
    gui.show()
    sys.exit(app.exec_())


