import json
import sys

import requests
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt, QDate
from PyQt5.QtWidgets import QFileDialog, QMessageBox

import config
import tool


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1600, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 80, 1500, 1000))

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 10, 560, 40))
        self.label.setStyleSheet("font:16pt")

        self.totalComBox = QtWidgets.QComboBox(self.centralwidget)
        self.totalComBox.setGeometry(QtCore.QRect(800, 10, 560, 40))
        self.totalComBox.addItems(['', '改良Barthel指数（MBI）', '功能独立性测评（FIM）'])
        self.totalComBox.setStyleSheet("font:16pt;background:white")

        self.page = QtWidgets.QWidget()
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label_2.setStyleSheet('font:14pt')

        self.MBI_name = QtWidgets.QLabel(self.page)
        self.MBI_name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.MBI_name.setText('--')
        self.MBI_name.setStyleSheet('font:14pt')

        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.MBI_gender = QtWidgets.QLabel(self.page)
        self.MBI_gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.MBI_gender.setText('--')
        self.MBI_gender.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.MBI_age = QtWidgets.QLabel(self.page)
        self.MBI_age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.MBI_age.setText('--')
        self.MBI_age.setStyleSheet('font:14pt')

        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_5.setStyleSheet('font:14pt')

        self.MBI_hand = QtWidgets.QLabel(self.page)
        self.MBI_hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.MBI_hand.setText('--')
        self.MBI_hand.setStyleSheet('font:14pt')

        self.label_6= QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(500, 10, 400, 41))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setStyleSheet('font:16pt')

        self.MBI_table = QtWidgets.QTableWidget(self.page)
        self.MBI_table.setGeometry(QtCore.QRect(20, 120, 1460, 700))
        self.MBI_table.setStyleSheet('background:white')
        self.MBI_table.setColumnCount(7)
        self.MBI_table.setRowCount(11)
        self.MBI_table.verticalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()  # 行
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setVerticalHeaderItem(0, item)
        self.MBI_table.setRowHeight(0, 60)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setVerticalHeaderItem(1, item)
        self.MBI_table.setRowHeight(1, 60)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setVerticalHeaderItem(2, item)
        self.MBI_table.setRowHeight(2, 60)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setVerticalHeaderItem(3, item)
        self.MBI_table.setRowHeight(3, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(4, item)
        self.MBI_table.setRowHeight(4, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(5, item)
        self.MBI_table.setRowHeight(5, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(6, item)
        self.MBI_table.setRowHeight(6, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(7, item)
        self.MBI_table.setRowHeight(7, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(8, item)
        self.MBI_table.setRowHeight(8, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(9, item)
        self.MBI_table.setRowHeight(9, 60)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setVerticalHeaderItem(10, item)
        self.MBI_table.setRowHeight(10, 60)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(0, item)  # 列
        self.MBI_table.setColumnWidth(0, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(1, item)
        self.MBI_table.setColumnWidth(1, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(2, item)
        self.MBI_table.setColumnWidth(2, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(3, item)
        self.MBI_table.setColumnWidth(3, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(4, item)
        self.MBI_table.setColumnWidth(4, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setHorizontalHeaderItem(5, item)
        self.MBI_table.setColumnWidth(5, 208)
        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setColumnWidth(6, 208)
        self.MBI_table.setHorizontalHeaderItem(6, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 0, item)

        item = QtWidgets.QTableWidgetItem('0')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(0, 5, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 0, item)

        item = QtWidgets.QTableWidgetItem('0')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 1, item)

        item = QtWidgets.QTableWidgetItem('1')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 2, item)

        item = QtWidgets.QTableWidgetItem('3')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 3, item)

        item = QtWidgets.QTableWidgetItem('4')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 4, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(1, 5, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(2, 0, item)

        item = QtWidgets.QTableWidgetItem('0')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(2, 1, item)

        item = QtWidgets.QTableWidgetItem('1')
        item.setCheckState(Qt.Unchecked)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.MBI_table.setItem(2, 2, item)

        item = QtWidgets.QTableWidgetItem('3')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(2, 3, item)

        item = QtWidgets.QTableWidgetItem('4')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(2, 4, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(2, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(3, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(3, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(3, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(3, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(3, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(3, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(4, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(4, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(4, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(4, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(4, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(4, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(5, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(5, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(5, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(5, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(5, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(5, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(6, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(6, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(6, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(6, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(6, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(6, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(7, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(7, 1, item)

        item = QtWidgets.QTableWidgetItem('3')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(7, 2, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(7, 3, item)

        item = QtWidgets.QTableWidgetItem('12')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(7, 4, item)

        item = QtWidgets.QTableWidgetItem('15')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(7, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(8, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(8, 1, item)

        item = QtWidgets.QTableWidgetItem('3')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(8, 2, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(8, 3, item)

        item = QtWidgets.QTableWidgetItem('12')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(8, 4, item)

        item = QtWidgets.QTableWidgetItem('15')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(8, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(9, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(9, 1, item)

        item = QtWidgets.QTableWidgetItem('1')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(9, 2, item)

        item = QtWidgets.QTableWidgetItem('3')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(9, 3, item)

        item = QtWidgets.QTableWidgetItem('4')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(9, 4, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(9, 5, item)

        item = QtWidgets.QTableWidgetItem()
        self.MBI_table.setItem(10, 0, item)
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

        item = QtWidgets.QTableWidgetItem('0')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(10, 1, item)

        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(10, 2, item)

        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(10, 3, item)

        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(10, 4, item)

        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        item.setCheckState(Qt.Unchecked)
        self.MBI_table.setItem(10, 5, item)

        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(10, 820, 500, 40))
        self.label_7.setText('注：*表示仅在不能行走时才评定此项')
        self.label_7.setStyleSheet("font:12pt")

        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(40, 870, 500, 40))
        self.label_8.setStyleSheet("font:14pt")

        self.MBI_totalscore = QtWidgets.QLabel(self.page)
        self.MBI_totalscore.setGeometry(QtCore.QRect(120, 870, 200, 40))
        self.MBI_totalscore.setText('--')
        self.MBI_totalscore.setStyleSheet("font:14pt")

        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(600, 870, 500, 40))
        self.label_9.setStyleSheet("font:14pt")

        self.MBI_result = QtWidgets.QComboBox(self.page)
        self.MBI_result.setGeometry(QtCore.QRect(740, 870, 600, 40))
        self.MBI_result.addItems(
            ['', '正常100分', '≥60分，生活基本自理', '41-59分，中度功能障碍，生活需要帮助', '21-40分，重度功能障碍，生活依赖明显', '≤20分， 生活完全依赖'])
        self.MBI_result.setStyleSheet("font:14pt;background:white")

        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(40, 920, 500, 40))
        self.label_10.setText('评定日期:')
        self.label_10.setStyleSheet("font:14pt")

        self.MBI_dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.page)
        self.MBI_dateEdit.setGeometry(QtCore.QRect(180, 920, 200, 40))
        self.MBI_dateEdit.setCalendarPopup(True)
        self.MBI_dateEdit.setStyleSheet("font:14pt;background:white")

        self.MBI_saveButton = QtWidgets.QPushButton(self.page)
        self.MBI_saveButton.setGeometry(QtCore.QRect(400, 920, 120, 40))
        self.MBI_saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.MBI_downloadButton = QtWidgets.QPushButton(self.page)
        self.MBI_downloadButton.setGeometry(QtCore.QRect(540, 920, 120, 40))
        self.MBI_downloadButton.setText('导出')
        self.MBI_downloadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")
        self.stackedWidget.addWidget(self.page)

        self.page_2=QtWidgets.QWidget()

        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(500, 10, 400, 41))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setStyleSheet('font:16pt')

        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label_12.setStyleSheet('font:14pt')

        self.FIM_name = QtWidgets.QLabel(self.page_2)
        self.FIM_name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.FIM_name.setStyleSheet('font:14pt')

        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_13.setStyleSheet('font:14pt')

        self.FIM_gender = QtWidgets.QLabel(self.page_2)
        self.FIM_gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.FIM_gender.setStyleSheet('font:14pt')

        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_14.setStyleSheet('font:14pt')

        self.FIM_age = QtWidgets.QLabel(self.page_2)
        self.FIM_age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.FIM_age.setStyleSheet('font:14pt')

        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_15.setStyleSheet('font:14pt')

        self.FIM_hand = QtWidgets.QLabel(self.page_2)
        self.FIM_hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.FIM_hand.setStyleSheet('font:14pt')

        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(830,60, 260, 40))
        self.label_16.setStyleSheet("font:14pt")

        self.FIM_dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.page_2)
        self.FIM_dateEdit.setGeometry(QtCore.QRect(950, 60, 200, 40))
        self.FIM_dateEdit.setStyleSheet("font:14pt;background:white")
        self.FIM_dateEdit.setCalendarPopup(True)

        self.FIM_saveButton = QtWidgets.QPushButton(self.page_2)
        self.FIM_saveButton.setGeometry(QtCore.QRect(1170, 60, 120, 40))
        self.FIM_saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.FIM_downLoadButton = QtWidgets.QPushButton(self.page_2)
        self.FIM_downLoadButton.setGeometry(QtCore.QRect(1320, 60, 120, 40))
        self.FIM_downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.FIM_table = QtWidgets.QTableWidget(self.page_2)
        self.FIM_table.setGeometry(QtCore.QRect(20, 120, 1460, 350))
        self.FIM_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FIM_table.setStyleSheet('background:white;font:14pt')
        self.FIM_table.setColumnCount(5)
        self.FIM_table.setRowCount(22)
        self.FIM_table.verticalHeader().setVisible(False)
        self.FIM_table.horizontalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.FIM_table.setHorizontalHeaderItem(0, item)  # 列
        self.FIM_table.setColumnWidth(0, 220)
        item = QtWidgets.QTableWidgetItem()
        self.FIM_table.setHorizontalHeaderItem(1, item)
        self.FIM_table.setColumnWidth(1, 280)
        item = QtWidgets.QTableWidgetItem()
        self.FIM_table.setHorizontalHeaderItem(2, item)
        self.FIM_table.setColumnWidth(2, 208)
        item = QtWidgets.QTableWidgetItem()
        self.FIM_table.setHorizontalHeaderItem(3, item)
        self.FIM_table.setColumnWidth(3, 408)
        item = QtWidgets.QTableWidgetItem()
        self.FIM_table.setHorizontalHeaderItem(4, item)
        self.FIM_table.setColumnWidth(4, 308)

        item = QtWidgets.QTableWidgetItem('项目')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(0, 0, item)
        self.FIM_table.setSpan(0,0,1,4)
        item = QtWidgets.QTableWidgetItem('得分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('运动功能')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(1, 0, item)
        self.FIM_table.setSpan(1, 0, 14, 1)
        item = QtWidgets.QTableWidgetItem('自理能力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(1, 1, item)
        self.FIM_table.setSpan(1,1, 6, 1)
        item = QtWidgets.QTableWidgetItem('1')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem('2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem('3')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem('4')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem('5')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem('6')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem('进食')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem('梳洗修饰')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem('洗澡')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem('穿裤子')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem('穿上衣')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem('上厕所')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem('括约肌控制')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(7, 1, item)
        self.FIM_table.setSpan(7, 1, 2, 1)
        item = QtWidgets.QTableWidgetItem('7')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem('8')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem('膀胱管理')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem('直肠管理')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem('转移')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(9, 1, item)
        self.FIM_table.setSpan(9, 1, 3, 1)
        item = QtWidgets.QTableWidgetItem('9')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem('10')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem('11')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem('床、椅、轮椅间')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem('入厕')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem('盆浴或淋浴')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem('行走')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(12, 1, item)
        self.FIM_table.setSpan(12, 1, 2, 1)
        item = QtWidgets.QTableWidgetItem('12')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem('13')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem('步行/轮椅')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem('上下楼梯')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem('运动功能评分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(14, 1, item)
        self.FIM_table.setSpan(14, 1, 1, 3)

        item = QtWidgets.QTableWidgetItem('认知功能')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(15, 0, item)
        self.FIM_table.setSpan(15, 0, 6,1)
        item = QtWidgets.QTableWidgetItem('交流')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(15, 1, item)
        self.FIM_table.setSpan(15, 1, 2, 1)
        item = QtWidgets.QTableWidgetItem('14')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem('15')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem('理解')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem('表达')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem('社会认知')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(17, 1, item)
        self.FIM_table.setSpan(17, 1, 3, 1)
        item = QtWidgets.QTableWidgetItem('16')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem('17')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem('18')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem('社会交往')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem('解决问题')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem('记忆')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(19, 3, item)
        item = QtWidgets.QTableWidgetItem('认知功能评分');
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(20, 1, item)
        self.FIM_table.setSpan(20, 1, 1, 3)

        item = QtWidgets.QTableWidgetItem('FIM 总分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(21, 0, item)
        self.FIM_table.setSpan(21, 0, 1, 4)

        item = QtWidgets.QTableWidgetItem('评估人')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.FIM_table.setItem(21, 0, item)
        self.FIM_table.setSpan(21, 0, 1, 4)

        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(20, 480, 1460, 500))
        self.label_17.setStyleSheet("font:12pt")
        self.label_17.setWordWrap(True)

        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.stackedWidget.setCurrentIndex(0)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "日常生活能力评定"))
        self.label.setText(_translate("MainWindow", "日常生活能力评定"))
        self.MBI_saveButton.setText(_translate("MainWindow", "保存"))
        self.label_8.setText(_translate("MainWindow", "总分:"))
        self.label_9.setText(_translate("MainWindow", "评定结果:"))
        self.label_2.setText(_translate("MainWindow", "姓名:"))
        self.label_3.setText(_translate("MainWindow", "性别:"))
        self.label_4.setText(_translate("MainWindow", "年龄:"))
        self.label_5.setText(_translate("MainWindow", "患手:"))
        self.label_6.setText(_translate("MainWindow", "改良Barthel指数（MBI）"))
        item = self.MBI_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ADL项目"))
        item = self.MBI_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "完全依赖1级"))
        item = self.MBI_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最大帮助2级"))
        item = self.MBI_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "中等帮助3级"))
        item = self.MBI_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "最小帮助4级"))
        item = self.MBI_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "完全独立5级"))
        item = self.MBI_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "得分"))
        __sortingEnabled = self.MBI_table.isSortingEnabled()
        self.MBI_table.setSortingEnabled(False)
        item = self.MBI_table.item(0, 0)
        item.setText(_translate("MainWindow", "进   食"))
        item = self.MBI_table.item(1, 0)
        item.setText(_translate("MainWindow", "洗   澡"))
        item = self.MBI_table.item(2, 0)
        item.setText(_translate("MainWindow", "个人卫生"))
        item = self.MBI_table.item(3, 0)
        item.setText(_translate("MainWindow", "穿   衣"))
        item = self.MBI_table.item(4, 0)
        item.setText(_translate("MainWindow", "大便控制"))
        item = self.MBI_table.item(5, 0)
        item.setText(_translate("MainWindow", "小便控制"))
        item = self.MBI_table.item(6, 0)
        item.setText(_translate("MainWindow", "用   厕"))
        item = self.MBI_table.item(7, 0)
        item.setText(_translate("MainWindow", "床椅转移"))
        item = self.MBI_table.item(8, 0)
        item.setText(_translate("MainWindow", "平地行走"))
        item = self.MBI_table.item(9, 0)
        item.setText(_translate("MainWindow", "坐轮椅*"))
        item = self.MBI_table.item(10, 0)
        item.setText(_translate("MainWindow", "上下楼梯"))
        self.label_11.setText(_translate("MainWindow", "功能独立性测评（FIM）"))
        self.label_12.setText(_translate("MainWindow", "姓名:"))
        self.FIM_name.setText(_translate("MainWindow", "--"))
        self.label_13.setText(_translate("MainWindow", "性别:"))
        self.FIM_gender.setText(_translate("MainWindow", "--"))
        self.label_14.setText(_translate("MainWindow", "年龄:"))
        self.FIM_age.setText(_translate("MainWindow", "--"))
        self.label_15.setText(_translate("MainWindow", "患手:"))
        self.FIM_hand.setText(_translate("MainWindow", "--"))
        self.label_17.setText(_translate("MainWindow", "功能水平和评分标准：\r\n1、独立：活动中不需他人帮助。\r\n完全独立（7 分）-- 构成活动的所有作业均能规范、完全地完成，不需修改和辅助设备或用品，并在合理的时间内完成\r\n\
        有条件的独立（6分）-- 具有下列一项或几项：活动中需要辅助设备；活动需要比正常长的时间；或需要安全方面的考虑\r\n2、依赖：为了进行活动，患者需要另一个人予以监护或身体的接触性帮助，或者不进行活动。\r\n有条件的依赖--患者付出50%或更多的努力，其所需的辅助水平如下：\r\n\
        （1） 监护和准备（5 分）-- 患者所需的帮助只限于备用、提示或劝告，帮助者和患者之间没有身体的\r\n接触或帮助者仅需要帮助准备必需用品；或帮助带上矫形器。\r\n\
        （2）少量身体接触的帮助（4 分）-- 患者所需的帮助只限于轻轻接触，自己能付出75%或以上的努力。\r\n（3）中度身体接触的帮助（3 分）-- 患者需要中度的帮助，自己能付出50%~75%的努力。\r\n\
        完全依赖 -- 患者需要一半以上的帮助或完全依赖他人，否则活动就不能进行。\r\n（1）大量身体接触的帮助（2 分）-- 患者付出的努力小于50%，但大于25%。\r\n（2）完全依赖（1 分）-- 患者付出的努力小于25%。\r\n\
        FIM 的最高分为126 分（运动功能评分91 分，认知功能评分35 分），最低分18 分。126 分=完全独立；108 分~125 分=基本独立；90~107 分=有条件的独立或极轻度依赖；72~89 分轻度依赖；54~71 分中度依赖；36~53 分=重度依赖；19~35 分=极重度依赖；18 分=完全依赖。"))
        self.label_16.setText(_translate("MainWindow", "评定日期:"))
        self.FIM_saveButton.setText(_translate("MainWindow", "保存"))
        self.FIM_downLoadButton.setText(_translate("MainWindow", "导出"))


class DailyLivingAbilityAssessment(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, patient_id):
        super(DailyLivingAbilityAssessment, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']

        self.MBI_name.setText(self.patientInfo['name'])
        self.MBI_age.setText(str(self.patientInfo['age']))
        self.MBI_gender.setText(self.patientInfo['sex'])
        self.MBI_hand.setText(self.patientInfo['illness'])

        self.FIM_name.setText(self.patientInfo['name'])
        self.FIM_age.setText(str(self.patientInfo['age']))
        self.FIM_gender.setText(self.patientInfo['sex'])
        self.FIM_hand.setText(self.patientInfo['illness'])

        self.totalComBox.currentIndexChanged.connect(self.totalComBoxClick)
        self.MBI_saveButton.clicked.connect(self.MBI_saveButtonClick)
        self.MBI_downloadButton.clicked.connect(self.MBI_downloadButtonClick)
        self.FIM_saveButton.clicked.connect(self.FIM_saveButtonClick)
        self.FIM_downLoadButton.clicked.connect(self.FIM_downLoadButtonClick)

    def totalComBoxClick(self, *args):
        if(self.totalComBox.currentIndex()==1):
            self.stackedWidget.setCurrentIndex(0)
        else:
            self.stackedWidget.setCurrentIndex(1)

    def MBI_saveButtonClick(self, *args):
        code_1 = self.MBI_totalscore.text()
        code_2 = self.MBI_result.currentText()
        test_date = self.MBI_dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'code_1': code_1, 'code_2': code_2,
                 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def MBI_downloadButtonClick(self, *args):
        self.MBI_saveButton.hide()
        self.MBI_downloadButton.hide()
        img = self.grab()
        self.MBI_saveButton.show()
        self.MBI_downloadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(
            f"{path}/{self.MBI_name.text()}_{self.MBI_dateEdit.text().replace('/', '-')}_{self.totalComBox.currentText()}.png")
        ...

    def FIM_saveButtonClick(self, *args):
        test_date = self.FIM_dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def FIM_downLoadButtonClick(self, *args):
        self.FIM_saveButton.hide()
        self.FIM_downLoadButton.hide()
        img = self.grab()
        self.FIM_saveButton.show()
        self.FIM_downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(
            f"{path}/{self.FIM_name.text()}_{self.FIM_dateEdit.text().replace('/', '-')}_{self.totalComBox.currentText()}.png")
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = DailyLivingAbilityAssessment()
    gui.show()
    sys.exit(app.exec_())


