# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '22.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import sys

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, Qt
from PyQt5.QtWidgets import QFileDialog, QMessageBox

import config
import tool


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(300, 10, 900, 41))
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setStyleSheet('font:16pt')

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label.setStyleSheet('font:14pt')

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.name.setStyleSheet('font:14pt')

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_2.setStyleSheet('font:14pt')

        self.gender = QtWidgets.QLabel(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.gender.setStyleSheet('font:14pt')

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.age.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.hand = QtWidgets.QLabel(self.centralwidget)
        self.hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.hand.setStyleSheet('font:14pt')

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 120, 1460, 700))
        self.table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table.setStyleSheet('background:white;font:14pt')
        self.table.setColumnCount(5)
        self.table.setRowCount(23)
        self.table.verticalHeader().setVisible(False)
        self.table.horizontalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)  # 列
        self.table.setColumnWidth(0, 120)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.setColumnWidth(1, 680)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.setColumnWidth(2, 208)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.setColumnWidth(3, 208)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.setColumnWidth(4, 208)

        item = QtWidgets.QTableWidgetItem('项目')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 0, item)
        self.table.setSpan(0,0,1,2)
        item = QtWidgets.QTableWidgetItem('评分标准')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem('评分1')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem('评分2')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 4, item)

        item = QtWidgets.QTableWidgetItem('定向力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 0, item)
        self.table.setSpan(1, 0,2, 1)
        item = QtWidgets.QTableWidgetItem('现在是(哪一年) (什么季节) (几月) (几号) (星期几)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem('我们现在在哪里(哪个国家)(哪个城市)(哪个城区) (哪个医院)(第几层楼)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2, 2, item)

        item = QtWidgets.QTableWidgetItem('记忆力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 0, item)
        self.table.setSpan(3, 0, 2, 1)
        self.table.setRowHeight(3,100)
        item = QtWidgets.QTableWidgetItem('现在我要说出三样东西的名称，在我讲完之后，请您重复说一遍。请您记出这三样东西，因为几分钟后还要再问您。(请仔细说清楚，每一样东西一秒钟)。\
“皮球”“国旗”“树木”')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem('请你把这三样东西说一遍(以第一次答案计分)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem('3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 2, item)
        self.table.setSpan(3,2,2,1)
        self.table.setSpan(3, 3, 2, 1)
        self.table.setSpan(3, 4, 2, 1)

        item = QtWidgets.QTableWidgetItem('注意力和计算力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 0, item)
        self.table.setRowHeight(5, 160)
        item = QtWidgets.QTableWidgetItem('请你算一算100减去7，然后从所得的数目再减去7，如此一直计算下去，请你将每减一个7后的答案告诉我，直到我说“停”为止。(若错了，但下一个答案是对的，那么只记一次错误) \
93…，86…，79…，72…，65…')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem('5分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 2, item)

        item = QtWidgets.QTableWidgetItem('回忆力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 0, item)
        self.table.setRowHeight(6, 80)
        item = QtWidgets.QTableWidgetItem('现在请您说出刚才我让您记住的那三样东西？“皮球”“国旗”“树木”（首次重复的答案）')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem('3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 2, item)

        item = QtWidgets.QTableWidgetItem('语言能力')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 0, item)
        self.table.setSpan(7, 0, 15, 1)
        self.table.setSpan(7, 2, 3, 1)
        self.table.setSpan(7, 3, 3, 1)
        self.table.setSpan(7, 4, 3, 1)
        self.table.setSpan(10, 2, 3, 1)
        self.table.setSpan(10, 3, 3, 1)
        self.table.setSpan(10, 4, 3, 1)
        self.table.setSpan(13, 2, 3, 1)
        self.table.setSpan(13, 3, 3, 1)
        self.table.setSpan(13, 4, 3, 1)
        self.table.setSpan(17, 2, 3, 1)
        self.table.setSpan(17, 3, 3, 1)
        self.table.setSpan(17, 4, 3, 1)
        item = QtWidgets.QTableWidgetItem('命名能力')
        self.table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem('每项1分，共2分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem(' （出示手表）这个东西叫什么？')
        self.table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem(' （出示铅笔）这个东西叫什么？')
        self.table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem('复述能力')
        self.table.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem('     现在我要说一句话，请您跟着我清楚地重复一遍。')
        self.table.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem('     “四十四只石狮子”')
        self.table.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem('阅读能力')
        self.table.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem('     请您念一念这句话，并按照上面的意思去做。')
        self.table.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem('     “闭上您的眼睛”')
        self.table.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem('我给您一张纸，请您按我说的去做，现在开始：“用右手拿着这张纸，用两只手将它对折起来，放在您的大腿上”（不要重复说明，也不要示范）')
        self.table.setItem(16, 1, item)
        self.table.setRowHeight(16,120)
        item = QtWidgets.QTableWidgetItem('每个动作1分，共3分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem('书写能力')
        self.table.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem('     请您给我写一个完整的句子（须有意义，有主语和动词），记下所叙述句子的全文')
        self.table.setItem(18, 1, item)
        self.table.setRowHeight(18,100)
        self.table.setRowHeight(19, 200)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem('结构能力')
        self.table.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem('1分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem('     这是一张图，请您在同一张纸上照样把它画下来。（对：两个五边形的图案，交叉处有个小四边形，得1分）')
        self.table.setItem(21, 1, item)
        self.table.setRowHeight(21, 80)
        item = QtWidgets.QTableWidgetItem('得分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(22, 0, item)
        self.table.setWordWrap(True)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 840, 260, 40))
        self.label_6.setStyleSheet("font:16pt")

        self.dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 840, 260, 40))
        self.dateEdit.setStyleSheet("font:16pt;background:white")
        self.dateEdit.setCalendarPopup(True)

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(450, 840, 120, 40))
        self.saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.downLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downLoadButton.setGeometry(QtCore.QRect(590, 840, 120, 40))
        self.downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简易智力状态检查量表（MMSE）"))
        self.title.setText(_translate("MainWindow", "简易认知功能检查 (Mini-Mental State Examination, MMSE)"))
        self.label.setText(_translate("MainWindow", "姓名:"))
        self.name.setText(_translate("MainWindow", "--"))
        self.label_2.setText(_translate("MainWindow", "性别:"))
        self.gender.setText(_translate("MainWindow", "--"))
        self.label_3.setText(_translate("MainWindow", "年龄:"))
        self.age.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "患手:"))
        self.hand.setText(_translate("MainWindow", "--"))
        self.label_6.setText(_translate("MainWindow", "评定日期:"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.downLoadButton.setText(_translate("MainWindow", "导出"))

class MMSE(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, patient_id):
        super(MMSE, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']

        self.name.setText(self.patientInfo['name'])
        self.age.setText(str(self.patientInfo['age']))
        self.gender.setText(self.patientInfo['sex'])
        self.hand.setText(self.patientInfo['illness'])
        self.saveButton.clicked.connect(self.saveButtonClick)
        self.downLoadButton.clicked.connect(self.downLoadButtonClick)

        #

    def saveButtonClick(self, *args):
        test_date = self.dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def downLoadButtonClick(self, *args):
        self.saveButton.hide()
        self.downLoadButton.hide()
        img = self.grab()
        self.saveButton.show()
        self.downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.name.text()}_{self.dateEdit.text().replace('/', '-')}.png")
        ...

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = MMSE()
    gui.show()
    sys.exit(app.exec_())

