# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '20uipy.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import sys

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QDate
from PyQt5.QtWidgets import QFileDialog, QMessageBox

import config
import tool


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color:rgb(242, 249, 255)')

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(450, 10, 600, 41))
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setStyleSheet('font:16pt')

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 200, 40))
        self.label.setStyleSheet('font:14pt')

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 60, 200, 40))
        self.name.setStyleSheet('font:14pt')

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 200, 40))
        self.label_2.setStyleSheet('font:14pt')

        self.gender = QtWidgets.QLabel(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(360, 60, 200, 40))
        self.gender.setStyleSheet('font:14pt')

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 60, 200, 40))
        self.label_3.setStyleSheet('font:14pt')

        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(560, 60, 200, 40))
        self.age.setStyleSheet('font:14pt')

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 200, 40))
        self.label_4.setStyleSheet('font:14pt')

        self.hand = QtWidgets.QLabel(self.centralwidget)
        self.hand.setGeometry(QtCore.QRect(760, 60, 200, 40))
        self.hand.setStyleSheet('font:14pt')

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 120, 1460, 430))
        self.table.setStyleSheet('background:white;font:14pt')
        self.table.setColumnCount(2)
        self.table.setRowCount(18)
        self.table.verticalHeader().setVisible(False)
        self.table.horizontalHeader().setVisible(False)

        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)  # 列
        self.table.setColumnWidth(0, 740)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.setColumnWidth(1, 680)

        item = QtWidgets.QTableWidgetItem('项目内容')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem('评分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(0, 1, item)

        item = QtWidgets.QTableWidgetItem('前臂放到桌子(侧面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(1, 0, item)

        item = QtWidgets.QTableWidgetItem('前臂由桌子放到盒子f侧面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(2, 0, item)

        item = QtWidgets.QTableWidgetItem('前臂放到桌子(侧面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem('在桌面上伸肘(侧面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem('在桌面有负荷伸尉(侧面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem('手放到桌子(正面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem('手由桌子放到盒子(正面)')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem('在桌面屈肘拉回O.45kg的物体')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem('拿起易拉罐到嘴边')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem('从桌面上拿起铅笔')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem('从桌面拿起曲别针')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem('叠放3个棋子')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem('翻转3张纸牌')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem('在锁中转动钥匙')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem('叠毛巾')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem('提1.35kg篮子到旁边桌子上')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem('总分')
        item.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.table.setItem(17, 0, item)


        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 550, 1460,100))
        self.label_5.setStyleSheet("font:12pt")
        self.label_5.setWordWrap(True)

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 640, 1460, 50))
        self.label_7.setStyleSheet("font:12pt")
        self.label_7.setWordWrap(True)

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 690, 1460, 50))
        self.label_8.setStyleSheet("font:12pt")
        self.label_8.setWordWrap(True)

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 740, 1460,60))
        self.label_9.setStyleSheet("font:12pt")
        self.label_9.setWordWrap(True)

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 800, 1460, 50))
        self.label_10.setStyleSheet("font:12pt")
        self.label_10.setWordWrap(True)

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 840, 1460, 50))
        self.label_11.setStyleSheet("font:12pt")
        self.label_11.setWordWrap(True)

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 880, 1460, 50))
        self.label_12.setStyleSheet("font:12pt")
        self.label_12.setWordWrap(True)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 940, 260, 40))
        self.label_6.setStyleSheet("font:16pt")

        self.dateEdit = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 940, 260, 40))
        self.dateEdit.setStyleSheet("font:16pt;background:white")
        self.dateEdit.setCalendarPopup(True)

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(450, 940, 120, 40))
        self.saveButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        self.downLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downLoadButton.setGeometry(QtCore.QRect(590, 940, 120, 40))
        self.downLoadButton.setStyleSheet("background-color:rgb(1, 144, 202);font:12pt;color:white")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WOLF运动功能测试"))
        self.title.setText(_translate("MainWindow", "WOLF运动功能评价量表（WMFT）"))
        self.label.setText(_translate("MainWindow", "姓名:"))
        self.name.setText(_translate("MainWindow", "--"))
        self.label_2.setText(_translate("MainWindow", "性别:"))
        self.gender.setText(_translate("MainWindow", "--"))
        self.label_3.setText(_translate("MainWindow", "年龄:"))
        self.age.setText(_translate("MainWindow", "--"))
        self.label_4.setText(_translate("MainWindow", "患手:"))
        self.hand.setText(_translate("MainWindow", "--"))
        self.label_5.setText(_translate("MainWindow", "WMFT由15个项目组成．1—6为简单的关节运动．7一15为复合的功能动作(表1)。对所有动作当场进行计时和动作质量打分(O一5分，6个分级)，目前该量表的评价手册还没有进行汉化，以下是评测项目和评分标准。WMFT功能能力评分："))
        self.label_6.setText(_translate("MainWindow", "评定日期:"))
        self.label_7.setText(_translate("MainWindow", "0分：所测试的上肢没有尝试参与测试"))
        self.label_8.setText(_translate("MainWindow", "1分：所测试的上肢没有功能性的参与但试图参加．在单侧动作的测试中．未被测试的上肢有可能帮助测试上肢。"))
        self.label_9.setText(_translate("MainWindow", "2分：所测试的上肢参与测试并完成任务．但需要未测试上肢的帮助．如小的调整或变换位置．或需要2次尝试才能完成任务．或完成任务非常慢。在双侧任务中，被测试上肢功能损害非常严重。只能作为辅助。"))
        self.label_10.setText(_translate("MainWindow", "3分：所测试的上肢参与测试并完成任务．但是动作受到协同运动的一些影响。或动作完成较慢及需要努力才能完成。"))
        self.label_11.setText(_translate("MainWindow", "4分：所测试的上肢参与测试并完成任务，动作接近正常．但是完成速度轻度变慢，或缺乏精确度．良好的协调和流畅性。"))
        self.label_12.setText(_translate("MainWindow", "5分：所测试的上肢参与测试并完成任务．表现为正常动作。以健侧上肢动作为正常标准。"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.downLoadButton.setText(_translate("MainWindow", "导出"))


class WOLF(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self,patient_id):
        super(WOLF, self).__init__()
        self.setupUi(self)
        self.patient_id = patient_id

        self.patientInfo = \
            json.loads(requests.post(config.patientGetById, data={'id': self.patient_id}).content.decode('utf-8'))[
                'data']

        self.name.setText(self.patientInfo['name'])
        self.age.setText(str(self.patientInfo['age']))
        self.gender.setText(self.patientInfo['sex'])
        self.hand.setText(self.patientInfo['illness'])
        self.saveButton.clicked.connect(self.saveButtonClick)
        self.downLoadButton.clicked.connect(self.downLoadButtonClick)
    #
    def saveButtonClick(self, *args):
        test_date = self.dateEdit.text().replace('/', '-')
        sheet = {'id': tool.Tools.getTimeStamp(), 'patient_id': self.patient_id, 'test_date': test_date}
        res = requests.post(config.ashworthInsert, data=sheet)
        QMessageBox.information(self, "保存", '保存成功', QMessageBox.Yes, QMessageBox.Yes)
        ...

    def downLoadButtonClick(self, *args):
        self.saveButton.hide()
        self.downLoadButton.hide()
        img = self.grab()
        self.saveButton.show()
        self.downLoadButton.show()
        path = QFileDialog.getExistingDirectory()
        img.save(f"{path}/{self.name.text()}_{self.dateEdit.text().replace('/', '-')}.png")
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = WOLF()
    gui.show()
    sys.exit(app.exec_())