# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Formuntitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets


# 病人信息-高级查询界面

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 1080)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1400, 1080))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.userNameLabel = QtWidgets.QLabel(self.frame)
        self.userNameLabel.setGeometry(QtCore.QRect(10, 10, 100, 40))
        self.userNameLabel.setStyleSheet("font:12pt")

        self.userNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.userNameLineEdit.setGeometry(QtCore.QRect(70, 15, 120, 35))
        self.userNameLineEdit.setStyleSheet("background:white;font:12pt")

        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 100, 40))  # 性别
        self.label_3.setStyleSheet("font:12pt")

        self.sexComboBox = QtWidgets.QComboBox(self.frame)
        self.sexComboBox.setGeometry(QtCore.QRect(290, 15, 120, 35))
        self.sexComboBox.setStyleSheet("background:white;font:12pt")
        self.sexComboBox.addItems(['', '男', '女'])

        self.label_2 = QtWidgets.QLabel(self.frame)  # 年龄
        self.label_2.setGeometry(QtCore.QRect(440, 10, 100, 40))
        self.label_2.setStyleSheet("font:12pt")

        self.ageLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ageLineEdit.setGeometry(QtCore.QRect(510, 15, 120, 35))
        self.ageLineEdit.setStyleSheet("background:white;font:12pt")

        self.label_4 = QtWidgets.QLabel(self.frame)  # 电话
        self.label_4.setGeometry(QtCore.QRect(650, 10, 60, 40))
        self.label_4.setStyleSheet("font:12pt")

        self.telpLineEdit = QtWidgets.QLineEdit(self.frame)
        self.telpLineEdit.setGeometry(QtCore.QRect(720, 15, 250, 35))
        self.telpLineEdit.setStyleSheet("background:white;font:12pt")

        self.label_9 = QtWidgets.QLabel(self.frame)  # 利手
        self.label_9.setGeometry(QtCore.QRect(980, 10, 100, 40))
        self.label_9.setStyleSheet("font:12pt")

        self.healtComboBox = QtWidgets.QComboBox(self.frame)
        self.healtComboBox.setGeometry(QtCore.QRect(1040, 15, 120, 35))
        self.healtComboBox.setStyleSheet("background:white;font:12pt")
        self.healtComboBox.addItems(['', '左', '右'])

        self.label_10 = QtWidgets.QLabel(self.frame)  # 患手
        self.label_10.setGeometry(QtCore.QRect(1190, 10, 100, 40))
        self.label_10.setStyleSheet("font:12pt;")

        self.unhealthComboBox = QtWidgets.QComboBox(self.frame)
        self.unhealthComboBox.setGeometry(QtCore.QRect(1250, 15, 120, 35))
        self.unhealthComboBox.setStyleSheet("background:white;font:12pt")
        self.unhealthComboBox.addItems(['', '左', '右'])

        self.label = QtWidgets.QLabel(self.frame)  # 疾病类型
        self.label.setGeometry(QtCore.QRect(10, 65, 100, 40))
        self.label.setStyleSheet("font:12pt")

        self.diseaseTypeComboBox = QtWidgets.QComboBox(self.frame)
        self.diseaseTypeComboBox.setGeometry(QtCore.QRect(120, 70, 200, 35))
        self.diseaseTypeComboBox.addItems(['', '脑卒中', '脑外伤', '颅脑损伤', '周围神经损伤', '乳腺癌术后', '疼痛', '认知障碍', '脊髓损伤', '自定义'])
        self.diseaseTypeComboBox.setStyleSheet("background:white;font:12pt")

        self.patientInformation_diseaseTypeFrame1 = QtWidgets.QFrame(self.frame)
        self.patientInformation_diseaseTypeFrame1.setGeometry(QtCore.QRect(330, 70, 200, 35))
        self.patientInformation_diseaseTypeFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patientInformation_diseaseTypeFrame1.setFrameShadow(QtWidgets.QFrame.Raised)

        self.diseaseTypeComboBox_2 = QtWidgets.QComboBox(self.patientInformation_diseaseTypeFrame1)
        self.diseaseTypeComboBox_2.setGeometry(QtCore.QRect(0, 0, 200, 35))
        self.diseaseTypeComboBox_2.addItems(['', '脑梗死', '脑出血'])
        self.diseaseTypeComboBox_2.setStyleSheet("background:white;font:12pt")

        self.patientInformation_diseaseTypeFrame1_2 = QtWidgets.QFrame(self.frame)
        self.patientInformation_diseaseTypeFrame1_2.setGeometry(QtCore.QRect(330, 70, 200, 35))
        self.patientInformation_diseaseTypeFrame1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patientInformation_diseaseTypeFrame1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patientInformation_diseaseTypeFrame1_2.setVisible(False)

        self.patientInformation_diseaseTypeLineEdit = QtWidgets.QLineEdit(self.patientInformation_diseaseTypeFrame1_2)
        self.patientInformation_diseaseTypeLineEdit.setGeometry(QtCore.QRect(0, 0, 200, 35))
        self.patientInformation_diseaseTypeLineEdit.setStyleSheet("font:12pt;background:white")

        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(540, 65, 180, 40))
        self.label_12.setStyleSheet("font:12pt")

        self.burnnComboBox = QtWidgets.QComboBox(self.frame)
        self.burnnComboBox.setGeometry(QtCore.QRect(720, 70, 640, 35))
        self.burnnComboBox.addItems(['', 'Ⅰ-Ⅱ（无或极细微运动）', 'Ⅲ-Ⅳ（全指屈曲或轻微手指伸展）', 'Ⅴ-Ⅵ（拇指运动、伴随意屈伸/手指部分伸展）'])
        self.burnnComboBox.setStyleSheet("background:white;font:12pt")

        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 120, 120, 40))
        self.label_13.setText('认知情况')
        self.label_13.setStyleSheet("font:12pt")

        self.cognititveSituationComboBox = QtWidgets.QComboBox(self.frame)
        self.cognititveSituationComboBox.setGeometry(QtCore.QRect(120, 125, 150, 35))
        self.cognititveSituationComboBox.addItems(['', '优', '良', '差'])
        self.cognititveSituationComboBox.setStyleSheet("font:12pt;background:white")

        self.label_14 = QtWidgets.QLabel(self.frame)  # VAS疼痛评分
        self.label_14.setGeometry(QtCore.QRect(280, 120, 150, 45))
        self.label_14.setStyleSheet("font:12pt")

        self.vasComboBox = QtWidgets.QComboBox(self.frame)
        self.vasComboBox.setGeometry(QtCore.QRect(420, 125, 150, 35))
        self.vasComboBox.addItems(['', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.vasComboBox.setStyleSheet("background:white;font:12pt")

        self.label_15 = QtWidgets.QLabel(self.frame)  # 疼痛部位
        self.label_15.setGeometry(QtCore.QRect(580, 120, 150, 40))
        self.label_15.setStyleSheet("font:12pt")

        self.painfulArealineEdit = QtWidgets.QLineEdit(self.frame)
        self.painfulArealineEdit.setGeometry(QtCore.QRect(680, 125, 700, 35))
        self.painfulArealineEdit.setStyleSheet("background:white;font:12pt")

        self.label_11 = QtWidgets.QLabel(self.frame)  # 病程
        self.label_11.setGeometry(QtCore.QRect(10, 170, 120, 40))
        self.label_11.setStyleSheet("font:12pt")

        self.diseaseProcessComboBox = QtWidgets.QComboBox(self.frame)
        self.diseaseProcessComboBox.setGeometry(QtCore.QRect(80, 175, 300, 35))
        self.diseaseProcessComboBox.addItems(['', '急性期（0-3个月）', '亚急性期（3-6个月）', '慢性期（6个月以上）'])
        self.diseaseProcessComboBox.setStyleSheet("background:white;font:12pt")

        self.label_16 = QtWidgets.QLabel(self.frame)  # 文化程度
        self.label_16.setGeometry(QtCore.QRect(390, 170, 120, 40))
        self.label_16.setText('文化程度')
        self.label_16.setStyleSheet("font:12pt")

        self.educationLevelComboBox = QtWidgets.QComboBox(self.frame)
        self.educationLevelComboBox.setGeometry(QtCore.QRect(490, 175, 150, 35))
        self.educationLevelComboBox.addItems(['', '小学', '初中', '高中', '大学', '无'])
        self.educationLevelComboBox.setStyleSheet("font:12pt;background:white")

        self.label_17 = QtWidgets.QLabel(self.frame)  # 职业
        self.label_17.setGeometry(QtCore.QRect(650, 170, 120, 40))
        self.label_17.setText('职业')
        self.label_17.setStyleSheet("font:12pt")

        self.professionLineEdit = QtWidgets.QLineEdit(self.frame)
        self.professionLineEdit.setGeometry(QtCore.QRect(700, 175, 200, 35))
        self.professionLineEdit.setStyleSheet("font:12pt;background:white")

        self.inquireButton = QtWidgets.QPushButton(self.frame)
        self.inquireButton.setGeometry(QtCore.QRect(910, 175, 150, 40))
        self.inquireButton.setText('查询')
        self.inquireButton.setStyleSheet('font:12pt;background: rgb(0,138,200);color:white')

        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 240, 1340, 830))
        self.tableWidget.setStyleSheet("background:white")

        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(15)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.setColumnWidth(6, 420)

        self.frontButton = QtWidgets.QPushButton(self.frame)
        self.frontButton.setGeometry(QtCore.QRect(30, 1000, 150, 40))
        self.frontButton.setStyleSheet('font:12pt')

        self.previousButton = QtWidgets.QPushButton(Form)
        self.previousButton.setGeometry(QtCore.QRect(190, 1000, 150, 40))
        self.previousButton.setStyleSheet('font:12pt')

        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(350, 1000, 150, 40))
        self.nextButton.setStyleSheet('font:12pt')

        self.lastButton = QtWidgets.QPushButton(Form)
        self.lastButton.setGeometry(QtCore.QRect(510, 1000, 150, 40))
        self.lastButton.setStyleSheet('font:12pt')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.userNameLabel.setText(_translate("Form", "姓名"))
        self.label.setText(_translate("Form", "疾病类型"))
        self.label_2.setText(_translate("Form", "年龄"))
        self.label_3.setText(_translate("Form", "性别"))
        self.label_4.setText(_translate("Form", "电话"))
        self.label_9.setText(_translate("Form", "利手"))
        self.label_10.setText(_translate("Form", "患手"))
        self.label_11.setText(_translate("Form", "病程"))
        self.label_12.setText(_translate("Form", "Brunnstorm分期"))
        self.label_14.setText(_translate("Form", "VAS疼痛评分"))
        self.label_15.setText(_translate("Form", "疼痛部位"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "年龄"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "患手"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "认知情况"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "文化程度"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "疾病类型"))
        self.frontButton.setText(_translate("Form", "首页"))
        self.previousButton.setText(_translate("Form", "上一页"))
        self.nextButton.setText(_translate("Form", "下一页"))
        self.lastButton.setText(_translate("Form", "尾页"))


class AdvancedSearch(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super(AdvancedSearch, self).__init__()
        self.setupUi(self)
        self.inquireButton.mousePressEvent = self.inquireButtonClick
        self.frontButton.mousePressEvent = self.frontButtonClick
        self.nextButton.mousePressEvent = self.nextButtonClick
        self.previousButton.mousePressEvent = self.previousButtonClick
        self.lastButton.mousePressEvent = self.lastClick
        # self.vasComboBox.mousePressEvent = self.vasComboBoxClick
        # self.sexComboBox.mousePressEvent = self.sexComboBoxClick
        # self.healtComboBox.mousePressEvent = self.healtComboBoxClick
        # self.unhealthComboBox.mousePressEvent = self.unhealthComboBoxClick
        self.diseaseTypeComboBox.currentIndexChanged.connect(self.diseaseTypeComboBoxClick)
        # self.diseaseTypeComboBox_2.mousePressEvent = self.diseaseTypeComboBox_2Click
        # self.diseaseProcessComboBox.mousePressEvent = self.diseaseProcessComboBoxClick
        # self.burnnComboBox.mousePressEvent = self.burnnComboBoxClick

    def inquireButtonClick(self, *args):  # 查询
        username = self.userNameLineEdit.getText()  # 获取姓名
        age = self.ageLineEdit.getText()  # 获取年龄
        telp = self.telpLineEdit.getText()  # 获取电话

        ...

    def frontButtonClick(self, *args):  # 首页

        ...

    def previousButtonClick(self, *args):  # 上一页

        ...

    def nextButtonClick(self, *args):  # 下一页

        ...

    def lastClick(self, *args):  # 尾页
        ...

    # def vasComboBoxClick(self, *args):  #VAS疼痛评分
    #     ...
    #
    # def sexComboBoxClick(self, *args):  # 性别
    #     ...
    #
    # def healtComboBoxClick(self, *args):  # 利手
    #     ...
    #
    # def unhealthComboBoxClick(self, *args):  # 患手
    #     ...
    #
    def diseaseTypeComboBoxClick(self, *args):  # 疾病类型选项1
        if (self.diseaseTypeComboBox.currentIndex() == 1 or self.diseaseTypeComboBox.currentIndex() == 3):
            self.patientInformation_diseaseTypeFrame1_2.setVisible(False)  # 疾病类型二级填写容器
            self.patientInformation_diseaseTypeFrame1.setVisible(True)  # 疾病类型二级选项容器
        else:
            self.patientInformation_diseaseTypeFrame1_2.setVisible(True)  # 疾病类型二级填写容器
            self.patientInformation_diseaseTypeFrame1.setVisible(False)  # 疾病类型二级选项容器
        ...

    # def diseaseTypeComboBox_2Click(self, *args):# 疾病类型选项2
    #     ...
    #
    # def diseaseProcessComboBoxClick(self, *args):  # 病程
    #     ...
    #
    # def burnnComboBoxClick(self, *args):  # burnnstorm分期
    #     ...
    #
    #


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = AdvancedSearch()
    gui.show()
    sys.exit(app.exec_())
