# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import requests
from PyQt5 import QtCore, QtWidgets

import config
import tool.Tools


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")

        Form.resize(800, 600)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 5, 800, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setStyleSheet("background:rgb(220, 239, 255)")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 35, 54, 20))
        self.label.setStyleSheet("color:red;font:10pt")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 25, 120, 40))
        self.label_2.setStyleSheet("font:12pt")

        self.loginNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.loginNameLineEdit.setGeometry(QtCore.QRect(180, 25, 300, 40))
        self.loginNameLineEdit.setStyleSheet("background:white;font:12pt")

        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 800, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setStyleSheet("background:rgb(220, 239, 255)")

        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(50, 35, 54, 20))
        self.label_3.setStyleSheet("font:10pt;color:red")

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(60, 25, 120, 40))
        self.label_4.setStyleSheet("font:12pt")

        self.userNameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.userNameLineEdit.setGeometry(QtCore.QRect(180, 25, 300, 40))
        self.userNameLineEdit.setStyleSheet("background:white;font:12pt")

        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 160, 800, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setStyleSheet("background:rgb(220, 239, 255)")

        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(50, 35, 54, 20))
        self.label_5.setStyleSheet("font:10pt;color:red")

        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(60, 25, 120, 40))
        self.label_6.setStyleSheet("font:12pt")

        self.sexComboBox = QtWidgets.QComboBox(self.frame_3)
        self.sexComboBox.setGeometry(QtCore.QRect(180, 25, 300, 40))
        self.sexComboBox.addItems(['', '男', '女'])
        self.sexComboBox.setStyleSheet("background:white;font:12pt")

        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 240, 800, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setStyleSheet("background:rgb(220, 239, 255)")

        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(50, 35, 54, 20))
        self.label_7.setStyleSheet("font:10pt;color:red")

        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(60, 25, 120, 40))
        self.label_8.setStyleSheet("font:12pt")

        self.doctorTypeCombobox = QtWidgets.QComboBox(self.frame_4)
        self.doctorTypeCombobox.setGeometry(QtCore.QRect(180, 25, 300, 40))
        self.doctorTypeCombobox.addItems(['', '主治医生', '普通医生'])
        self.doctorTypeCombobox.setStyleSheet("background:white;font:12pt")

        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(0, 320, 800, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setStyleSheet("background:rgb(220, 239, 255)")

        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(50, 35, 100, 30))
        self.label_9.setStyleSheet("font:12pt")

        self.telLineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.telLineEdit.setGeometry(QtCore.QRect(180, 25, 300, 40))
        self.telLineEdit.setStyleSheet("background:white;font:12pt")

        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(0, 400, 800, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setStyleSheet("background:rgb(220, 239, 255)")

        self.initPasswordCheckbox = QtWidgets.QCheckBox(self.frame_6)
        self.initPasswordCheckbox.setGeometry(QtCore.QRect(50, 35, 160, 20))
        self.initPasswordCheckbox.setStyleSheet("font:12pt")

        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(220, 30, 250, 30))
        self.label_10.setStyleSheet("font:12pt;color:red")

        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(0, 480, 800, 120))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setStyleSheet("background:rgb(220, 239, 255)")

        self.saveButton = QtWidgets.QPushButton(self.frame_7)
        self.saveButton.setGeometry(QtCore.QRect(280, 20, 150, 40))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "*"))
        self.label_2.setText(_translate("Form", "登录名"))
        self.label_3.setText(_translate("Form", "*"))
        self.label_4.setText(_translate("Form", "姓  名"))
        self.label_5.setText(_translate("Form", "*"))
        self.label_6.setText(_translate("Form", "性  别"))
        self.label_7.setText(_translate("Form", "*"))
        self.label_8.setText(_translate("Form", "医生类型"))
        self.label_9.setText(_translate("Form", "电    话"))
        self.initPasswordCheckbox.setText(_translate("Form", "密码初始化"))
        self.label_10.setText(_translate("Form", "初始密码：abc123"))
        self.saveButton.setText(_translate("Form", "保存"))


class addDoctor(QtWidgets.QMainWindow, Ui_Form):  # 基本功能动作训练
    def __init__(self):
        super(addDoctor, self).__init__()
        self.setupUi(self)

        self.saveButton.mousePressEvent = self.saveButtonLeftClick

    def saveButtonLeftClick(self, *args):
        password = 'abc123'
        data = {'id': tool.Tools.getTimeStamp(), 'account': self.loginNameLineEdit.text(), 'password': password,
                'sex': self.sexComboBox.currentText(), 'title': self.doctorTypeCombobox.currentText(),
                'tel': self.telLineEdit.text()}
        res = requests.post(config.userRegister, data=data)
        print(res.text)

    #     self.pushButton_6.click.connect(self.select_all)#全选
    #
    # def select_all(self):


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = addDoctor()
    gui.show()
    sys.exit(app.exec_())
