# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1800, 1200)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 10, 100, 40))
        self.label.setStyleSheet("font:12pt")

        self.trianTimeDateEdit = QtWidgets.QDateEdit(Form)
        self.trianTimeDateEdit.setGeometry(QtCore.QRect(170, 10, 200, 40))

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 240, 40))  # 空间训练参数设置
        self.label_2.setStyleSheet("font:14pt")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 180, 40))
        self.label_3.setStyleSheet("font:12pt")

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(380, 130, 240, 40))
        self.label_4.setStyleSheet("font:12pt")

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(730, 130, 240, 40))
        self.label_5.setStyleSheet("font:12pt")

        self.pictureNum = QtWidgets.QComboBox(Form)
        self.pictureNum.setGeometry(QtCore.QRect(200, 135, 150, 30))

        self.playSpeed = QtWidgets.QComboBox(Form)
        self.playSpeed.setGeometry(QtCore.QRect(540, 135, 150, 30))

        self.selecthard = QtWidgets.QComboBox(Form)
        self.selecthard.setGeometry(QtCore.QRect(830, 135, 150, 30))

        self.baseTraining = QtWidgets.QScrollArea(Form)
        self.baseTraining.setGeometry(QtCore.QRect(40, 260, 830, 800))
        self.baseTraining.setWidgetResizable(True)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setMinimumHeight(1500)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 830, 800))

        font = QtGui.QFont()
        font.setFamily("KaiTi_GB2312")
        font.setPointSize(16)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 比ok
        self.checkBox.setGeometry(QtCore.QRect(10, 5, 160, 80))
        self.checkBox.setFont(font)

        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 比数字
        self.checkBox_2.setGeometry(QtCore.QRect(10, 55, 170, 80))
        self.checkBox_2.setFont(font)

        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 侧捏
        self.checkBox_3.setGeometry(QtCore.QRect(10, 105, 160, 80))
        self.checkBox_3.setFont(font)

        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 尺偏
        self.checkBox_4.setGeometry(QtCore.QRect(10, 155, 150, 80))
        self.checkBox_4.setFont(font)

        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 钩状抓握
        self.checkBox_5.setGeometry(QtCore.QRect(10, 205, 240, 80))
        self.checkBox_5.setFont(font)

        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对食指
        self.checkBox_6.setGeometry(QtCore.QRect(10, 255, 240, 80))
        self.checkBox_6.setFont(font)

        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对四指
        self.checkBox_7.setGeometry(QtCore.QRect(10, 305, 240, 80))
        self.checkBox_7.setFont(font)

        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对小指指跟
        self.checkBox_8.setGeometry(QtCore.QRect(10, 355, 300, 80))
        self.checkBox_8.setFont(font)

        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指环转
        self.checkBox_9.setGeometry(QtCore.QRect(10, 405, 200, 80))
        self.checkBox_9.setFont(font)

        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指外展
        self.checkBox_10.setGeometry(QtCore.QRect(10, 455, 200, 80))
        self.checkBox_10.setFont(font)

        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指屈伸
        self.checkBox_11.setGeometry(QtCore.QRect(10, 505, 200, 80))
        self.checkBox_11.setFont(font)

        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 球状抓握
        self.checkBox_12.setGeometry(QtCore.QRect(10, 555, 200, 80))
        self.checkBox_12.setFont(font)

        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 手指内外收展
        self.checkBox_13.setGeometry(QtCore.QRect(10, 605, 280, 80))
        self.checkBox_13.setFont(font)

        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指单独屈伸
        self.checkBox_14.setGeometry(QtCore.QRect(10, 655, 280, 80))
        self.checkBox_14.setFont(font)

        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指屈伸
        self.checkBox_15.setGeometry(QtCore.QRect(10, 705, 240, 80))
        self.checkBox_15.setFont(font)

        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指伸展
        self.checkBox_16.setGeometry(QtCore.QRect(10, 755, 200, 80))
        self.checkBox_16.setFont(font)

        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 握拳
        self.checkBox_17.setGeometry(QtCore.QRect(10, 805, 200, 80))
        self.checkBox_17.setFont(font)

        self.checkBox_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 掌指关节屈伸 指尖关节伸展_右
        self.checkBox_18.setGeometry(QtCore.QRect(10, 855, 490, 80))
        self.checkBox_18.setFont(font)

        self.checkBox_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 直拳
        self.checkBox_19.setGeometry(QtCore.QRect(10, 905, 160, 80))
        self.checkBox_19.setFont(font)

        self.checkBox_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 柱状抓握
        self.checkBox_20.setGeometry(QtCore.QRect(10, 955, 200, 80))
        self.checkBox_20.setFont(font)

        self.checkBox_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 腕背伸
        self.checkBox_21.setGeometry(QtCore.QRect(10, 1005, 200, 80))
        self.checkBox_21.setFont(font)

        self.checkBox_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋后
        self.checkBox_22.setGeometry(QtCore.QRect(10, 1055, 200, 80))
        self.checkBox_22.setFont(font)

        self.checkBox_23 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋前
        self.checkBox_23.setGeometry(QtCore.QRect(10, 1105, 200, 80))
        self.checkBox_23.setFont(font)

        self.checkBox_24 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋前旋后
        self.checkBox_24.setGeometry(QtCore.QRect(10, 1155, 300, 80))
        self.checkBox_24.setFont(font)

        self.baseTraining.setWidget(self.scrollAreaWidgetContents)

        self.functionTraining = QtWidgets.QScrollArea(Form)
        self.functionTraining.setGeometry(QtCore.QRect(900, 260, 830, 800))
        self.functionTraining.setWidgetResizable(True)

        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setMinimumHeight(1500)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 830, 800))
        font = QtGui.QFont()
        font.setFamily("KaiTi_GB2312")
        font.setPointSize(16)
        self.checkBox_25 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 比ok
        self.checkBox_25.setGeometry(QtCore.QRect(10, 5, 180, 80))
        self.checkBox_25.setFont(font)

        self.checkBox_26 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 比数字
        self.checkBox_26.setGeometry(QtCore.QRect(10, 55, 200, 80))
        self.checkBox_26.setFont(font)

        self.checkBox_27 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 侧捏
        self.checkBox_27.setGeometry(QtCore.QRect(10, 105, 200, 80))
        self.checkBox_27.setFont(font)

        self.checkBox_28 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 尺偏
        self.checkBox_28.setGeometry(QtCore.QRect(10, 155, 200, 80))
        self.checkBox_28.setFont(font)

        self.checkBox_29 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 钩状抓握
        self.checkBox_29.setGeometry(QtCore.QRect(10, 205, 240, 80))
        self.checkBox_29.setFont(font)

        self.checkBox_30 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指对食指
        self.checkBox_30.setGeometry(QtCore.QRect(10, 255, 240, 80))
        self.checkBox_30.setFont(font)

        self.checkBox_31 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指对四指
        self.checkBox_31.setGeometry(QtCore.QRect(10, 305, 240, 80))
        self.checkBox_31.setFont(font)

        self.checkBox_32 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指对小指指跟
        self.checkBox_32.setGeometry(QtCore.QRect(10, 355, 300, 80))
        self.checkBox_32.setFont(font)

        self.checkBox_33 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指环转
        self.checkBox_33.setGeometry(QtCore.QRect(10, 405, 200, 80))
        self.checkBox_33.setFont(font)

        self.checkBox_34 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指外展
        self.checkBox_34.setGeometry(QtCore.QRect(10, 455, 200, 80))
        self.checkBox_34.setFont(font)

        self.checkBox_35 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 拇指屈伸
        self.checkBox_35.setGeometry(QtCore.QRect(10, 505, 200, 80))
        self.checkBox_35.setFont(font)

        self.checkBox_36 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 球状抓握
        self.checkBox_36.setGeometry(QtCore.QRect(10, 555, 200, 80))
        self.checkBox_36.setFont(font)

        self.checkBox_37 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 手指内外收展
        self.checkBox_37.setGeometry(QtCore.QRect(10, 605, 280, 80))
        self.checkBox_37.setFont(font)

        self.checkBox_38 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 四指单独屈伸
        self.checkBox_38.setGeometry(QtCore.QRect(10, 655, 280, 80))
        self.checkBox_38.setFont(font)

        self.checkBox_39 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 四指屈伸
        self.checkBox_39.setGeometry(QtCore.QRect(10, 705, 240, 80))
        self.checkBox_39.setFont(font)

        self.checkBox_40 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 四指伸展
        self.checkBox_40.setGeometry(QtCore.QRect(10, 755, 200, 80))
        self.checkBox_40.setFont(font)

        self.checkBox_41 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 握拳
        self.checkBox_41.setGeometry(QtCore.QRect(10, 805, 200, 80))
        self.checkBox_41.setFont(font)

        self.checkBox_42 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 掌指关节屈伸 指尖关节伸展_右
        self.checkBox_42.setGeometry(QtCore.QRect(10, 855, 490, 80))
        self.checkBox_42.setFont(font)

        self.checkBox_43 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 直拳
        self.checkBox_43.setGeometry(QtCore.QRect(10, 905, 160, 80))
        self.checkBox_43.setFont(font)

        self.checkBox_44 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 柱状抓握
        self.checkBox_44.setGeometry(QtCore.QRect(10, 955, 200, 80))
        self.checkBox_44.setFont(font)

        self.checkBox_45 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 腕背伸
        self.checkBox_45.setGeometry(QtCore.QRect(10, 1005, 200, 80))
        self.checkBox_45.setFont(font)

        self.checkBox_46 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 前臂旋后
        self.checkBox_46.setGeometry(QtCore.QRect(10, 1055, 200, 80))
        self.checkBox_46.setFont(font)

        self.checkBox_47 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 前臂旋前
        self.checkBox_47.setGeometry(QtCore.QRect(10, 1105, 200, 80))
        self.checkBox_47.setFont(font)

        self.checkBox_48 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)  # 前臂旋前旋后
        self.checkBox_48.setGeometry(QtCore.QRect(10, 1155, 300, 80))
        self.checkBox_48.setFont(font)

        self.functionTraining.setWidget(self.scrollAreaWidgetContents_2)

        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 1080, 100, 40))
        self.label_6.setStyleSheet("font:12pt")

        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(900, 1080, 100, 40))
        self.label_7.setStyleSheet("font:12pt")

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 200, 240, 40))
        self.label_8.setStyleSheet("font:14pt")

        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(900, 200, 240, 40))
        self.label_9.setStyleSheet("font:14pt")

        self.baseTrainnumlineEdit = QtWidgets.QLineEdit(Form)
        self.baseTrainnumlineEdit.setGeometry(QtCore.QRect(90, 1080, 150, 40))

        self.functionTrainnumlineEdit = QtWidgets.QLineEdit(Form)
        self.functionTrainnumlineEdit.setGeometry(QtCore.QRect(960, 1080, 150, 40))

        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(260, 1080, 100, 40))
        self.label_10.setStyleSheet("font:12pt")

        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(1120, 1080, 100, 40))
        self.label_11.setStyleSheet("font:12pt")

        self.baseTrainWay = QtWidgets.QComboBox(Form)
        self.baseTrainWay.setGeometry(QtCore.QRect(320, 1080, 150, 40))

        self.fuctionTrainWay = QtWidgets.QComboBox(Form)
        self.fuctionTrainWay.setGeometry(QtCore.QRect(1180, 1080, 150, 40))

        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(1180, 50, 150, 40))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "训练时间"))
        self.label_2.setText(_translate("Form", "空间训练参数设置"))
        self.label_3.setText(_translate("Form", "图片总数（张）"))
        self.label_4.setText(_translate("Form", "播放速率（秒）"))
        self.label_5.setText(_translate("Form", "辨别难度"))
        self.checkBox.setText(_translate("MainWindow", "比ok_右"))
        self.checkBox_2.setText(_translate("MainWindow", "比数字_右"))
        self.checkBox_3.setText(_translate("MainWindow", "侧捏_右"))
        self.checkBox_4.setText(_translate("MainWindow", "尺偏_右"))
        self.checkBox_5.setText(_translate("MainWindow", "钩状抓握_右"))
        self.checkBox_6.setText(_translate("MainWindow", "拇指对食指_右"))
        self.checkBox_7.setText(_translate("MainWindow", "拇指对四指_右"))
        self.checkBox_8.setText(_translate("MainWindow", "拇指对小指指跟_右"))
        self.checkBox_9.setText(_translate("MainWindow", "拇指环转_右"))
        self.checkBox_10.setText(_translate("MainWindow", "拇指屈伸_右"))
        self.checkBox_11.setText(_translate("MainWindow", "拇指外展_右"))
        self.checkBox_12.setText(_translate("MainWindow", "球状抓握_右"))
        self.checkBox_13.setText(_translate("MainWindow", "手指内外收展_右"))
        self.checkBox_14.setText(_translate("MainWindow", "四指单独屈伸_右"))
        self.checkBox_15.setText(_translate("MainWindow", "四指屈伸_右"))
        self.checkBox_16.setText(_translate("MainWindow", "四指伸展_右"))
        self.checkBox_17.setText(_translate("MainWindow", "握拳_右"))
        self.checkBox_18.setText(_translate("MainWindow", "掌指关节屈伸 指尖关节伸展_右"))
        self.checkBox_19.setText(_translate("MainWindow", "直拳_右"))
        self.checkBox_20.setText(_translate("MainWindow", "柱状抓握_右"))
        self.checkBox_21.setText(_translate("MainWindow", "腕背伸_右"))
        self.checkBox_22.setText(_translate("MainWindow", "前臂旋后_右"))
        self.checkBox_23.setText(_translate("MainWindow", "前臂旋前_右"))
        self.checkBox_24.setText(_translate("MainWindow", "前臂旋前旋后_右"))

        self.checkBox_25.setText(_translate("MainWindow", "叠毛巾_右"))
        self.checkBox_26.setText(_translate("MainWindow", "堆棋子_右"))
        self.checkBox_27.setText(_translate("MainWindow", "翻卡片_右"))
        self.checkBox_28.setText(_translate("MainWindow", "翻木板_右"))
        self.checkBox_29.setText(_translate("MainWindow", "木棒抓握-1_右"))
        self.checkBox_30.setText(_translate("MainWindow", "木棒抓握-2_右"))
        self.checkBox_31.setText(_translate("MainWindow", "木棒抓握-3_右"))
        self.checkBox_32.setText(_translate("MainWindow", "木块-1_右"))
        self.checkBox_33.setText(_translate("MainWindow", "木块-2_右"))
        self.checkBox_34.setText(_translate("MainWindow", "拿玻璃杯_右"))
        self.checkBox_35.setText(_translate("MainWindow", "拿玻璃球_右"))
        self.checkBox_36.setText(_translate("MainWindow", "拿回行针_右"))
        self.checkBox_37.setText(_translate("MainWindow", "拿矿泉水瓶_右"))
        self.checkBox_38.setText(_translate("MainWindow", "拿铅笔_右"))
        self.checkBox_39.setText(_translate("MainWindow", "拿勺子_右"))
        self.checkBox_40.setText(_translate("MainWindow", "拿钥匙_右"))
        self.checkBox_41.setText(_translate("MainWindow", "拿易拉罐_右"))
        self.checkBox_42.setText(_translate("MainWindow", "捏夹子_右"))
        self.checkBox_43.setText(_translate("MainWindow", "握弹力球_右"))
        self.checkBox_44.setText(_translate("MainWindow", "握网球_右"))
        self.checkBox_45.setText(_translate("MainWindow", "腕背伸_右"))
        self.checkBox_46.setText(_translate("MainWindow", "前臂旋后_右"))
        self.checkBox_47.setText(_translate("MainWindow", "前臂旋前_右"))
        self.checkBox_48.setText(_translate("MainWindow", "前臂旋前旋后_右"))
        self.label_6.setText(_translate("Form", "组数"))
        self.label_7.setText(_translate("Form", "组数"))
        self.label_8.setText(_translate("Form", "基本动作训练设置"))
        self.label_9.setText(_translate("Form", "功能动作训练设置"))
        self.label_10.setText(_translate("Form", "方式"))
        self.label_11.setText(_translate("Form", "方式"))
        self.saveButton.setText(_translate("Form", "保存"))


class AddPlan(QtWidgets.QMainWindow, Ui_Form):  # 基本功能动作训练
    def __init__(self):
        super(AddPlan, self).__init__()
        self.setupUi(self)
        self.saveButton.mousePressEvent = self.saveButtonClick
        self.trianTimeDateEdit.mousePressEvent = self.trianTimeDateEditClick
        self.baseTrainnumlineEdit.mousePressEvent = self.baseTrainnumlineEditClick
        self.baseTrainWay.mousePressEvent = self.baseTrainWayClick
        self.functionTrainnumlineEdit.mousePressEvent = self.functionTrainnumlineEditClick
        self.fuctionTrainWay.mousePressEvent = self.fuctionTrainWayClick
        self.pictureNum.mousePressEvent = self.pictureNumClick
        self.playSpeed.mousePressEvent = self.playSpeedClick
        self.selecthard.mousePressEvent = self.selecthardClick

    def saveButtonClick(self, *args):  # 保存训练方案
        ...

    def trianTimeDateEditClick(self, *args):  # 训练日期
        ...

    def baseTrainnumlineEditClick(self, *args):  # 基本训练数目
        ...

    def baseTrainWayClick(self, *args):  # 基本训练方式选择
        ...

    def functionTrainnumlineEditClick(self, *args):  # 功能训练方式次数
        ...

    def fuctionTrainWayClick(self, *args):  # 功能训练方式选择
        ...

    def pictureNumClick(self, *args):  # 空间训练-图片数目
        ...

    def playSpeedClick(self, *args):  # 空间训练-播放速率
        ...

    def selecthardClick(self, *args):  # 空间训练-辨别难度
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = AddPlan()
    gui.show()
    sys.exit(app.exec_())
