# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QHeaderView


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2100, 1250)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 2100, 250))
        self.frame.setStyleSheet("background:white\n""\n""")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 120, 40))
        self.label.setStyleSheet("font:14pt")

        self.schemeNamelineEdit = QtWidgets.QLineEdit(self.frame)
        self.schemeNamelineEdit.setGeometry(QtCore.QRect(150, 20, 1500, 40))

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 12))
        self.label_2.setStyleSheet("color:red;font:12pt;")

        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 150, 40))
        self.label_3.setStyleSheet("font:14pt")

        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(160, 90, 250, 40))

        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(420, 90, 154, 40))
        self.label_4.setStyleSheet("font:14pt")

        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_2.setGeometry(QtCore.QRect(430, 90, 250, 40))

        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 150, 40))
        self.label_5.setStyleSheet("font:14pt")

        self.remarklineEdit = QtWidgets.QLineEdit(self.frame)
        self.remarklineEdit.setGeometry(QtCore.QRect(100, 140, 1500, 40))

        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(110, 200, 150, 40))

        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setGeometry(QtCore.QRect(300, 200, 150, 40))

        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setGeometry(QtCore.QRect(500, 200, 150, 40))

        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 260, 2100, 960))

        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(18)
        self.tableWidget.verticalHeader().setVisible(False)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.tableWidget.setColumnWidth(1, 200)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        self.tableWidget.setColumnWidth(2, 200)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        self.tableWidget.setColumnWidth(3, 1300)  # 设置table表格第4列的宽度，130为宽度
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        self.tableWidget.setColumnWidth(4, 200)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)

        self.frontButton = QtWidgets.QPushButton(Form)
        self.frontButton.setGeometry(QtCore.QRect(20, 1150, 150, 40))

        self.previousButton = QtWidgets.QPushButton(Form)
        self.previousButton.setGeometry(QtCore.QRect(180, 1150, 150, 40))

        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(350, 1150, 150, 40))

        self.lastButton = QtWidgets.QPushButton(Form)
        self.lastButton.setGeometry(QtCore.QRect(520, 1150, 150, 40))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "方案名称"))
        self.label_2.setText(_translate("Form", "*"))
        self.label_3.setText(_translate("Form", "计划日期"))
        self.label_4.setText(_translate("Form", "-"))
        self.label_5.setText(_translate("Form", "备注"))
        self.addButton.setText(_translate("Form", "添加训练计划"))
        self.deleteButton.setText(_translate("Form", "删除训练计划"))
        self.startButton.setText(_translate("Form", "开始训练"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "计划时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "训练模式"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "训练内容"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "训练状态"))

        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.setSelectionBehavior(QHeaderView.SelectRows)
        self.tableWidget.setSelectionMode(QTableWidget.SingleSelection)

        self.frontButton.setText(_translate("Form", "首页"))
        self.previousButton.setText(_translate("Form", "上一页"))
        self.nextButton.setText(_translate("Form", "下一页"))
        self.lastButton.setText(_translate("Form", "尾页"))


class AddTrainingPlan(QtWidgets.QMainWindow, Ui_Form):
    # singal = pyqtSignal(list)
    def __init__(self):
        super(AddTrainingPlan, self).__init__()
        self.setupUi(self)
        self.addButton.mousePressEvent = self.addButtonClick
        self.deleteButton.mousePressEvent = self.deleteButtonClick
        self.startButton.mousePressEvent = self.startButtonClick
        self.frontButton.mousePressEvent = self.frontButtonClick
        self.nextButton.mousePressEvent = self.nextButtonClick
        self.previousButton.mousePressEvent = self.previousButtonClick
        self.lastButton.mousePressEvent = self.lastClick

    def addButtonClick(self, *args):  # 添加训练计划

        ...

    def deleteButtonClick(self, *args):  # 删除训练计划

        ...

    def startButtonClick(self, *args):  # 开始训练，跳到相应界面

        ...

    def frontButtonClick(self, *args):  # 首页

        ...

    def previousButtonClick(self, *args):  # 上一页

        ...

    def nextButtonClick(self, *args):  # 下一页

        ...

    def lastClick(self, *args):  # 尾页
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = AddTrainingPlan()
    gui.show()
    sys.exit(app.exec_())
