# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):#基本训练-病人界面
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.leftlistView = QtWidgets.QListView(Form)
        self.leftlistView.setGeometry(QtCore.QRect(0, 0,960, 1080))
        self.leftlistView.setObjectName("leftlistView")
        self.rightlistView = QtWidgets.QListView(Form)
        self.rightlistView.setGeometry(QtCore.QRect(960, 0,960, 1080))
        self.rightlistView.setObjectName("rightlistView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
class basic_Patient(QtWidgets.QMainWindow, Ui_Form):  # 基本功能动作训练
    def __init__(self):
        super(basic_Patient, self).__init__()
        self.setupUi(self)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = basic_Patient()
    gui.show()
    sys.exit(app.exec_())
