# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

###########基本功能训练界面
import sys

from PyQt5 import QtCore, QtWidgets
from pyqt5_plugins.examplebuttonplugin import QtGui

import frontend.FunctionalTraining


class Ui_MainWindow(object):
    def __init__(self):
        self.selectCheckBox = []
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.setStyleSheet("background-color:white")

        MainWindow.resize(2200, 1280)  # (2200,1400)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 2180, 1200))
        self.label.setStyleSheet("background-color:  white ")

        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(10, 69, 2180, 2))
        self.background_label.setStyleSheet("background-color:#FFD700")

        # self.buttton_label = QtWidgets.QLabel(self.centralwidget)
        # self.buttton_label.setGeometry(QtCore.QRect(0, 0, self.screenwidth, 70))
        # self.buttton_label.setStyleSheet("background-color: #FFFFCD ")

        self.spatialImaginationRainingButton = QtWidgets.QPushButton(self.centralwidget)  # 空间想象训练按钮
        self.spatialImaginationRainingButton.setGeometry(QtCore.QRect(10, 0, 200, 70))
        self.spatialImaginationRainingButton.setObjectName("pushButton")
        self.spatialImaginationRainingButton.setStyleSheet('''QPushButton{
                                                            color: black;
                                                            font:16pt;
                                                            border:1px groove white;
                                                            
                                                        }
                                                    QPushButton:hover{
                                                            background-color: #FFD700;
                                                            color:white}
                                                    QPushButton:pressed{
                                                            background-color: rgba(235, 235, 235,100);}
                                                   ''')
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 0, 200, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet('''QPushButton{    background-color: #FFD700;
                                                            color:white;
                                                            font:16pt;
                                                            border:1px groove white;
                                                        }''')
        self.motiveTrainingButton = QtWidgets.QPushButton(self.centralwidget)
        self.motiveTrainingButton.setGeometry(QtCore.QRect(410, 0, 200, 70))
        self.motiveTrainingButton.setStyleSheet('''QPushButton{
                                                            color: black;
                                                            font:16pt;
                                                            border:1px groove white;
                                                        }
                                                    QPushButton:hover{
                                                            background-color: #FFD700;
                                                            color:white}
                                                    QPushButton:pressed{
                                                            background-color: rgba(235, 235, 235,100);}
                                                   ''')

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(70, 200, 650, 850))
        self.scrollArea.setWidgetResizable(True)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setMinimumWidth(1000)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -13, 1000, 850))

        font = QtGui.QFont()
        font.setFamily("KaiTi_GB2312")
        font.setPointSize(16)
        self.checkBox_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 比ok
        self.checkBox_1.setGeometry(QtCore.QRect(10, 5, 160, 80))
        self.checkBox_1.setFont(font)

        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 比数字
        self.checkBox_2.setGeometry(QtCore.QRect(10, 55, 170, 80))
        self.checkBox_2.setFont(font)

        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 侧捏
        self.checkBox_3.setGeometry(QtCore.QRect(10, 105, 160, 80))
        self.checkBox_3.setFont(font)

        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 尺偏
        self.checkBox_4.setGeometry(QtCore.QRect(10, 155, 150, 80))
        self.checkBox_4.setFont(font)

        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 钩状抓握
        self.checkBox_5.setGeometry(QtCore.QRect(10, 205, 240, 80))
        self.checkBox_5.setFont(font)

        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对食指
        self.checkBox_6.setGeometry(QtCore.QRect(10, 255, 240, 80))
        self.checkBox_6.setFont(font)

        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对四指
        self.checkBox_7.setGeometry(QtCore.QRect(10, 305, 240, 80))
        self.checkBox_7.setFont(font)

        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指对小指指跟
        self.checkBox_8.setGeometry(QtCore.QRect(10, 355, 300, 80))
        self.checkBox_8.setFont(font)

        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指环转
        self.checkBox_9.setGeometry(QtCore.QRect(10, 405, 200, 80))
        self.checkBox_9.setFont(font)

        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指外展
        self.checkBox_10.setGeometry(QtCore.QRect(10, 455, 200, 80))
        self.checkBox_10.setFont(font)

        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 拇指屈伸
        self.checkBox_11.setGeometry(QtCore.QRect(10, 505, 200, 80))
        self.checkBox_11.setFont(font)

        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 球状抓握
        self.checkBox_12.setGeometry(QtCore.QRect(10, 555, 200, 80))
        self.checkBox_12.setFont(font)

        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 手指内外收展
        self.checkBox_13.setGeometry(QtCore.QRect(10, 605, 280, 80))
        self.checkBox_13.setFont(font)

        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指单独屈伸
        self.checkBox_14.setGeometry(QtCore.QRect(10, 655, 280, 80))
        self.checkBox_14.setFont(font)

        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指屈伸
        self.checkBox_15.setGeometry(QtCore.QRect(10, 705, 240, 80))
        self.checkBox_15.setFont(font)

        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 四指伸展
        self.checkBox_16.setGeometry(QtCore.QRect(340, 5, 200, 80))
        self.checkBox_16.setFont(font)

        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 握拳
        self.checkBox_17.setGeometry(QtCore.QRect(340, 55, 200, 80))
        self.checkBox_17.setFont(font)

        self.checkBox_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 掌指关节屈伸 指尖关节伸展_右
        self.checkBox_18.setGeometry(QtCore.QRect(340, 105, 490, 80))
        self.checkBox_18.setFont(font)

        self.checkBox_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 直拳
        self.checkBox_19.setGeometry(QtCore.QRect(340, 155, 160, 80))
        self.checkBox_19.setFont(font)

        self.checkBox_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 柱状抓握
        self.checkBox_20.setGeometry(QtCore.QRect(340, 205, 200, 80))
        self.checkBox_20.setFont(font)

        self.checkBox_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 腕背伸
        self.checkBox_21.setGeometry(QtCore.QRect(340, 255, 200, 80))
        self.checkBox_21.setFont(font)

        self.checkBox_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋后
        self.checkBox_22.setGeometry(QtCore.QRect(340, 305, 200, 80))
        self.checkBox_22.setFont(font)

        self.checkBox_23 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋前
        self.checkBox_23.setGeometry(QtCore.QRect(340, 355, 200, 80))
        self.checkBox_23.setFont(font)

        self.checkBox_24 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)  # 前臂旋前旋后
        self.checkBox_24.setGeometry(QtCore.QRect(340, 405, 300, 80))
        self.checkBox_24.setFont(font)

        self.cancelAllButton = QtWidgets.QPushButton(self.centralwidget)  # 全部取消
        self.cancelAllButton.setGeometry(QtCore.QRect(60, 1060, 130, 50))
        self.cancelAllButton.setStyleSheet('''QPushButton{
                                                                           color: white;
                                                                           font:16pt;
                                                                           background-color:#FFD700;
                                                                            border:1px groove white;
                                                                       }

                                                                  ''')

        self.label_2 = QtWidgets.QLabel(self.centralwidget)  # 组数
        self.label_2.setGeometry(QtCore.QRect(220, 1060, 100, 50))
        self.label_2.setStyleSheet('''QLabel{
                                                             font:30px;
                                                             color:black;}''')

        self.trianingNum = QtWidgets.QLineEdit(self.centralwidget)  # 组数次数
        self.trianingNum.setGeometry(QtCore.QRect(290, 1060, 140, 40))

        self.label_3 = QtWidgets.QLabel(self.centralwidget)  # 方式
        self.label_3.setGeometry(QtCore.QRect(440, 1060, 100, 50))
        self.label_3.setStyleSheet('''QLabel{
                                                                    font:30px;
                                                                    color:black;}''')

        self.selectWay = QtWidgets.QComboBox(self.centralwidget)
        self.selectWay.setGeometry(QtCore.QRect(510, 1060, 140, 40))  # 方式选择
        self.selectWay.addItems(['AABB', 'ABAB'])

        self.recommendButton = QtWidgets.QPushButton(self.centralwidget)  # 推荐
        self.recommendButton.setGeometry(QtCore.QRect(60, 1120, 130, 50))
        self.recommendButton.setStyleSheet('''QPushButton{
                                                                        color: white;
                                                                        font:16pt;
                                                                        background-color:#FFD700;
                                                                         border:1px groove white;
                                                                    }

                                                               ''')

        self.selectAllButton = QtWidgets.QPushButton(self.centralwidget)  # 全部选择
        self.selectAllButton.setGeometry(QtCore.QRect(260, 1120, 160, 50))
        self.selectAllButton.setStyleSheet('''QPushButton{
                                                                        color: white;
                                                                        font:16pt;
                                                                        background-color:#FFD700;
                                                                         border:1px groove white;
                                                                    }

                                                               ''')

        self.startTraining = QtWidgets.QPushButton(self.centralwidget)  # 开始训练
        self.startTraining.setGeometry(QtCore.QRect(480, 1120, 160, 50))
        self.startTraining.setStyleSheet('''QPushButton{
                                                                        color: white;
                                                                        font:16pt;
                                                                        background-color:#FFD700;
                                                                         border:1px groove white;
                                                                    }

                                                               ''')

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 130, 100, 50))
        self.label_4.setStyleSheet('''QLabel{
                                                font:30px;
                                                color:#FFD700;}''')

        self.label_5 = QtWidgets.QLabel(self.centralwidget)  # 右手
        self.label_5.setGeometry(QtCore.QRect(1520, 130, 100, 50))
        self.label_5.setStyleSheet('''QLabel{
                                                     font:30px;
                                                     color:#FFD700;}''')

        self.listView_2 = QtWidgets.QListView(self.centralwidget)  # 左手镜像
        self.listView_2.setGeometry(QtCore.QRect(820, 180, 650, 850))

        self.listView_3 = QtWidgets.QListView(self.centralwidget)  # 右手镜像
        self.listView_3.setGeometry(QtCore.QRect(1500, 180, 650, 850))

        self.leftMiorrButton = QtWidgets.QPushButton(self.centralwidget)  # 左手镜像
        self.leftMiorrButton.setGeometry(QtCore.QRect(940, 125, 120, 50))
        self.leftMiorrButton.setStyleSheet('''QPushButton{
                                                                   color: white;
                                                                   font:16pt;
                                                                   background-color:#FFD700;
                                                                    border:1px groove white;
                                                               }
                                                
                                                          ''')

        self.leftCopyButton = QtWidgets.QPushButton(self.centralwidget)  # 左手复制
        self.leftCopyButton.setGeometry(QtCore.QRect(1060, 125, 120, 50))
        self.leftCopyButton.setStyleSheet('''QPushButton{
                                                                           color: white;
                                                                           font:16pt;
                                                                           background-color:#FFD700;
                                                                            border:1px groove white;
                                                                       }

                                                                  ''')

        self.leftMaskButton = QtWidgets.QPushButton(self.centralwidget)  # 左手遮罩
        self.leftMaskButton.setGeometry(QtCore.QRect(1180, 125, 120, 50))
        self.leftMaskButton.setStyleSheet('''QPushButton{
                                                                                  color: white;
                                                                                  font:16pt;
                                                                                  background-color:#FFD700;
                                                                                   border:1px groove white;
                                                                              }

                                                                         ''')

        self.leftPlayButton = QtWidgets.QPushButton(self.centralwidget)  # 左手播放
        self.leftPlayButton.setGeometry(QtCore.QRect(820, 1035, 120, 50))
        self.leftPlayButton.setStyleSheet('''QPushButton{
                                                                                          color: white;
                                                                                          font:16pt;
                                                                                          background-color:#FFD700;
                                                                                           border:1px groove white;
                                                                                      }

                                                                                 ''')

        self.leftRecordButton = QtWidgets.QPushButton(self.centralwidget)  # 左手录制
        self.leftRecordButton.setGeometry(QtCore.QRect(950, 1035, 120, 50))
        self.leftRecordButton.setStyleSheet('''QPushButton{
                                                                                          color: white;
                                                                                          font:16pt;
                                                                                          background-color:#FFD700;
                                                                                           border:1px groove white;
                                                                                      }

                                                                                 ''')

        self.rightMiorrButton = QtWidgets.QPushButton(self.centralwidget)  # 右手镜像
        self.rightMiorrButton.setGeometry(QtCore.QRect(1640, 125, 120, 50))
        self.rightMiorrButton.setStyleSheet('''QPushButton{
                                                                                          color: white;
                                                                                          font:16pt;
                                                                                          background-color:#FFD700;
                                                                                           border:1px groove white;
                                                                                      }

                                                                                 ''')

        self.rightCopyButton = QtWidgets.QPushButton(self.centralwidget)  # 右手复制
        self.rightCopyButton.setGeometry(QtCore.QRect(1760, 125, 120, 50))
        self.rightCopyButton.setStyleSheet('''QPushButton{
                                                                                          color: white;
                                                                                          font:16pt;
                                                                                          background-color:#FFD700;
                                                                                           border:1px groove white;
                                                                                      }

                                                                                 ''')

        self.rightMaskButton = QtWidgets.QPushButton(self.centralwidget)  # 右手遮罩
        self.rightMaskButton.setGeometry(QtCore.QRect(1880, 125, 120, 50))
        self.rightMaskButton.setStyleSheet('''QPushButton{
                                                                                          color: white;
                                                                                          font:16pt;
                                                                                          background-color:#FFD700;
                                                                                           border:1px groove white;
                                                                                      }

                                                                                 ''')

        self.rightPlayButton = QtWidgets.QPushButton(self.centralwidget)  # 右手播放
        self.rightPlayButton.setGeometry(QtCore.QRect(1500, 1035, 120, 50))
        self.rightPlayButton.setStyleSheet('''QPushButton{
                                                                                                  color: white;
                                                                                                  font:16pt;
                                                                                                  background-color:#FFD700;
                                                                                                   border:1px groove white;
                                                                                              }

                                                                                         ''')

        self.rightRecordButton = QtWidgets.QPushButton(self.centralwidget)  # 右手录制
        self.rightRecordButton.setGeometry(QtCore.QRect(1630, 1035, 120, 50))
        self.rightRecordButton.setStyleSheet('''QPushButton{
                                                                                                  color: white;
                                                                                                  font:16pt;
                                                                                                  background-color:#FFD700;
                                                                                                   border:1px groove white;
                                                                                              }

                                                                                         ''')

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spatialImaginationRainingButton.setText(_translate("MainWindow", "空间想象训练"))
        self.pushButton_2.setText(_translate("MainWindow", "基本动作训练"))
        self.motiveTrainingButton.setText(_translate("MainWindow", "功能动作训练"))
        self.checkBox_1.setText(_translate("MainWindow", "比ok_右"))
        self.checkBox_2.setText(_translate("MainWindow", "比数字_右"))
        self.checkBox_3.setText(_translate("MainWindow", "侧捏_右"))
        self.checkBox_4.setText(_translate("MainWindow", "尺偏_右"))
        self.checkBox_5.setText(_translate("MainWindow", "钩状抓握_右"))
        self.checkBox_6.setText(_translate("MainWindow", "拇指对食指_右"))
        self.checkBox_7.setText(_translate("MainWindow", "拇指对四指_右"))
        self.checkBox_8.setText(_translate("MainWindow", "拇指对小指指跟_右"))
        self.checkBox_9.setText(_translate("MainWindow", "拇指环转_右"))
        self.checkBox_10.setText(_translate("MainWindow", "拇指屈伸_右"))
        self.checkBox_11.setText(_translate("MainWindow", "拇指外展_右"))
        self.checkBox_12.setText(_translate("MainWindow", "球状抓握_右"))
        self.checkBox_13.setText(_translate("MainWindow", "手指内外收展_右"))
        self.checkBox_14.setText(_translate("MainWindow", "四指单独屈伸_右"))
        self.checkBox_15.setText(_translate("MainWindow", "四指屈伸_右"))
        self.checkBox_16.setText(_translate("MainWindow", "四指伸展_右"))
        self.checkBox_17.setText(_translate("MainWindow", "握拳_右"))
        self.checkBox_18.setText(_translate("MainWindow", "掌指关节屈伸 指尖关节伸展_右"))
        self.checkBox_19.setText(_translate("MainWindow", "直拳_右"))
        self.checkBox_20.setText(_translate("MainWindow", "柱状抓握_右"))
        self.checkBox_21.setText(_translate("MainWindow", "腕背伸_右"))
        self.checkBox_22.setText(_translate("MainWindow", "前臂旋后_右"))
        self.checkBox_23.setText(_translate("MainWindow", "前臂旋前_右"))
        self.checkBox_24.setText(_translate("MainWindow", "前臂旋前旋后_右"))
        self.cancelAllButton.setText(_translate("MainWindow", "全部取消"))
        self.label_2.setText(_translate("MainWindow", "组数"))
        self.label_3.setText(_translate("MainWindow", "方式"))
        self.recommendButton.setText(_translate("MainWindow", "推荐"))
        self.selectAllButton.setText(_translate("MainWindow", "全部"))
        self.startTraining.setText(_translate("MainWindow", "开始训练"))
        self.label_4.setText(_translate("MainWindow", "左手"))
        self.label_5.setText(_translate("MainWindow", "右手"))
        self.leftMiorrButton.setText(_translate("MainWindow", "镜像"))
        self.leftCopyButton.setText(_translate("MainWindow", "复制"))
        self.leftMaskButton.setText(_translate("MainWindow", "遮罩"))
        self.leftPlayButton.setText(_translate("MainWindow", "播放"))
        self.leftRecordButton.setText(_translate("MainWindow", "录制"))
        self.rightMiorrButton.setText(_translate("MainWindow", "镜像"))  # 右手
        self.rightCopyButton.setText(_translate("MainWindow", "复制"))
        self.rightMaskButton.setText(_translate("MainWindow", "遮罩"))
        self.rightPlayButton.setText(_translate("MainWindow", "播放"))
        self.rightRecordButton.setText(_translate("MainWindow", "录制"))


class BasicTraining(QtWidgets.QMainWindow, Ui_MainWindow):  # 基本功能动作训练
    def __init__(self):
        super(BasicTraining, self).__init__()
        self.setupUi(self)
        self.motiveTrainingButton.mousePressEvent = self.motiveTrainingButtonLeftClick
        self.spatialImaginationRainingButton.mousePressEvent = self.spatialImaginationRainingLeftClick
        self.cancelAllButton.mousePressEvent = self.cancelAllButtonClick
        self.selectAllButton.mousePressEvent = self.selectAllButtonClick
        self.startTraining.mousePressEvent = self.startTrainingClick
        self.recommendButton.mousePressEvent = self.recommendButtonClick
        self.leftMiorrButton.mousePressEvent = self.leftMirrorButtonClick
        self.leftCopyButton.mousePressEvent = self.leftCopyButtonButtonClick
        self.leftMaskButton.mousePressEvent = self.leftMaskButtonClick
        self.leftPlayButton.mousePressEvent = self.leftPlayButtonClick
        self.leftRecordButton.mousePressEvent = self.leftRecordButtonClick
        self.rightMiorrButton.mousePressEvent = self.rightMirrorButtonClick
        self.rightCopyButton.mousePressEvent = self.rightCopyButtonButtonClick
        self.rightMaskButton.mousePressEvent = self.rightMaskButtonClick
        self.rightPlayButton.mousePressEvent = self.rightPlayButtonClick
        self.rightRecordButton.mousePressEvent = self.rightRecordButtonClick

        self.checkBoxWidget = [getattr(self, f'checkBox_{i}') for i in range(1, 25)]
        self.checkBoxName = [i.text() for i in self.checkBoxWidget]

        self.basicTrainingPatientWindow = frontend.BasicTrainingPatient.BasicTrainingPatient()
        self.basicTrainingPatientWindow.show()

    def closeEvent(self, a0: QtGui.QCloseEvent):
        self.basicTrainingPatientWindow.close()

    def motiveTrainingButtonLeftClick(self, *args):
        motiveTraining = frontend.FunctionalTraining.FunctionalTraining()
        motiveTraining.show()
        self.close()

    def spatialImaginationRainingLeftClick(self, *args):
        spatialImaginationRaining = frontend.SpatialImaginationTraining.SpatialImaginationTraining()
        spatialImaginationRaining.show()
        self.close()
        pass

    def cancelAllButtonClick(self, *args):  # 全部取消
        # 对所有被选中的复选框进行取消
        ...

    def selectAllButtonClick(self, *args):  # 全部选择
        # 选择所有的选项
        ...

    def startTrainingClick(self, *args):  # 开始训练
        traingNum = self.trianingNum.text()  # 训练次数
        #  selectWay=self.selectWay.
        # 获取训练的方式，根据方式决定视频播放顺序
        # 分频界面出现模拟视频
        ...

    def recommendButtonClick(self, *args):  # 推荐
        # 暂时没法写
        pass

    def leftMirrorButtonClick(self, *args):  # 左手镜像
        # 患者界面变化
        ...

    def leftCopyButtonButtonClick(self, *args):  # 左手复制
        #
        ...

    def leftRecordButtonClick(self, *args):  # 左手遮罩
        #
        ...

    def leftPlayButtonClick(self, *args):  # 左手播放
        #
        ...

    def leftMaskButtonClick(self, *args):  # 左手录制
        #
        ...

    def rightMirrorButtonClick(self, *args):  # 右手镜像
        # 患者界面变化
        ...

    def rightCopyButtonButtonClick(self, *args):  # 右手复制
        #
        ...

    def rightMaskButtonClick(self, *args):  # 右手遮罩
        #
        ...

    def rightPlayButtonClick(self, *args):  # 右手播放
        #
        ...

    def rightRecordButtonClick(self, *args):  # 右手录制
        ...

    # def rightMaskButtonClick(self,*args):#右手录制
    #     ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = BasicTraining()
    gui.show()
    sys.exit(app.exec_())
