# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.resize(1500, 1000)
        Form.setStyleSheet("background:#f0faff")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 150, 60))
        self.label.setStyleSheet("background:#1E90FF;font:14pt;color:white")

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(0, 60, 1500, 4))
        self.label_8.setStyleSheet("background:#1E90FF;")

        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 80, 500, 880))
        self.tableWidget.setStyleSheet("background:white;")
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.setColumnWidth(2, 190)

        self.frontButton = QtWidgets.QPushButton(Form)
        self.frontButton.setGeometry(QtCore.QRect(40, 880, 120, 40))

        self.previousButton = QtWidgets.QPushButton(Form)
        self.previousButton.setGeometry(QtCore.QRect(160, 880, 120, 40))

        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(280, 880, 120, 40))

        self.lastButton = QtWidgets.QPushButton(Form)
        self.lastButton.setGeometry(QtCore.QRect(400, 880, 120, 40))

        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(570, 80, 900, 880))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setStyleSheet("background:white;")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 200, 40))
        self.label_2.setStyleSheet("font:19pt")

        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 54, 40))
        self.label_3.setStyleSheet("font:10pt;color:red")

        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 100, 40))
        self.label_4.setStyleSheet("font:12pt")

        self.teamNamelineEdit = QtWidgets.QLineEdit(self.frame)
        self.teamNamelineEdit.setGeometry(QtCore.QRect(160, 70, 700, 30))
        self.teamNamelineEdit.setObjectName("teamNamelineEdit")

        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 54, 40))
        self.label_5.setStyleSheet("font:10pt;color:red")

        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 150, 100, 40))
        self.label_6.setStyleSheet("font:12pt")

        self.illustratelineEdit = QtWidgets.QLineEdit(self.frame)
        self.illustratelineEdit.setGeometry(QtCore.QRect(160, 150, 700, 150))

        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 350, 120, 40))
        self.label_7.setStyleSheet("font:12pt")

        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(160, 350, 700, 400))

        self.systemAdministratorCheckBox = QtWidgets.QCheckBox(self.frame)
        self.systemAdministratorCheckBox.setGeometry(QtCore.QRect(170, 380, 170, 40))
        self.systemAdministratorCheckBox.setStyleSheet("font:12pt")

        self.user1checkBox = QtWidgets.QCheckBox(self.frame)
        self.user1checkBox.setGeometry(QtCore.QRect(170, 430, 170, 40))
        self.user1checkBox.setStyleSheet("font:12pt")

        self.user2checkBox = QtWidgets.QCheckBox(self.frame)
        self.user2checkBox.setGeometry(QtCore.QRect(170, 490, 170, 40))
        self.user2checkBox.setStyleSheet("font:12pt")

        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(170, 780, 100, 40))

        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setGeometry(QtCore.QRect(330, 780, 100, 40))

        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(490, 780, 100, 40))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "科研小组"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "组名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "说明"))
        self.label_2.setText(_translate("Form", "详细信息"))
        self.label_3.setText(_translate("Form", "*"))
        self.label_4.setText(_translate("Form", "组名"))
        self.label_5.setText(_translate("Form", "*"))
        self.label_6.setText(_translate("Form", "说明"))
        self.label_7.setText(_translate("Form", "小组成员"))
        self.systemAdministratorCheckBox.setText(_translate("Form", "系统管理员"))
        self.user1checkBox.setText(_translate("Form", "用户1"))
        self.user2checkBox.setText(_translate("Form", "用户2"))
        self.addButton.setText(_translate("Form", "新增"))
        self.deleteButton.setText(_translate("Form", "删除"))
        self.saveButton.setText(_translate("Form", "保存"))
        self.frontButton.setText(_translate("Form", "首页"))
        self.previousButton.setText(_translate("Form", "上一页"))
        self.nextButton.setText(_translate("Form", "下一页"))
        self.lastButton.setText(_translate("Form", "尾页"))


class researchTeam(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super(researchTeam, self).__init__()
        self.setupUi(self)
        self.frontButton.mousePressEvent = self.frontButtonClick
        self.nextButton.mousePressEvent = self.nextButtonClick
        self.previousButton.mousePressEvent = self.previousButtonClick
        self.lastButton.mousePressEvent = self.lastClick
        self.addButton.mousePressEvent = self.addButtonClick
        self.deleteButton.mousePressEvent = self.deleteButtonClick
        self.saveButton.mousePressEvent = self.saveButtonClick

    def frontButtonClick(self, *args):  # 首页

        ...

    def previousButtonClick(self, *args):  # 上一页

        ...

    def nextButtonClick(self, *args):  # 下一页

        ...

    def lastClick(self, *args):  # 尾页
        ...

    def addButtonClick(self, *args):  # 新增

        ...

    def deleteButtonClick(self, *args):  # 删除

        ...

    def saveButtonClick(self, *args):  # 保持
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = researchTeam()
    gui.show()
    sys.exit(app.exec_())
