# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '窗口1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.frame_sub = QtWidgets.QFrame(self.centralwidget)
        self.frame_sub.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.frame_sub.setStyleSheet("QFrame {background-color:rgb(242, 249, 255);}")
        self.frame_sub.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sub.setFrameShadow(QtWidgets.QFrame.Raised)

        self.label_3 = QtWidgets.QLabel(self.frame_sub)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 101, 40))
        self.label_3.setText('*')
        self.label_3.setStyleSheet("font:10pt;color:red")

        self.label = QtWidgets.QLabel(self.frame_sub)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 40))
        self.label.setStyleSheet("font:12pt")

        self.discriminationDifficultyComboBox = QtWidgets.QComboBox(self.frame_sub)
        self.discriminationDifficultyComboBox.setGeometry(QtCore.QRect(140, 30, 250, 40))
        self.discriminationDifficultyComboBox.addItems(['', '低难度', '中难度',  '高难度'])
        self.discriminationDifficultyComboBox.setStyleSheet("font:12pt")

        self.label_4 = QtWidgets.QLabel(self.frame_sub)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 40))
        self.label_4.setText('*')
        self.label_4.setStyleSheet("font:10pt;color:red")

        self.label_2 = QtWidgets.QLabel(self.frame_sub)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 101, 31))
        self.label_2.setStyleSheet("font:12pt")

        self.pictureTypeComboBox = QtWidgets.QComboBox(self.frame_sub)
        self.pictureTypeComboBox.setGeometry(QtCore.QRect(140, 100, 250, 40))
        self.pictureTypeComboBox.addItems(['', '左', '右'])
        self.pictureTypeComboBox.setStyleSheet("font:12pt")

        self.deletePictureButton = QtWidgets.QPushButton(self.frame_sub)
        self.deletePictureButton.setGeometry(QtCore.QRect(140, 180, 180, 50))
        self.deletePictureButton.setStyleSheet("background-color:rgb(1, 144, 202);border:none;font:12pt;color:white")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "辨别难度："))
        self.label_2.setText(_translate("MainWindow", "图片类型："))
        self.deletePictureButton.setText(_translate("MainWindow", "删除图片"))


class setSystemSpaceImageDeleteButtonInterface(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(setSystemSpaceImageDeleteButtonInterface, self).__init__()
        self.setupUi(self)
        self.deletePictureButton.clicked.connect(self.deletePictureButtonClick)

    def deletePictureButtonClick(self, *args):  # 系统设置-空间想象参数设置-批量删除图片
        ...


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = setSystemSpaceImageDeleteButtonInterface()
    gui.show()
    sys.exit(app.exec_())
